/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CnpjEmpresa,
  CnpjListagem,
} from '../models';
import {
    CnpjEmpresaFromJSON,
    CnpjEmpresaToJSON,
    CnpjListagemFromJSON,
    CnpjListagemToJSON,
} from '../models';

export interface ConsultarCnpjRequest {
    cnpj: string;
}

export interface ListarCnpjRequest {
    cnaePrincipal: string;
    municipio: string;
    naturezaJuridica: string;
    $top?: number;
    $skip?: number;
    $inlinecount?: boolean;
}

/**
 * 
 */
export class CnpjApi extends runtime.BaseAPI {

    /**
     * **Informações adicionais**:  - Consumo: 0,1 unidade por requisição.  - Em sandbox, a consulta é permitida somente para os seguintes CNPJ:    `18760540000139`    `00038166000105`    `00394460000141`    `29979036000140`
     * Consultar dados do CNPJ
     */
    async consultarCnpjRaw(requestParameters: ConsultarCnpjRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CnpjEmpresa>> {
        if (requestParameters.cnpj === null || requestParameters.cnpj === undefined) {
            throw new runtime.RequiredError('cnpj','Required parameter requestParameters.cnpj was null or undefined when calling consultarCnpj.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/cnpj/{Cnpj}`.replace(`{${"Cnpj"}}`, encodeURIComponent(String(requestParameters.cnpj))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CnpjEmpresaFromJSON(jsonValue));
    }

    /**
     * **Informações adicionais**:  - Consumo: 0,1 unidade por requisição.  - Em sandbox, a consulta é permitida somente para os seguintes CNPJ:    `18760540000139`    `00038166000105`    `00394460000141`    `29979036000140`
     * Consultar dados do CNPJ
     */
    async consultarCnpj(requestParameters: ConsultarCnpjRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CnpjEmpresa> {
        const response = await this.consultarCnpjRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retorna uma lista de estabelecimentos de acordo com os critérios de busca utilizados.  Somente serão retornados estabelecimentos com situação cadastral \"Ativa\".    **Informações adicionais**:  - Consumo: 0,1 unidade por estabelecimento listado ou requisição.  - Em sandbox, a consulta de listagem de CNPJ não é permitida.
     * Listar estabelecimentos ativos a partir da base de CNPJ
     */
    async listarCnpjRaw(requestParameters: ListarCnpjRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CnpjListagem>> {
        if (requestParameters.cnaePrincipal === null || requestParameters.cnaePrincipal === undefined) {
            throw new runtime.RequiredError('cnaePrincipal','Required parameter requestParameters.cnaePrincipal was null or undefined when calling listarCnpj.');
        }

        if (requestParameters.municipio === null || requestParameters.municipio === undefined) {
            throw new runtime.RequiredError('municipio','Required parameter requestParameters.municipio was null or undefined when calling listarCnpj.');
        }

        if (requestParameters.naturezaJuridica === null || requestParameters.naturezaJuridica === undefined) {
            throw new runtime.RequiredError('naturezaJuridica','Required parameter requestParameters.naturezaJuridica was null or undefined when calling listarCnpj.');
        }

        const queryParameters: any = {};

        if (requestParameters.$top !== undefined) {
            queryParameters['$top'] = requestParameters.$top;
        }

        if (requestParameters.$skip !== undefined) {
            queryParameters['$skip'] = requestParameters.$skip;
        }

        if (requestParameters.$inlinecount !== undefined) {
            queryParameters['$inlinecount'] = requestParameters.$inlinecount;
        }

        if (requestParameters.cnaePrincipal !== undefined) {
            queryParameters['cnae_principal'] = requestParameters.cnaePrincipal;
        }

        if (requestParameters.municipio !== undefined) {
            queryParameters['municipio'] = requestParameters.municipio;
        }

        if (requestParameters.naturezaJuridica !== undefined) {
            queryParameters['natureza_juridica'] = requestParameters.naturezaJuridica;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/cnpj`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CnpjListagemFromJSON(jsonValue));
    }

    /**
     * Retorna uma lista de estabelecimentos de acordo com os critérios de busca utilizados.  Somente serão retornados estabelecimentos com situação cadastral \"Ativa\".    **Informações adicionais**:  - Consumo: 0,1 unidade por estabelecimento listado ou requisição.  - Em sandbox, a consulta de listagem de CNPJ não é permitida.
     * Listar estabelecimentos ativos a partir da base de CNPJ
     */
    async listarCnpj(requestParameters: ListarCnpjRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CnpjListagem> {
        const response = await this.listarCnpjRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
