/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CteOsCartaCorrecao,
  CteOsPedidoCancelamento,
  CteOsPedidoCartaCorrecao,
  CteOsPedidoEmissao,
  Dfe,
  DfeCancelamento,
  DfeEvento,
  DfeListagem,
  DfeSefazStatus,
  DfeSincronizacao,
} from '../models';
import {
    CteOsCartaCorrecaoFromJSON,
    CteOsCartaCorrecaoToJSON,
    CteOsPedidoCancelamentoFromJSON,
    CteOsPedidoCancelamentoToJSON,
    CteOsPedidoCartaCorrecaoFromJSON,
    CteOsPedidoCartaCorrecaoToJSON,
    CteOsPedidoEmissaoFromJSON,
    CteOsPedidoEmissaoToJSON,
    DfeFromJSON,
    DfeToJSON,
    DfeCancelamentoFromJSON,
    DfeCancelamentoToJSON,
    DfeEventoFromJSON,
    DfeEventoToJSON,
    DfeListagemFromJSON,
    DfeListagemToJSON,
    DfeSefazStatusFromJSON,
    DfeSefazStatusToJSON,
    DfeSincronizacaoFromJSON,
    DfeSincronizacaoToJSON,
} from '../models';

export interface BaixarPdfCancelamentoCteOsRequest {
    id: string;
}

export interface BaixarPdfCartaCorrecaoCteOsRequest {
    id: string;
}

export interface BaixarPdfCteOsRequest {
    id: string;
    logotipo?: boolean;
}

export interface BaixarPdfEventoCteOsRequest {
    id: string;
}

export interface BaixarXmlCancelamentoCteOsRequest {
    id: string;
}

export interface BaixarXmlCartaCorrecaoCteOsRequest {
    id: string;
}

export interface BaixarXmlCteOsRequest {
    id: string;
}

export interface BaixarXmlCteOsConhecimentoRequest {
    id: string;
}

export interface BaixarXmlCteOsProtocoloRequest {
    id: string;
}

export interface BaixarXmlEventoCteOsRequest {
    id: string;
}

export interface CancelarCteOsRequest {
    id: string;
    body?: CteOsPedidoCancelamento;
}

export interface ConsultarCancelamentoCteOsRequest {
    id: string;
}

export interface ConsultarCartaCorrecaoCteOsRequest {
    id: string;
}

export interface ConsultarCteOsRequest {
    id: string;
}

export interface ConsultarEventoCteOsRequest {
    id: string;
}

export interface ConsultarStatusSefazCteOsRequest {
    cpfCnpj: string;
    autorizador?: string;
}

export interface CriarCartaCorrecaoCteOsRequest {
    id: string;
    body: CteOsPedidoCartaCorrecao;
}

export interface EmitirCteOsRequest {
    body: CteOsPedidoEmissao;
}

export interface ListarCteOsRequest {
    cpfCnpj: string;
    ambiente: string;
    $top?: number;
    $skip?: number;
    $inlinecount?: boolean;
    referencia?: string;
    chave?: string;
    serie?: string;
}

export interface SincronizarCteOsRequest {
    id: string;
}

/**
 * 
 */
export class CteOsApi extends runtime.BaseAPI {

    /**
     * Baixar PDF do cancelamento
     */
    async baixarPdfCancelamentoCteOsRaw(requestParameters: BaixarPdfCancelamentoCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling baixarPdfCancelamentoCteOs.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/cteos/{id}/cancelamento/pdf`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Baixar PDF do cancelamento
     */
    async baixarPdfCancelamentoCteOs(requestParameters: BaixarPdfCancelamentoCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.baixarPdfCancelamentoCteOsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Baixar PDF da carta de correção
     */
    async baixarPdfCartaCorrecaoCteOsRaw(requestParameters: BaixarPdfCartaCorrecaoCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling baixarPdfCartaCorrecaoCteOs.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/cteos/{id}/carta-correcao/pdf`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Baixar PDF da carta de correção
     */
    async baixarPdfCartaCorrecaoCteOs(requestParameters: BaixarPdfCartaCorrecaoCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.baixarPdfCartaCorrecaoCteOsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Baixar PDF do DACTE
     */
    async baixarPdfCteOsRaw(requestParameters: BaixarPdfCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling baixarPdfCteOs.');
        }

        const queryParameters: any = {};

        if (requestParameters.logotipo !== undefined) {
            queryParameters['logotipo'] = requestParameters.logotipo;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/cteos/{id}/pdf`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Baixar PDF do DACTE
     */
    async baixarPdfCteOs(requestParameters: BaixarPdfCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.baixarPdfCteOsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Baixar PDF do evento
     */
    async baixarPdfEventoCteOsRaw(requestParameters: BaixarPdfEventoCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling baixarPdfEventoCteOs.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/cteos/eventos/{id}/pdf`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Baixar PDF do evento
     */
    async baixarPdfEventoCteOs(requestParameters: BaixarPdfEventoCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.baixarPdfEventoCteOsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * **Informações adicionais**:  - Consumo: Primeira requisição isenta, posteriores 1 unidade por requisição.
     * Baixar XML do cancelamento
     */
    async baixarXmlCancelamentoCteOsRaw(requestParameters: BaixarXmlCancelamentoCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling baixarXmlCancelamentoCteOs.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/cteos/{id}/cancelamento/xml`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * **Informações adicionais**:  - Consumo: Primeira requisição isenta, posteriores 1 unidade por requisição.
     * Baixar XML do cancelamento
     */
    async baixarXmlCancelamentoCteOs(requestParameters: BaixarXmlCancelamentoCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.baixarXmlCancelamentoCteOsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * **Informações adicionais**:  - Consumo: Primeira requisição isenta, posteriores 1 unidade por requisição.
     * Baixar XML da carta de correção
     */
    async baixarXmlCartaCorrecaoCteOsRaw(requestParameters: BaixarXmlCartaCorrecaoCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling baixarXmlCartaCorrecaoCteOs.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/cteos/{id}/carta-correcao/xml`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * **Informações adicionais**:  - Consumo: Primeira requisição isenta, posteriores 1 unidade por requisição.
     * Baixar XML da carta de correção
     */
    async baixarXmlCartaCorrecaoCteOs(requestParameters: BaixarXmlCartaCorrecaoCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.baixarXmlCartaCorrecaoCteOsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Utilize esse endpoint para obter o XML do conhecimento enviado para a SEFAZ, complementado com a informação do protocolo de autorização de uso (TAG raiz `cteProc`).    O XML só estará disponível nesse endpoint caso o conhecimento tenha sido autorizado pela SEFAZ. Para obter o XML nos demais casos, utilize o endpoint `GET /cteos/{id}/xml/conhecimento`.    **Informações adicionais**:  - Consumo: Primeira requisição isenta, posteriores 1 unidade por requisição.
     * Baixar XML do CT-e OS processado
     */
    async baixarXmlCteOsRaw(requestParameters: BaixarXmlCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling baixarXmlCteOs.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/cteos/{id}/xml`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Utilize esse endpoint para obter o XML do conhecimento enviado para a SEFAZ, complementado com a informação do protocolo de autorização de uso (TAG raiz `cteProc`).    O XML só estará disponível nesse endpoint caso o conhecimento tenha sido autorizado pela SEFAZ. Para obter o XML nos demais casos, utilize o endpoint `GET /cteos/{id}/xml/conhecimento`.    **Informações adicionais**:  - Consumo: Primeira requisição isenta, posteriores 1 unidade por requisição.
     * Baixar XML do CT-e OS processado
     */
    async baixarXmlCteOs(requestParameters: BaixarXmlCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.baixarXmlCteOsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Utilize esse endpoint para obter o XML do conhecimento enviado para a SEFAZ.    O XML estará disponível nesse endpoint mesmo em casos que o conhecimento tenha sido rejeitado.    **Informações adicionais**:  - Consumo: Primeira requisição isenta, posteriores 1 unidade por requisição.
     * Baixar XML do CT-e OS
     */
    async baixarXmlCteOsConhecimentoRaw(requestParameters: BaixarXmlCteOsConhecimentoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling baixarXmlCteOsConhecimento.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/cteos/{id}/xml/conhecimento`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Utilize esse endpoint para obter o XML do conhecimento enviado para a SEFAZ.    O XML estará disponível nesse endpoint mesmo em casos que o conhecimento tenha sido rejeitado.    **Informações adicionais**:  - Consumo: Primeira requisição isenta, posteriores 1 unidade por requisição.
     * Baixar XML do CT-e OS
     */
    async baixarXmlCteOsConhecimento(requestParameters: BaixarXmlCteOsConhecimentoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.baixarXmlCteOsConhecimentoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * **Informações adicionais**:  - Consumo: Primeira requisição isenta, posteriores 1 unidade por requisição.
     * Baixar XML do Protocolo da SEFAZ
     */
    async baixarXmlCteOsProtocoloRaw(requestParameters: BaixarXmlCteOsProtocoloRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling baixarXmlCteOsProtocolo.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/cteos/{id}/xml/protocolo`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * **Informações adicionais**:  - Consumo: Primeira requisição isenta, posteriores 1 unidade por requisição.
     * Baixar XML do Protocolo da SEFAZ
     */
    async baixarXmlCteOsProtocolo(requestParameters: BaixarXmlCteOsProtocoloRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.baixarXmlCteOsProtocoloRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * **Informações adicionais**:  - Consumo: Primeira requisição isenta, posteriores 1 unidade por requisição.
     * Baixar XML do evento
     */
    async baixarXmlEventoCteOsRaw(requestParameters: BaixarXmlEventoCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling baixarXmlEventoCteOs.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/cteos/eventos/{id}/xml`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * **Informações adicionais**:  - Consumo: Primeira requisição isenta, posteriores 1 unidade por requisição.
     * Baixar XML do evento
     */
    async baixarXmlEventoCteOs(requestParameters: BaixarXmlEventoCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.baixarXmlEventoCteOsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * **Informações adicionais**:  - Consumo: 1 unidade por requisição.
     * Cancelar um CT-e OS autorizado
     */
    async cancelarCteOsRaw(requestParameters: CancelarCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DfeCancelamento>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling cancelarCteOs.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/cteos/{id}/cancelamento`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CteOsPedidoCancelamentoToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DfeCancelamentoFromJSON(jsonValue));
    }

    /**
     * **Informações adicionais**:  - Consumo: 1 unidade por requisição.
     * Cancelar um CT-e OS autorizado
     */
    async cancelarCteOs(requestParameters: CancelarCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DfeCancelamento> {
        const response = await this.cancelarCteOsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Consultar o cancelamento do CT-e OS
     */
    async consultarCancelamentoCteOsRaw(requestParameters: ConsultarCancelamentoCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DfeCancelamento>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling consultarCancelamentoCteOs.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/cteos/{id}/cancelamento`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DfeCancelamentoFromJSON(jsonValue));
    }

    /**
     * Consultar o cancelamento do CT-e OS
     */
    async consultarCancelamentoCteOs(requestParameters: ConsultarCancelamentoCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DfeCancelamento> {
        const response = await this.consultarCancelamentoCteOsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Consultar a solicitação de correção do CT-e OS
     */
    async consultarCartaCorrecaoCteOsRaw(requestParameters: ConsultarCartaCorrecaoCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CteOsCartaCorrecao>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling consultarCartaCorrecaoCteOs.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/cteos/{id}/carta-correcao`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CteOsCartaCorrecaoFromJSON(jsonValue));
    }

    /**
     * Consultar a solicitação de correção do CT-e OS
     */
    async consultarCartaCorrecaoCteOs(requestParameters: ConsultarCartaCorrecaoCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CteOsCartaCorrecao> {
        const response = await this.consultarCartaCorrecaoCteOsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Consulta os detalhes de um CT-e OS já existente. Forneça o ID único obtido de uma requisição de emissão ou de listagem de CT-e OS e a API irá retornar as informações do CT-e OS correspondente.
     * Consultar CT-e OS
     */
    async consultarCteOsRaw(requestParameters: ConsultarCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Dfe>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling consultarCteOs.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/cteos/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DfeFromJSON(jsonValue));
    }

    /**
     * Consulta os detalhes de um CT-e OS já existente. Forneça o ID único obtido de uma requisição de emissão ou de listagem de CT-e OS e a API irá retornar as informações do CT-e OS correspondente.
     * Consultar CT-e OS
     */
    async consultarCteOs(requestParameters: ConsultarCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Dfe> {
        const response = await this.consultarCteOsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Consultar evento
     */
    async consultarEventoCteOsRaw(requestParameters: ConsultarEventoCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DfeEvento>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling consultarEventoCteOs.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/cteos/eventos/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DfeEventoFromJSON(jsonValue));
    }

    /**
     * Consultar evento
     */
    async consultarEventoCteOs(requestParameters: ConsultarEventoCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DfeEvento> {
        const response = await this.consultarEventoCteOsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Consulta do status do serviço prestado pelo Portal da Secretaria de Fazenda Estadual.    A API mantém a última consulta em cache por 5 minutos, evitando sobrecarregar desnecessariamente os servidores da SEFAZ (conforme orientação do MOC - versão 3.0.0a, item 4.6.3). Dessa forma, você poderá chamar esse endpoint quantas vezes quiser, sem preocupar-se em ter o seu CNPJ bloqueado por consumo indevido (Rejeição 656).
     * Consulta do Status do Serviço na SEFAZ Autorizadora
     */
    async consultarStatusSefazCteOsRaw(requestParameters: ConsultarStatusSefazCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DfeSefazStatus>> {
        if (requestParameters.cpfCnpj === null || requestParameters.cpfCnpj === undefined) {
            throw new runtime.RequiredError('cpfCnpj','Required parameter requestParameters.cpfCnpj was null or undefined when calling consultarStatusSefazCteOs.');
        }

        const queryParameters: any = {};

        if (requestParameters.cpfCnpj !== undefined) {
            queryParameters['cpf_cnpj'] = requestParameters.cpfCnpj;
        }

        if (requestParameters.autorizador !== undefined) {
            queryParameters['autorizador'] = requestParameters.autorizador;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/cteos/sefaz/status`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DfeSefazStatusFromJSON(jsonValue));
    }

    /**
     * Consulta do status do serviço prestado pelo Portal da Secretaria de Fazenda Estadual.    A API mantém a última consulta em cache por 5 minutos, evitando sobrecarregar desnecessariamente os servidores da SEFAZ (conforme orientação do MOC - versão 3.0.0a, item 4.6.3). Dessa forma, você poderá chamar esse endpoint quantas vezes quiser, sem preocupar-se em ter o seu CNPJ bloqueado por consumo indevido (Rejeição 656).
     * Consulta do Status do Serviço na SEFAZ Autorizadora
     */
    async consultarStatusSefazCteOs(requestParameters: ConsultarStatusSefazCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DfeSefazStatus> {
        const response = await this.consultarStatusSefazCteOsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * É possível enviar até 20 correções diferentes, sendo que será válido sempre a última correção enviada.    **Informações adicionais**:  - Consumo: 1 unidade por requisição.
     * Solicitar correção do CT-e OS
     */
    async criarCartaCorrecaoCteOsRaw(requestParameters: CriarCartaCorrecaoCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CteOsCartaCorrecao>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling criarCartaCorrecaoCteOs.');
        }

        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling criarCartaCorrecaoCteOs.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/cteos/{id}/carta-correcao`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CteOsPedidoCartaCorrecaoToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CteOsCartaCorrecaoFromJSON(jsonValue));
    }

    /**
     * É possível enviar até 20 correções diferentes, sendo que será válido sempre a última correção enviada.    **Informações adicionais**:  - Consumo: 1 unidade por requisição.
     * Solicitar correção do CT-e OS
     */
    async criarCartaCorrecaoCteOs(requestParameters: CriarCartaCorrecaoCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CteOsCartaCorrecao> {
        const response = await this.criarCartaCorrecaoCteOsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * **Informações adicionais**:  - Consumo: 1 unidade por requisição.
     * Emitir CT-e OS
     */
    async emitirCteOsRaw(requestParameters: EmitirCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Dfe>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling emitirCteOs.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/cteos`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CteOsPedidoEmissaoToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DfeFromJSON(jsonValue));
    }

    /**
     * **Informações adicionais**:  - Consumo: 1 unidade por requisição.
     * Emitir CT-e OS
     */
    async emitirCteOs(requestParameters: EmitirCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Dfe> {
        const response = await this.emitirCteOsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retorna a lista de CT-e OS de acordo com os critérios de busca utilizados. Os CT-e OS são retornados ordenados pela data da criação, com os mais recentes aparecendo primeiro.
     * Listar CT-e OS
     */
    async listarCteOsRaw(requestParameters: ListarCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DfeListagem>> {
        if (requestParameters.cpfCnpj === null || requestParameters.cpfCnpj === undefined) {
            throw new runtime.RequiredError('cpfCnpj','Required parameter requestParameters.cpfCnpj was null or undefined when calling listarCteOs.');
        }

        if (requestParameters.ambiente === null || requestParameters.ambiente === undefined) {
            throw new runtime.RequiredError('ambiente','Required parameter requestParameters.ambiente was null or undefined when calling listarCteOs.');
        }

        const queryParameters: any = {};

        if (requestParameters.$top !== undefined) {
            queryParameters['$top'] = requestParameters.$top;
        }

        if (requestParameters.$skip !== undefined) {
            queryParameters['$skip'] = requestParameters.$skip;
        }

        if (requestParameters.$inlinecount !== undefined) {
            queryParameters['$inlinecount'] = requestParameters.$inlinecount;
        }

        if (requestParameters.cpfCnpj !== undefined) {
            queryParameters['cpf_cnpj'] = requestParameters.cpfCnpj;
        }

        if (requestParameters.referencia !== undefined) {
            queryParameters['referencia'] = requestParameters.referencia;
        }

        if (requestParameters.ambiente !== undefined) {
            queryParameters['ambiente'] = requestParameters.ambiente;
        }

        if (requestParameters.chave !== undefined) {
            queryParameters['chave'] = requestParameters.chave;
        }

        if (requestParameters.serie !== undefined) {
            queryParameters['serie'] = requestParameters.serie;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/cteos`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DfeListagemFromJSON(jsonValue));
    }

    /**
     * Retorna a lista de CT-e OS de acordo com os critérios de busca utilizados. Os CT-e OS são retornados ordenados pela data da criação, com os mais recentes aparecendo primeiro.
     * Listar CT-e OS
     */
    async listarCteOs(requestParameters: ListarCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DfeListagem> {
        const response = await this.listarCteOsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Realiza a sincronização dos dados a partir da consulta da situação atual do CT-e OS na Base de Dados do Portal da Secretaria de Fazenda Estadual.    **Cenários de uso**:  * Sincronizar um CT-e OS que se encontra com o status `erro` na API, mas está autorizado na SEFAZ (útil em casos de erros de transmissão com a SEFAZ, como instabilidades e timeouts).  * Sincronizar um CT-e OS que se encontra com o status `autorizado`na API, mas está cancelado na SEFAZ.  * Sincronizar todos os eventos de Cancelamento e Carta de Correção de um CT-e OS que porventura não tenham sido feitos a partir da API.    **Informações adicionais**:  - Consumo: 1 unidade por evento sincronizado ou requisição.
     * Sincroniza dados no CT-e OS a partir da SEFAZ
     */
    async sincronizarCteOsRaw(requestParameters: SincronizarCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DfeSincronizacao>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling sincronizarCteOs.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/cteos/{id}/sincronizar`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DfeSincronizacaoFromJSON(jsonValue));
    }

    /**
     * Realiza a sincronização dos dados a partir da consulta da situação atual do CT-e OS na Base de Dados do Portal da Secretaria de Fazenda Estadual.    **Cenários de uso**:  * Sincronizar um CT-e OS que se encontra com o status `erro` na API, mas está autorizado na SEFAZ (útil em casos de erros de transmissão com a SEFAZ, como instabilidades e timeouts).  * Sincronizar um CT-e OS que se encontra com o status `autorizado`na API, mas está cancelado na SEFAZ.  * Sincronizar todos os eventos de Cancelamento e Carta de Correção de um CT-e OS que porventura não tenham sido feitos a partir da API.    **Informações adicionais**:  - Consumo: 1 unidade por evento sincronizado ou requisição.
     * Sincroniza dados no CT-e OS a partir da SEFAZ
     */
    async sincronizarCteOs(requestParameters: SincronizarCteOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DfeSincronizacao> {
        const response = await this.sincronizarCteOsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
