/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Dfe,
  DfeCancelamento,
  DfeListagem,
  DfeSefazStatus,
  NfcomPedidoCancelamento,
  NfcomPedidoEmissao,
} from '../models';
import {
    DfeFromJSON,
    DfeToJSON,
    DfeCancelamentoFromJSON,
    DfeCancelamentoToJSON,
    DfeListagemFromJSON,
    DfeListagemToJSON,
    DfeSefazStatusFromJSON,
    DfeSefazStatusToJSON,
    NfcomPedidoCancelamentoFromJSON,
    NfcomPedidoCancelamentoToJSON,
    NfcomPedidoEmissaoFromJSON,
    NfcomPedidoEmissaoToJSON,
} from '../models';

export interface BaixarPdfNfcomRequest {
    id: string;
    logotipo?: boolean;
}

export interface BaixarXmlCancelamentoNfcomRequest {
    id: string;
}

export interface BaixarXmlNfcomRequest {
    id: string;
}

export interface BaixarXmlNfcomNotaRequest {
    id: string;
}

export interface BaixarXmlNfcomProtocoloRequest {
    id: string;
}

export interface CancelarNfcomRequest {
    id: string;
    body?: NfcomPedidoCancelamento;
}

export interface ConsultarCancelamentoNfcomRequest {
    id: string;
}

export interface ConsultarNfcomRequest {
    id: string;
}

export interface ConsultarStatusSefazNfcomRequest {
    cpfCnpj: string;
    autorizador?: string;
}

export interface EmitirNfcomRequest {
    body: NfcomPedidoEmissao;
}

export interface ListarNfcomRequest {
    cpfCnpj: string;
    ambiente: string;
    $top?: number;
    $skip?: number;
    $inlinecount?: boolean;
    referencia?: string;
    chave?: string;
    serie?: string;
}

/**
 * 
 */
export class NfcomApi extends runtime.BaseAPI {

    /**
     * Baixar PDF do DANFE-COM
     */
    async baixarPdfNfcomRaw(requestParameters: BaixarPdfNfcomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling baixarPdfNfcom.');
        }

        const queryParameters: any = {};

        if (requestParameters.logotipo !== undefined) {
            queryParameters['logotipo'] = requestParameters.logotipo;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/nfcom/{id}/pdf`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Baixar PDF do DANFE-COM
     */
    async baixarPdfNfcom(requestParameters: BaixarPdfNfcomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.baixarPdfNfcomRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * **Informações adicionais**:  - Consumo: Primeira requisição isenta, posteriores 1 unidade por requisição.
     * Baixar XML do cancelamento
     */
    async baixarXmlCancelamentoNfcomRaw(requestParameters: BaixarXmlCancelamentoNfcomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling baixarXmlCancelamentoNfcom.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/nfcom/{id}/cancelamento/xml`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * **Informações adicionais**:  - Consumo: Primeira requisição isenta, posteriores 1 unidade por requisição.
     * Baixar XML do cancelamento
     */
    async baixarXmlCancelamentoNfcom(requestParameters: BaixarXmlCancelamentoNfcomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.baixarXmlCancelamentoNfcomRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Utilize esse endpoint para obter o XML da nota enviada para a SEFAZ, complementado com a informação do protocolo de autorização de uso (TAG raiz `nfcomProc`).    O XML só estará disponível nesse endpoint caso a nota tenha sido autorizada pela SEFAZ. Para obter o XML nos demais casos, utilize o endpoint `GET /nfcom/{id}/xml/nota`.    **Informações adicionais**:  - Consumo: Primeira requisição isenta, posteriores 1 unidade por requisição.
     * Baixar XML da NFCom processada
     */
    async baixarXmlNfcomRaw(requestParameters: BaixarXmlNfcomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling baixarXmlNfcom.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/nfcom/{id}/xml`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Utilize esse endpoint para obter o XML da nota enviada para a SEFAZ, complementado com a informação do protocolo de autorização de uso (TAG raiz `nfcomProc`).    O XML só estará disponível nesse endpoint caso a nota tenha sido autorizada pela SEFAZ. Para obter o XML nos demais casos, utilize o endpoint `GET /nfcom/{id}/xml/nota`.    **Informações adicionais**:  - Consumo: Primeira requisição isenta, posteriores 1 unidade por requisição.
     * Baixar XML da NFCom processada
     */
    async baixarXmlNfcom(requestParameters: BaixarXmlNfcomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.baixarXmlNfcomRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Utilize esse endpoint para obter o XML da nota enviada para a SEFAZ.    O XML estará disponível nesse endpoint mesmo em casos que a nota tenha sido rejeitada.    **Informações adicionais**:  - Consumo: Primeira requisição isenta, posteriores 1 unidade por requisição.
     * Baixar XML da NFCom
     */
    async baixarXmlNfcomNotaRaw(requestParameters: BaixarXmlNfcomNotaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling baixarXmlNfcomNota.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/nfcom/{id}/xml/nota`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Utilize esse endpoint para obter o XML da nota enviada para a SEFAZ.    O XML estará disponível nesse endpoint mesmo em casos que a nota tenha sido rejeitada.    **Informações adicionais**:  - Consumo: Primeira requisição isenta, posteriores 1 unidade por requisição.
     * Baixar XML da NFCom
     */
    async baixarXmlNfcomNota(requestParameters: BaixarXmlNfcomNotaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.baixarXmlNfcomNotaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * **Informações adicionais**:  - Consumo: Primeira requisição isenta, posteriores 1 unidade por requisição.
     * Baixar XML do Protocolo da SEFAZ
     */
    async baixarXmlNfcomProtocoloRaw(requestParameters: BaixarXmlNfcomProtocoloRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling baixarXmlNfcomProtocolo.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/nfcom/{id}/xml/protocolo`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * **Informações adicionais**:  - Consumo: Primeira requisição isenta, posteriores 1 unidade por requisição.
     * Baixar XML do Protocolo da SEFAZ
     */
    async baixarXmlNfcomProtocolo(requestParameters: BaixarXmlNfcomProtocoloRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.baixarXmlNfcomProtocoloRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * **Informações adicionais**:  - Consumo: 1 unidade por requisição.
     * Cancelar uma NFCom autorizada
     */
    async cancelarNfcomRaw(requestParameters: CancelarNfcomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DfeCancelamento>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling cancelarNfcom.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/nfcom/{id}/cancelamento`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NfcomPedidoCancelamentoToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DfeCancelamentoFromJSON(jsonValue));
    }

    /**
     * **Informações adicionais**:  - Consumo: 1 unidade por requisição.
     * Cancelar uma NFCom autorizada
     */
    async cancelarNfcom(requestParameters: CancelarNfcomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DfeCancelamento> {
        const response = await this.cancelarNfcomRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Consultar o cancelamento da NFCom
     */
    async consultarCancelamentoNfcomRaw(requestParameters: ConsultarCancelamentoNfcomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DfeCancelamento>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling consultarCancelamentoNfcom.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/nfcom/{id}/cancelamento`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DfeCancelamentoFromJSON(jsonValue));
    }

    /**
     * Consultar o cancelamento da NFCom
     */
    async consultarCancelamentoNfcom(requestParameters: ConsultarCancelamentoNfcomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DfeCancelamento> {
        const response = await this.consultarCancelamentoNfcomRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Consulta os detalhes de uma NFCom já existente. Forneça o ID único obtido de uma requisição de emissão ou de listagem de NFCom e a API irá retornar as informações da NFCom correspondente.
     * Consultar NFCom
     */
    async consultarNfcomRaw(requestParameters: ConsultarNfcomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Dfe>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling consultarNfcom.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/nfcom/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DfeFromJSON(jsonValue));
    }

    /**
     * Consulta os detalhes de uma NFCom já existente. Forneça o ID único obtido de uma requisição de emissão ou de listagem de NFCom e a API irá retornar as informações da NFCom correspondente.
     * Consultar NFCom
     */
    async consultarNfcom(requestParameters: ConsultarNfcomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Dfe> {
        const response = await this.consultarNfcomRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Consulta do status do serviço prestado pelo Portal da Secretaria de Fazenda Estadual.    A API mantém a última consulta em cache por 5 minutos, evitando sobrecarregar desnecessariamente os servidores da SEFAZ.
     * Consulta do Status do Serviço na SEFAZ Autorizadora
     */
    async consultarStatusSefazNfcomRaw(requestParameters: ConsultarStatusSefazNfcomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DfeSefazStatus>> {
        if (requestParameters.cpfCnpj === null || requestParameters.cpfCnpj === undefined) {
            throw new runtime.RequiredError('cpfCnpj','Required parameter requestParameters.cpfCnpj was null or undefined when calling consultarStatusSefazNfcom.');
        }

        const queryParameters: any = {};

        if (requestParameters.cpfCnpj !== undefined) {
            queryParameters['cpf_cnpj'] = requestParameters.cpfCnpj;
        }

        if (requestParameters.autorizador !== undefined) {
            queryParameters['autorizador'] = requestParameters.autorizador;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/nfcom/sefaz/status`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DfeSefazStatusFromJSON(jsonValue));
    }

    /**
     * Consulta do status do serviço prestado pelo Portal da Secretaria de Fazenda Estadual.    A API mantém a última consulta em cache por 5 minutos, evitando sobrecarregar desnecessariamente os servidores da SEFAZ.
     * Consulta do Status do Serviço na SEFAZ Autorizadora
     */
    async consultarStatusSefazNfcom(requestParameters: ConsultarStatusSefazNfcomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DfeSefazStatus> {
        const response = await this.consultarStatusSefazNfcomRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * **Informações adicionais**:  - Consumo: 1 unidade por requisição.
     * Emitir NFCom
     */
    async emitirNfcomRaw(requestParameters: EmitirNfcomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Dfe>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling emitirNfcom.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/nfcom`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NfcomPedidoEmissaoToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DfeFromJSON(jsonValue));
    }

    /**
     * **Informações adicionais**:  - Consumo: 1 unidade por requisição.
     * Emitir NFCom
     */
    async emitirNfcom(requestParameters: EmitirNfcomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Dfe> {
        const response = await this.emitirNfcomRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retorna a lista de NFCom de acordo com os critérios de busca utilizados. As NFCom são retornadas ordenadas pela data da criação, com as mais recentes aparecendo primeiro.
     * Listar NFCom
     */
    async listarNfcomRaw(requestParameters: ListarNfcomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DfeListagem>> {
        if (requestParameters.cpfCnpj === null || requestParameters.cpfCnpj === undefined) {
            throw new runtime.RequiredError('cpfCnpj','Required parameter requestParameters.cpfCnpj was null or undefined when calling listarNfcom.');
        }

        if (requestParameters.ambiente === null || requestParameters.ambiente === undefined) {
            throw new runtime.RequiredError('ambiente','Required parameter requestParameters.ambiente was null or undefined when calling listarNfcom.');
        }

        const queryParameters: any = {};

        if (requestParameters.$top !== undefined) {
            queryParameters['$top'] = requestParameters.$top;
        }

        if (requestParameters.$skip !== undefined) {
            queryParameters['$skip'] = requestParameters.$skip;
        }

        if (requestParameters.$inlinecount !== undefined) {
            queryParameters['$inlinecount'] = requestParameters.$inlinecount;
        }

        if (requestParameters.cpfCnpj !== undefined) {
            queryParameters['cpf_cnpj'] = requestParameters.cpfCnpj;
        }

        if (requestParameters.referencia !== undefined) {
            queryParameters['referencia'] = requestParameters.referencia;
        }

        if (requestParameters.ambiente !== undefined) {
            queryParameters['ambiente'] = requestParameters.ambiente;
        }

        if (requestParameters.chave !== undefined) {
            queryParameters['chave'] = requestParameters.chave;
        }

        if (requestParameters.serie !== undefined) {
            queryParameters['serie'] = requestParameters.serie;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/nfcom`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DfeListagemFromJSON(jsonValue));
    }

    /**
     * Retorna a lista de NFCom de acordo com os critérios de busca utilizados. As NFCom são retornadas ordenadas pela data da criação, com as mais recentes aparecendo primeiro.
     * Listar NFCom
     */
    async listarNfcom(requestParameters: ListarNfcomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DfeListagem> {
        const response = await this.listarNfcomRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
