/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CnpjQualificacaoSocio } from './CnpjQualificacaoSocio';
import {
    CnpjQualificacaoSocioFromJSON,
    CnpjQualificacaoSocioFromJSONTyped,
    CnpjQualificacaoSocioToJSON,
} from './CnpjQualificacaoSocio';

/**
 * Representante legal.
 * @export
 * @interface CnpjRepresentanteLegal
 */
export interface CnpjRepresentanteLegal {
    /**
     * Número do cpf do representante legal.
     * @type {string}
     * @memberof CnpjRepresentanteLegal
     */
    cpf?: string;
    /**
     * Nome do representante legal.
     * @type {string}
     * @memberof CnpjRepresentanteLegal
     */
    nome?: string;
    /**
     * 
     * @type {CnpjQualificacaoSocio}
     * @memberof CnpjRepresentanteLegal
     */
    qualificacao?: CnpjQualificacaoSocio;
}

/**
 * Check if a given object implements the CnpjRepresentanteLegal interface.
 */
export function instanceOfCnpjRepresentanteLegal(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CnpjRepresentanteLegalFromJSON(json: any): CnpjRepresentanteLegal {
    return CnpjRepresentanteLegalFromJSONTyped(json, false);
}

export function CnpjRepresentanteLegalFromJSONTyped(json: any, ignoreDiscriminator: boolean): CnpjRepresentanteLegal {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cpf': !exists(json, 'cpf') ? undefined : json['cpf'],
        'nome': !exists(json, 'nome') ? undefined : json['nome'],
        'qualificacao': !exists(json, 'qualificacao') ? undefined : CnpjQualificacaoSocioFromJSON(json['qualificacao']),
    };
}

export function CnpjRepresentanteLegalToJSON(value?: CnpjRepresentanteLegal | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cpf': value.cpf,
        'nome': value.nome,
        'qualificacao': CnpjQualificacaoSocioToJSON(value.qualificacao),
    };
}

