/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CteOsSefazICMS00OS } from './CteOsSefazICMS00OS';
import {
    CteOsSefazICMS00OSFromJSON,
    CteOsSefazICMS00OSFromJSONTyped,
    CteOsSefazICMS00OSToJSON,
} from './CteOsSefazICMS00OS';
import type { CteOsSefazICMS20OS } from './CteOsSefazICMS20OS';
import {
    CteOsSefazICMS20OSFromJSON,
    CteOsSefazICMS20OSFromJSONTyped,
    CteOsSefazICMS20OSToJSON,
} from './CteOsSefazICMS20OS';
import type { CteOsSefazICMS45OS } from './CteOsSefazICMS45OS';
import {
    CteOsSefazICMS45OSFromJSON,
    CteOsSefazICMS45OSFromJSONTyped,
    CteOsSefazICMS45OSToJSON,
} from './CteOsSefazICMS45OS';
import type { CteOsSefazICMS90OS } from './CteOsSefazICMS90OS';
import {
    CteOsSefazICMS90OSFromJSON,
    CteOsSefazICMS90OSFromJSONTyped,
    CteOsSefazICMS90OSToJSON,
} from './CteOsSefazICMS90OS';
import type { CteOsSefazICMSOutraUFOS } from './CteOsSefazICMSOutraUFOS';
import {
    CteOsSefazICMSOutraUFOSFromJSON,
    CteOsSefazICMSOutraUFOSFromJSONTyped,
    CteOsSefazICMSOutraUFOSToJSON,
} from './CteOsSefazICMSOutraUFOS';
import type { CteOsSefazICMSSNOS } from './CteOsSefazICMSSNOS';
import {
    CteOsSefazICMSSNOSFromJSON,
    CteOsSefazICMSSNOSFromJSONTyped,
    CteOsSefazICMSSNOSToJSON,
} from './CteOsSefazICMSSNOS';

/**
 * Informações relativas ao ICMS.
 * @export
 * @interface CteOsSefazImpOS
 */
export interface CteOsSefazImpOS {
    /**
     * 
     * @type {CteOsSefazICMS00OS}
     * @memberof CteOsSefazImpOS
     */
    ICMS00?: CteOsSefazICMS00OS;
    /**
     * 
     * @type {CteOsSefazICMS20OS}
     * @memberof CteOsSefazImpOS
     */
    ICMS20?: CteOsSefazICMS20OS;
    /**
     * 
     * @type {CteOsSefazICMS45OS}
     * @memberof CteOsSefazImpOS
     */
    ICMS45?: CteOsSefazICMS45OS;
    /**
     * 
     * @type {CteOsSefazICMS90OS}
     * @memberof CteOsSefazImpOS
     */
    ICMS90?: CteOsSefazICMS90OS;
    /**
     * 
     * @type {CteOsSefazICMSOutraUFOS}
     * @memberof CteOsSefazImpOS
     */
    ICMSOutraUF?: CteOsSefazICMSOutraUFOS;
    /**
     * 
     * @type {CteOsSefazICMSSNOS}
     * @memberof CteOsSefazImpOS
     */
    ICMSSN?: CteOsSefazICMSSNOS;
}

/**
 * Check if a given object implements the CteOsSefazImpOS interface.
 */
export function instanceOfCteOsSefazImpOS(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CteOsSefazImpOSFromJSON(json: any): CteOsSefazImpOS {
    return CteOsSefazImpOSFromJSONTyped(json, false);
}

export function CteOsSefazImpOSFromJSONTyped(json: any, ignoreDiscriminator: boolean): CteOsSefazImpOS {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ICMS00': !exists(json, 'ICMS00') ? undefined : CteOsSefazICMS00OSFromJSON(json['ICMS00']),
        'ICMS20': !exists(json, 'ICMS20') ? undefined : CteOsSefazICMS20OSFromJSON(json['ICMS20']),
        'ICMS45': !exists(json, 'ICMS45') ? undefined : CteOsSefazICMS45OSFromJSON(json['ICMS45']),
        'ICMS90': !exists(json, 'ICMS90') ? undefined : CteOsSefazICMS90OSFromJSON(json['ICMS90']),
        'ICMSOutraUF': !exists(json, 'ICMSOutraUF') ? undefined : CteOsSefazICMSOutraUFOSFromJSON(json['ICMSOutraUF']),
        'ICMSSN': !exists(json, 'ICMSSN') ? undefined : CteOsSefazICMSSNOSFromJSON(json['ICMSSN']),
    };
}

export function CteOsSefazImpOSToJSON(value?: CteOsSefazImpOS | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ICMS00': CteOsSefazICMS00OSToJSON(value.ICMS00),
        'ICMS20': CteOsSefazICMS20OSToJSON(value.ICMS20),
        'ICMS45': CteOsSefazICMS45OSToJSON(value.ICMS45),
        'ICMS90': CteOsSefazICMS90OSToJSON(value.ICMS90),
        'ICMSOutraUF': CteOsSefazICMSOutraUFOSToJSON(value.ICMSOutraUF),
        'ICMSSN': CteOsSefazICMSSNOSToJSON(value.ICMSSN),
    };
}

