/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CteOsSefazDevTribOS } from './CteOsSefazDevTribOS';
import {
    CteOsSefazDevTribOSFromJSON,
    CteOsSefazDevTribOSFromJSONTyped,
    CteOsSefazDevTribOSToJSON,
} from './CteOsSefazDevTribOS';
import type { CteOsSefazDifOS } from './CteOsSefazDifOS';
import {
    CteOsSefazDifOSFromJSON,
    CteOsSefazDifOSFromJSONTyped,
    CteOsSefazDifOSToJSON,
} from './CteOsSefazDifOS';
import type { CteOsSefazRedOS } from './CteOsSefazRedOS';
import {
    CteOsSefazRedOSFromJSON,
    CteOsSefazRedOSFromJSONTyped,
    CteOsSefazRedOSToJSON,
} from './CteOsSefazRedOS';

/**
 * Grupo de informações do IBS na UF.
 * @export
 * @interface CteOsSefazGIBSUFOS
 */
export interface CteOsSefazGIBSUFOS {
    /**
     * Aliquota do IBS de competência das UF (em percentual).
     * @type {number}
     * @memberof CteOsSefazGIBSUFOS
     */
    pIBSUF: number | null;
    /**
     * 
     * @type {CteOsSefazDifOS}
     * @memberof CteOsSefazGIBSUFOS
     */
    gDif?: CteOsSefazDifOS;
    /**
     * 
     * @type {CteOsSefazDevTribOS}
     * @memberof CteOsSefazGIBSUFOS
     */
    gDevTrib?: CteOsSefazDevTribOS;
    /**
     * 
     * @type {CteOsSefazRedOS}
     * @memberof CteOsSefazGIBSUFOS
     */
    gRed?: CteOsSefazRedOS;
    /**
     * Valor do IBS de competência das UF.
     * @type {number}
     * @memberof CteOsSefazGIBSUFOS
     */
    vIBSUF: number | null;
}

/**
 * Check if a given object implements the CteOsSefazGIBSUFOS interface.
 */
export function instanceOfCteOsSefazGIBSUFOS(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "pIBSUF" in value;
    isInstance = isInstance && "vIBSUF" in value;

    return isInstance;
}

export function CteOsSefazGIBSUFOSFromJSON(json: any): CteOsSefazGIBSUFOS {
    return CteOsSefazGIBSUFOSFromJSONTyped(json, false);
}

export function CteOsSefazGIBSUFOSFromJSONTyped(json: any, ignoreDiscriminator: boolean): CteOsSefazGIBSUFOS {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pIBSUF': json['pIBSUF'],
        'gDif': !exists(json, 'gDif') ? undefined : CteOsSefazDifOSFromJSON(json['gDif']),
        'gDevTrib': !exists(json, 'gDevTrib') ? undefined : CteOsSefazDevTribOSFromJSON(json['gDevTrib']),
        'gRed': !exists(json, 'gRed') ? undefined : CteOsSefazRedOSFromJSON(json['gRed']),
        'vIBSUF': json['vIBSUF'],
    };
}

export function CteOsSefazGIBSUFOSToJSON(value?: CteOsSefazGIBSUFOS | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pIBSUF': value.pIBSUF,
        'gDif': CteOsSefazDifOSToJSON(value.gDif),
        'gDevTrib': CteOsSefazDevTribOSToJSON(value.gDevTrib),
        'gRed': CteOsSefazRedOSToJSON(value.gRed),
        'vIBSUF': value.vIBSUF,
    };
}

