/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CteOsSefazEnderecoOS } from './CteOsSefazEnderecoOS';
import {
    CteOsSefazEnderecoOSFromJSON,
    CteOsSefazEnderecoOSFromJSONTyped,
    CteOsSefazEnderecoOSToJSON,
} from './CteOsSefazEnderecoOS';

/**
 * Informações do Tomador/Usuário do Serviço.
 * Opcional para Excesso de Bagagem.
 * @export
 * @interface CteOsSefazTomaOS
 */
export interface CteOsSefazTomaOS {
    /**
     * Número do CNPJ.
     * Em caso de empresa não estabelecida no Brasil, será informado o CNPJ com zeros.
     * Informar os zeros não significativos.
     * @type {string}
     * @memberof CteOsSefazTomaOS
     */
    CNPJ?: string | null;
    /**
     * Número do CPF.
     * Informar os zeros não significativos.
     * @type {string}
     * @memberof CteOsSefazTomaOS
     */
    CPF?: string | null;
    /**
     * Inscrição Estadual.
     * Informar a IE do tomador ou ISENTO se tomador é contribuinte do ICMS isento de inscrição no cadastro de contribuintes do ICMS. Caso o tomador não seja contribuinte do ICMS não informar o conteúdo.
     * @type {string}
     * @memberof CteOsSefazTomaOS
     */
    IE?: string | null;
    /**
     * Razão social ou nome do tomador.
     * @type {string}
     * @memberof CteOsSefazTomaOS
     */
    xNome: string | null;
    /**
     * Nome fantasia.
     * @type {string}
     * @memberof CteOsSefazTomaOS
     */
    xFant?: string | null;
    /**
     * Telefone.
     * @type {string}
     * @memberof CteOsSefazTomaOS
     */
    fone?: string | null;
    /**
     * 
     * @type {CteOsSefazEnderecoOS}
     * @memberof CteOsSefazTomaOS
     */
    enderToma: CteOsSefazEnderecoOS;
    /**
     * Endereço de email.
     * @type {string}
     * @memberof CteOsSefazTomaOS
     */
    email?: string | null;
}

/**
 * Check if a given object implements the CteOsSefazTomaOS interface.
 */
export function instanceOfCteOsSefazTomaOS(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "xNome" in value;
    isInstance = isInstance && "enderToma" in value;

    return isInstance;
}

export function CteOsSefazTomaOSFromJSON(json: any): CteOsSefazTomaOS {
    return CteOsSefazTomaOSFromJSONTyped(json, false);
}

export function CteOsSefazTomaOSFromJSONTyped(json: any, ignoreDiscriminator: boolean): CteOsSefazTomaOS {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'CNPJ': !exists(json, 'CNPJ') ? undefined : json['CNPJ'],
        'CPF': !exists(json, 'CPF') ? undefined : json['CPF'],
        'IE': !exists(json, 'IE') ? undefined : json['IE'],
        'xNome': json['xNome'],
        'xFant': !exists(json, 'xFant') ? undefined : json['xFant'],
        'fone': !exists(json, 'fone') ? undefined : json['fone'],
        'enderToma': CteOsSefazEnderecoOSFromJSON(json['enderToma']),
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function CteOsSefazTomaOSToJSON(value?: CteOsSefazTomaOS | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'CNPJ': value.CNPJ,
        'CPF': value.CPF,
        'IE': value.IE,
        'xNome': value.xNome,
        'xFant': value.xFant,
        'fone': value.fone,
        'enderToma': CteOsSefazEnderecoOSToJSON(value.enderToma),
        'email': value.email,
    };
}

