/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Informações de quantidades da Carga do CT-e.
 * Para Transporte de Pessoas indicar número de passageiros, para excesso de bagagem e transporte de valores indicar número de Volumes/Malotes.
 * @export
 * @interface CteOsSefazInfQOS
 */
export interface CteOsSefazInfQOS {
    /**
     * Quantidade.
     * @type {number}
     * @memberof CteOsSefazInfQOS
     */
    qCarga: number | null;
}

/**
 * Check if a given object implements the CteOsSefazInfQOS interface.
 */
export function instanceOfCteOsSefazInfQOS(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "qCarga" in value;

    return isInstance;
}

export function CteOsSefazInfQOSFromJSON(json: any): CteOsSefazInfQOS {
    return CteOsSefazInfQOSFromJSONTyped(json, false);
}

export function CteOsSefazInfQOSFromJSONTyped(json: any, ignoreDiscriminator: boolean): CteOsSefazInfQOS {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'qCarga': json['qCarga'],
    };
}

export function CteOsSefazInfQOSToJSON(value?: CteOsSefazInfQOS | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'qCarga': value.qCarga,
    };
}

