/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CteOsSefazCobrOS } from './CteOsSefazCobrOS';
import {
    CteOsSefazCobrOSFromJSON,
    CteOsSefazCobrOSFromJSONTyped,
    CteOsSefazCobrOSToJSON,
} from './CteOsSefazCobrOS';
import type { CteOsSefazInfCteSubOS } from './CteOsSefazInfCteSubOS';
import {
    CteOsSefazInfCteSubOSFromJSON,
    CteOsSefazInfCteSubOSFromJSONTyped,
    CteOsSefazInfCteSubOSToJSON,
} from './CteOsSefazInfCteSubOS';
import type { CteOsSefazInfDocRefOS } from './CteOsSefazInfDocRefOS';
import {
    CteOsSefazInfDocRefOSFromJSON,
    CteOsSefazInfDocRefOSFromJSONTyped,
    CteOsSefazInfDocRefOSToJSON,
} from './CteOsSefazInfDocRefOS';
import type { CteOsSefazInfGTVeOS } from './CteOsSefazInfGTVeOS';
import {
    CteOsSefazInfGTVeOSFromJSON,
    CteOsSefazInfGTVeOSFromJSONTyped,
    CteOsSefazInfGTVeOSToJSON,
} from './CteOsSefazInfGTVeOS';
import type { CteOsSefazInfModalOS } from './CteOsSefazInfModalOS';
import {
    CteOsSefazInfModalOSFromJSON,
    CteOsSefazInfModalOSFromJSONTyped,
    CteOsSefazInfModalOSToJSON,
} from './CteOsSefazInfModalOS';
import type { CteOsSefazInfServicoOS } from './CteOsSefazInfServicoOS';
import {
    CteOsSefazInfServicoOSFromJSON,
    CteOsSefazInfServicoOSFromJSONTyped,
    CteOsSefazInfServicoOSToJSON,
} from './CteOsSefazInfServicoOS';
import type { CteOsSefazSegOS } from './CteOsSefazSegOS';
import {
    CteOsSefazSegOSFromJSON,
    CteOsSefazSegOSFromJSONTyped,
    CteOsSefazSegOSToJSON,
} from './CteOsSefazSegOS';

/**
 * Grupo de informações do CT-e OS Normal.
 * @export
 * @interface CteOsSefazInfCTeNormOS
 */
export interface CteOsSefazInfCTeNormOS {
    /**
     * 
     * @type {CteOsSefazInfServicoOS}
     * @memberof CteOsSefazInfCTeNormOS
     */
    infServico: CteOsSefazInfServicoOS;
    /**
     * 
     * @type {Array<CteOsSefazInfDocRefOS>}
     * @memberof CteOsSefazInfCTeNormOS
     */
    infDocRef?: Array<CteOsSefazInfDocRefOS>;
    /**
     * 
     * @type {Array<CteOsSefazSegOS>}
     * @memberof CteOsSefazInfCTeNormOS
     */
    seg?: Array<CteOsSefazSegOS>;
    /**
     * 
     * @type {CteOsSefazInfModalOS}
     * @memberof CteOsSefazInfCTeNormOS
     */
    infModal?: CteOsSefazInfModalOS;
    /**
     * 
     * @type {CteOsSefazInfCteSubOS}
     * @memberof CteOsSefazInfCTeNormOS
     */
    infCteSub?: CteOsSefazInfCteSubOS;
    /**
     * Chave de acesso do CT-e Cancelado
     * Somente para Transporte de Valores.
     * @type {string}
     * @memberof CteOsSefazInfCTeNormOS
     */
    refCTeCanc?: string | null;
    /**
     * 
     * @type {CteOsSefazCobrOS}
     * @memberof CteOsSefazInfCTeNormOS
     */
    cobr?: CteOsSefazCobrOS;
    /**
     * 
     * @type {Array<CteOsSefazInfGTVeOS>}
     * @memberof CteOsSefazInfCTeNormOS
     */
    infGTVe?: Array<CteOsSefazInfGTVeOS>;
}

/**
 * Check if a given object implements the CteOsSefazInfCTeNormOS interface.
 */
export function instanceOfCteOsSefazInfCTeNormOS(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "infServico" in value;

    return isInstance;
}

export function CteOsSefazInfCTeNormOSFromJSON(json: any): CteOsSefazInfCTeNormOS {
    return CteOsSefazInfCTeNormOSFromJSONTyped(json, false);
}

export function CteOsSefazInfCTeNormOSFromJSONTyped(json: any, ignoreDiscriminator: boolean): CteOsSefazInfCTeNormOS {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'infServico': CteOsSefazInfServicoOSFromJSON(json['infServico']),
        'infDocRef': !exists(json, 'infDocRef') ? undefined : ((json['infDocRef'] as Array<any>).map(CteOsSefazInfDocRefOSFromJSON)),
        'seg': !exists(json, 'seg') ? undefined : ((json['seg'] as Array<any>).map(CteOsSefazSegOSFromJSON)),
        'infModal': !exists(json, 'infModal') ? undefined : CteOsSefazInfModalOSFromJSON(json['infModal']),
        'infCteSub': !exists(json, 'infCteSub') ? undefined : CteOsSefazInfCteSubOSFromJSON(json['infCteSub']),
        'refCTeCanc': !exists(json, 'refCTeCanc') ? undefined : json['refCTeCanc'],
        'cobr': !exists(json, 'cobr') ? undefined : CteOsSefazCobrOSFromJSON(json['cobr']),
        'infGTVe': !exists(json, 'infGTVe') ? undefined : ((json['infGTVe'] as Array<any>).map(CteOsSefazInfGTVeOSFromJSON)),
    };
}

export function CteOsSefazInfCTeNormOSToJSON(value?: CteOsSefazInfCTeNormOS | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'infServico': CteOsSefazInfServicoOSToJSON(value.infServico),
        'infDocRef': value.infDocRef === undefined ? undefined : ((value.infDocRef as Array<any>).map(CteOsSefazInfDocRefOSToJSON)),
        'seg': value.seg === undefined ? undefined : ((value.seg as Array<any>).map(CteOsSefazSegOSToJSON)),
        'infModal': CteOsSefazInfModalOSToJSON(value.infModal),
        'infCteSub': CteOsSefazInfCteSubOSToJSON(value.infCteSub),
        'refCTeCanc': value.refCTeCanc,
        'cobr': CteOsSefazCobrOSToJSON(value.cobr),
        'infGTVe': value.infGTVe === undefined ? undefined : ((value.infGTVe as Array<any>).map(CteOsSefazInfGTVeOSToJSON)),
    };
}

