/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CteOsSefazCIBSOS } from './CteOsSefazCIBSOS';
import {
    CteOsSefazCIBSOSFromJSON,
    CteOsSefazCIBSOSFromJSONTyped,
    CteOsSefazCIBSOSToJSON,
} from './CteOsSefazCIBSOS';
import type { CteOsSefazEstornoCredOS } from './CteOsSefazEstornoCredOS';
import {
    CteOsSefazEstornoCredOSFromJSON,
    CteOsSefazEstornoCredOSFromJSONTyped,
    CteOsSefazEstornoCredOSToJSON,
} from './CteOsSefazEstornoCredOS';

/**
 * Grupo de informações do IBS e CBS.
 * @export
 * @interface CteOsSefazTribCTeOS
 */
export interface CteOsSefazTribCTeOS {
    /**
     * Código Situação Tributária do IBS/CBS.
     * @type {string}
     * @memberof CteOsSefazTribCTeOS
     */
    CST: string | null;
    /**
     * 
     * @type {string}
     * @memberof CteOsSefazTribCTeOS
     */
    cClassTrib?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CteOsSefazTribCTeOS
     */
    indDoacao?: number | null;
    /**
     * 
     * @type {CteOsSefazCIBSOS}
     * @memberof CteOsSefazTribCTeOS
     */
    gIBSCBS?: CteOsSefazCIBSOS;
    /**
     * 
     * @type {CteOsSefazEstornoCredOS}
     * @memberof CteOsSefazTribCTeOS
     */
    gEstornoCred?: CteOsSefazEstornoCredOS;
}

/**
 * Check if a given object implements the CteOsSefazTribCTeOS interface.
 */
export function instanceOfCteOsSefazTribCTeOS(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "CST" in value;

    return isInstance;
}

export function CteOsSefazTribCTeOSFromJSON(json: any): CteOsSefazTribCTeOS {
    return CteOsSefazTribCTeOSFromJSONTyped(json, false);
}

export function CteOsSefazTribCTeOSFromJSONTyped(json: any, ignoreDiscriminator: boolean): CteOsSefazTribCTeOS {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'CST': json['CST'],
        'cClassTrib': !exists(json, 'cClassTrib') ? undefined : json['cClassTrib'],
        'indDoacao': !exists(json, 'indDoacao') ? undefined : json['indDoacao'],
        'gIBSCBS': !exists(json, 'gIBSCBS') ? undefined : CteOsSefazCIBSOSFromJSON(json['gIBSCBS']),
        'gEstornoCred': !exists(json, 'gEstornoCred') ? undefined : CteOsSefazEstornoCredOSFromJSON(json['gEstornoCred']),
    };
}

export function CteOsSefazTribCTeOSToJSON(value?: CteOsSefazTribCTeOS | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'CST': value.CST,
        'cClassTrib': value.cClassTrib,
        'indDoacao': value.indDoacao,
        'gIBSCBS': CteOsSefazCIBSOSToJSON(value.gIBSCBS),
        'gEstornoCred': CteOsSefazEstornoCredOSToJSON(value.gEstornoCred),
    };
}

