/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Dados do fretamento (apenas para Transporte de Pessoas).
 * @export
 * @interface CteOsSefazInfFretamentoOS
 */
export interface CteOsSefazInfFretamentoOS {
    /**
     * Tipo Fretamento.
     * Preencher com:
     * * 1 - Eventual 2 - Continuo
     * @type {number}
     * @memberof CteOsSefazInfFretamentoOS
     */
    tpFretamento: number | null;
    /**
     * Data e hora da viagem (Apenas para fretamento eventual).
     * Formato AAAA-MM-DDTHH:MM:DD TZD.
     * @type {Date}
     * @memberof CteOsSefazInfFretamentoOS
     */
    dhViagem?: Date | null;
}

/**
 * Check if a given object implements the CteOsSefazInfFretamentoOS interface.
 */
export function instanceOfCteOsSefazInfFretamentoOS(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "tpFretamento" in value;

    return isInstance;
}

export function CteOsSefazInfFretamentoOSFromJSON(json: any): CteOsSefazInfFretamentoOS {
    return CteOsSefazInfFretamentoOSFromJSONTyped(json, false);
}

export function CteOsSefazInfFretamentoOSFromJSONTyped(json: any, ignoreDiscriminator: boolean): CteOsSefazInfFretamentoOS {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tpFretamento': json['tpFretamento'],
        'dhViagem': !exists(json, 'dhViagem') ? undefined : (json['dhViagem'] === null ? null : new Date(json['dhViagem'])),
    };
}

export function CteOsSefazInfFretamentoOSToJSON(value?: CteOsSefazInfFretamentoOS | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tpFretamento': value.tpFretamento,
        'dhViagem': value.dhViagem === undefined ? undefined : (value.dhViagem === null ? null : value.dhViagem.toISOString()),
    };
}

