/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CteOsSefazDupOS } from './CteOsSefazDupOS';
import {
    CteOsSefazDupOSFromJSON,
    CteOsSefazDupOSFromJSONTyped,
    CteOsSefazDupOSToJSON,
} from './CteOsSefazDupOS';
import type { CteOsSefazFatOS } from './CteOsSefazFatOS';
import {
    CteOsSefazFatOSFromJSON,
    CteOsSefazFatOSFromJSONTyped,
    CteOsSefazFatOSToJSON,
} from './CteOsSefazFatOS';

/**
 * Dados da cobrança do CT-e.
 * @export
 * @interface CteOsSefazCobrOS
 */
export interface CteOsSefazCobrOS {
    /**
     * 
     * @type {CteOsSefazFatOS}
     * @memberof CteOsSefazCobrOS
     */
    fat?: CteOsSefazFatOS;
    /**
     * 
     * @type {Array<CteOsSefazDupOS>}
     * @memberof CteOsSefazCobrOS
     */
    dup?: Array<CteOsSefazDupOS>;
}

/**
 * Check if a given object implements the CteOsSefazCobrOS interface.
 */
export function instanceOfCteOsSefazCobrOS(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CteOsSefazCobrOSFromJSON(json: any): CteOsSefazCobrOS {
    return CteOsSefazCobrOSFromJSONTyped(json, false);
}

export function CteOsSefazCobrOSFromJSONTyped(json: any, ignoreDiscriminator: boolean): CteOsSefazCobrOS {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fat': !exists(json, 'fat') ? undefined : CteOsSefazFatOSFromJSON(json['fat']),
        'dup': !exists(json, 'dup') ? undefined : ((json['dup'] as Array<any>).map(CteOsSefazDupOSFromJSON)),
    };
}

export function CteOsSefazCobrOSToJSON(value?: CteOsSefazCobrOS | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fat': CteOsSefazFatOSToJSON(value.fat),
        'dup': value.dup === undefined ? undefined : ((value.dup as Array<any>).map(CteOsSefazDupOSToJSON)),
    };
}

