/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CteSefazEntrega } from './CteSefazEntrega';
import {
    CteSefazEntregaFromJSON,
    CteSefazEntregaFromJSONTyped,
    CteSefazEntregaToJSON,
} from './CteSefazEntrega';
import type { CteSefazFluxo } from './CteSefazFluxo';
import {
    CteSefazFluxoFromJSON,
    CteSefazFluxoFromJSONTyped,
    CteSefazFluxoToJSON,
} from './CteSefazFluxo';
import type { CteSefazObsCont } from './CteSefazObsCont';
import {
    CteSefazObsContFromJSON,
    CteSefazObsContFromJSONTyped,
    CteSefazObsContToJSON,
} from './CteSefazObsCont';
import type { CteSefazObsFisco } from './CteSefazObsFisco';
import {
    CteSefazObsFiscoFromJSON,
    CteSefazObsFiscoFromJSONTyped,
    CteSefazObsFiscoToJSON,
} from './CteSefazObsFisco';

/**
 * Dados complementares do CT-e para fins operacionais ou comerciais.
 * @export
 * @interface CteSefazCompl
 */
export interface CteSefazCompl {
    /**
     * Característica adicional do transporte.
     * Texto livre:
     * REENTREGA
     * DEVOLUÇÃO
     * REFATURAMENTO
     * etc.
     * @type {string}
     * @memberof CteSefazCompl
     */
    xCaracAd?: string | null;
    /**
     * Característica adicional do serviço.
     * Texto livre:
     * ENTREGA EXPRESSA
     * LOGÍSTICA REVERSA
     * CONVENCIONAL
     * EMERGENCIAL
     * etc.
     * @type {string}
     * @memberof CteSefazCompl
     */
    xCaracSer?: string | null;
    /**
     * Funcionário emissor do CTe.
     * @type {string}
     * @memberof CteSefazCompl
     */
    xEmi?: string | null;
    /**
     * 
     * @type {CteSefazFluxo}
     * @memberof CteSefazCompl
     */
    fluxo?: CteSefazFluxo;
    /**
     * 
     * @type {CteSefazEntrega}
     * @memberof CteSefazCompl
     */
    Entrega?: CteSefazEntrega;
    /**
     * Município de origem para efeito de cálculo do frete.
     * @type {string}
     * @memberof CteSefazCompl
     */
    origCalc?: string | null;
    /**
     * Município de destino para efeito de cálculo do frete.
     * @type {string}
     * @memberof CteSefazCompl
     */
    destCalc?: string | null;
    /**
     * Observações Gerais.
     * @type {string}
     * @memberof CteSefazCompl
     */
    xObs?: string | null;
    /**
     * 
     * @type {Array<CteSefazObsCont>}
     * @memberof CteSefazCompl
     */
    ObsCont?: Array<CteSefazObsCont>;
    /**
     * 
     * @type {Array<CteSefazObsFisco>}
     * @memberof CteSefazCompl
     */
    ObsFisco?: Array<CteSefazObsFisco>;
}

/**
 * Check if a given object implements the CteSefazCompl interface.
 */
export function instanceOfCteSefazCompl(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CteSefazComplFromJSON(json: any): CteSefazCompl {
    return CteSefazComplFromJSONTyped(json, false);
}

export function CteSefazComplFromJSONTyped(json: any, ignoreDiscriminator: boolean): CteSefazCompl {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'xCaracAd': !exists(json, 'xCaracAd') ? undefined : json['xCaracAd'],
        'xCaracSer': !exists(json, 'xCaracSer') ? undefined : json['xCaracSer'],
        'xEmi': !exists(json, 'xEmi') ? undefined : json['xEmi'],
        'fluxo': !exists(json, 'fluxo') ? undefined : CteSefazFluxoFromJSON(json['fluxo']),
        'Entrega': !exists(json, 'Entrega') ? undefined : CteSefazEntregaFromJSON(json['Entrega']),
        'origCalc': !exists(json, 'origCalc') ? undefined : json['origCalc'],
        'destCalc': !exists(json, 'destCalc') ? undefined : json['destCalc'],
        'xObs': !exists(json, 'xObs') ? undefined : json['xObs'],
        'ObsCont': !exists(json, 'ObsCont') ? undefined : ((json['ObsCont'] as Array<any>).map(CteSefazObsContFromJSON)),
        'ObsFisco': !exists(json, 'ObsFisco') ? undefined : ((json['ObsFisco'] as Array<any>).map(CteSefazObsFiscoFromJSON)),
    };
}

export function CteSefazComplToJSON(value?: CteSefazCompl | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'xCaracAd': value.xCaracAd,
        'xCaracSer': value.xCaracSer,
        'xEmi': value.xEmi,
        'fluxo': CteSefazFluxoToJSON(value.fluxo),
        'Entrega': CteSefazEntregaToJSON(value.Entrega),
        'origCalc': value.origCalc,
        'destCalc': value.destCalc,
        'xObs': value.xObs,
        'ObsCont': value.ObsCont === undefined ? undefined : ((value.ObsCont as Array<any>).map(CteSefazObsContToJSON)),
        'ObsFisco': value.ObsFisco === undefined ? undefined : ((value.ObsFisco as Array<any>).map(CteSefazObsFiscoToJSON)),
    };
}

