/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CteSimpSefazBalsaSimp } from './CteSimpSefazBalsaSimp';
import {
    CteSimpSefazBalsaSimpFromJSON,
    CteSimpSefazBalsaSimpFromJSONTyped,
    CteSimpSefazBalsaSimpToJSON,
} from './CteSimpSefazBalsaSimp';
import type { CteSimpSefazDetContSimp } from './CteSimpSefazDetContSimp';
import {
    CteSimpSefazDetContSimpFromJSON,
    CteSimpSefazDetContSimpFromJSONTyped,
    CteSimpSefazDetContSimpToJSON,
} from './CteSimpSefazDetContSimp';

/**
 * Informações do modal Aquaviário.
 * @export
 * @interface CteSimpSefazAquavSimp
 */
export interface CteSimpSefazAquavSimp {
    /**
     * Valor da Prestação Base de Cálculo do AFRMM.
     * @type {number}
     * @memberof CteSimpSefazAquavSimp
     */
    vPrest: number | null;
    /**
     * AFRMM (Adicional de Frete para Renovação da Marinha Mercante).
     * @type {number}
     * @memberof CteSimpSefazAquavSimp
     */
    vAFRMM: number | null;
    /**
     * Identificação do Navio.
     * @type {string}
     * @memberof CteSimpSefazAquavSimp
     */
    xNavio: string | null;
    /**
     * 
     * @type {Array<CteSimpSefazBalsaSimp>}
     * @memberof CteSimpSefazAquavSimp
     */
    balsa?: Array<CteSimpSefazBalsaSimp>;
    /**
     * Número da Viagem.
     * @type {string}
     * @memberof CteSimpSefazAquavSimp
     */
    nViag?: string | null;
    /**
     * Direção.
     * Preencher com: N-Norte, L-Leste, S-Sul, O-Oeste.
     * @type {string}
     * @memberof CteSimpSefazAquavSimp
     */
    direc: string | null;
    /**
     * Irin do navio sempre deverá ser informado.
     * @type {string}
     * @memberof CteSimpSefazAquavSimp
     */
    irin: string | null;
    /**
     * 
     * @type {Array<CteSimpSefazDetContSimp>}
     * @memberof CteSimpSefazAquavSimp
     */
    detCont?: Array<CteSimpSefazDetContSimp>;
    /**
     * Tipo de Navegação.
     * Preencher com:
     * * 0 - Interior
     * * 1 - Cabotagem
     * @type {number}
     * @memberof CteSimpSefazAquavSimp
     */
    tpNav?: number | null;
}

/**
 * Check if a given object implements the CteSimpSefazAquavSimp interface.
 */
export function instanceOfCteSimpSefazAquavSimp(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "vPrest" in value;
    isInstance = isInstance && "vAFRMM" in value;
    isInstance = isInstance && "xNavio" in value;
    isInstance = isInstance && "direc" in value;
    isInstance = isInstance && "irin" in value;

    return isInstance;
}

export function CteSimpSefazAquavSimpFromJSON(json: any): CteSimpSefazAquavSimp {
    return CteSimpSefazAquavSimpFromJSONTyped(json, false);
}

export function CteSimpSefazAquavSimpFromJSONTyped(json: any, ignoreDiscriminator: boolean): CteSimpSefazAquavSimp {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'vPrest': json['vPrest'],
        'vAFRMM': json['vAFRMM'],
        'xNavio': json['xNavio'],
        'balsa': !exists(json, 'balsa') ? undefined : ((json['balsa'] as Array<any>).map(CteSimpSefazBalsaSimpFromJSON)),
        'nViag': !exists(json, 'nViag') ? undefined : json['nViag'],
        'direc': json['direc'],
        'irin': json['irin'],
        'detCont': !exists(json, 'detCont') ? undefined : ((json['detCont'] as Array<any>).map(CteSimpSefazDetContSimpFromJSON)),
        'tpNav': !exists(json, 'tpNav') ? undefined : json['tpNav'],
    };
}

export function CteSimpSefazAquavSimpToJSON(value?: CteSimpSefazAquavSimp | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'vPrest': value.vPrest,
        'vAFRMM': value.vAFRMM,
        'xNavio': value.xNavio,
        'balsa': value.balsa === undefined ? undefined : ((value.balsa as Array<any>).map(CteSimpSefazBalsaSimpToJSON)),
        'nViag': value.nViag,
        'direc': value.direc,
        'irin': value.irin,
        'detCont': value.detCont === undefined ? undefined : ((value.detCont as Array<any>).map(CteSimpSefazDetContSimpToJSON)),
        'tpNav': value.tpNav,
    };
}

