/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Informações suplementares do CT-e.
 * @export
 * @interface CteSefazInfCTeSupl
 */
export interface CteSefazInfCTeSupl {
    /**
     * Texto com o QR-Code impresso no DACTE.
     * 
     * *Geramos automaticamente quando nenhum valor é informado.*
     * @type {string}
     * @memberof CteSefazInfCTeSupl
     */
    qrCodCTe?: string | null;
}

/**
 * Check if a given object implements the CteSefazInfCTeSupl interface.
 */
export function instanceOfCteSefazInfCTeSupl(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CteSefazInfCTeSuplFromJSON(json: any): CteSefazInfCTeSupl {
    return CteSefazInfCTeSuplFromJSONTyped(json, false);
}

export function CteSefazInfCTeSuplFromJSONTyped(json: any, ignoreDiscriminator: boolean): CteSefazInfCTeSupl {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'qrCodCTe': !exists(json, 'qrCodCTe') ? undefined : json['qrCodCTe'],
    };
}

export function CteSefazInfCTeSuplToJSON(value?: CteSefazInfCTeSupl | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'qrCodCTe': value.qrCodCTe,
    };
}

