/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CteSimpSefazNatCargaSimp } from './CteSimpSefazNatCargaSimp';
import {
    CteSimpSefazNatCargaSimpFromJSON,
    CteSimpSefazNatCargaSimpFromJSONTyped,
    CteSimpSefazNatCargaSimpToJSON,
} from './CteSimpSefazNatCargaSimp';
import type { CteSimpSefazPeriSimp } from './CteSimpSefazPeriSimp';
import {
    CteSimpSefazPeriSimpFromJSON,
    CteSimpSefazPeriSimpFromJSONTyped,
    CteSimpSefazPeriSimpToJSON,
} from './CteSimpSefazPeriSimp';
import type { CteSimpSefazTarifaSimp } from './CteSimpSefazTarifaSimp';
import {
    CteSimpSefazTarifaSimpFromJSON,
    CteSimpSefazTarifaSimpFromJSONTyped,
    CteSimpSefazTarifaSimpToJSON,
} from './CteSimpSefazTarifaSimp';

/**
 * Informações do modal Aéreo.
 * @export
 * @interface CteSimpSefazAereoSimp
 */
export interface CteSimpSefazAereoSimp {
    /**
     * Número da Minuta.
     * Documento que precede o CT-e, assinado pelo expedidor, espécie de pedido de serviço.
     * @type {number}
     * @memberof CteSimpSefazAereoSimp
     */
    nMinu?: number | null;
    /**
     * Número Operacional do Conhecimento Aéreo.
     * Representa o número de controle comumente utilizado pelo conhecimento aéreo composto por uma sequência numérica de onze dígitos. Os três primeiros dígitos representam um código que os operadores de transporte aéreo associados à IATA possuem. Em seguida um número de série de sete dígitos determinados pelo operador de transporte aéreo. Para finalizar, um dígito verificador, que é um sistema de módulo sete imponderado o qual divide o número de série do conhecimento aéreo por sete e usa o resto como dígito de verificação.
     * @type {string}
     * @memberof CteSimpSefazAereoSimp
     */
    nOCA?: string | null;
    /**
     * Data prevista da entrega.
     * Formato AAAA-MM-DD.
     * @type {Date}
     * @memberof CteSimpSefazAereoSimp
     */
    dPrevAereo: Date | null;
    /**
     * 
     * @type {CteSimpSefazNatCargaSimp}
     * @memberof CteSimpSefazAereoSimp
     */
    natCarga: CteSimpSefazNatCargaSimp;
    /**
     * 
     * @type {CteSimpSefazTarifaSimp}
     * @memberof CteSimpSefazAereoSimp
     */
    tarifa: CteSimpSefazTarifaSimp;
    /**
     * 
     * @type {Array<CteSimpSefazPeriSimp>}
     * @memberof CteSimpSefazAereoSimp
     */
    peri?: Array<CteSimpSefazPeriSimp>;
}

/**
 * Check if a given object implements the CteSimpSefazAereoSimp interface.
 */
export function instanceOfCteSimpSefazAereoSimp(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "dPrevAereo" in value;
    isInstance = isInstance && "natCarga" in value;
    isInstance = isInstance && "tarifa" in value;

    return isInstance;
}

export function CteSimpSefazAereoSimpFromJSON(json: any): CteSimpSefazAereoSimp {
    return CteSimpSefazAereoSimpFromJSONTyped(json, false);
}

export function CteSimpSefazAereoSimpFromJSONTyped(json: any, ignoreDiscriminator: boolean): CteSimpSefazAereoSimp {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nMinu': !exists(json, 'nMinu') ? undefined : json['nMinu'],
        'nOCA': !exists(json, 'nOCA') ? undefined : json['nOCA'],
        'dPrevAereo': (json['dPrevAereo'] === null ? null : new Date(json['dPrevAereo'])),
        'natCarga': CteSimpSefazNatCargaSimpFromJSON(json['natCarga']),
        'tarifa': CteSimpSefazTarifaSimpFromJSON(json['tarifa']),
        'peri': !exists(json, 'peri') ? undefined : ((json['peri'] as Array<any>).map(CteSimpSefazPeriSimpFromJSON)),
    };
}

export function CteSimpSefazAereoSimpToJSON(value?: CteSimpSefazAereoSimp | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nMinu': value.nMinu,
        'nOCA': value.nOCA,
        'dPrevAereo': (value.dPrevAereo === null ? null : value.dPrevAereo.toISOString().substr(0,10)),
        'natCarga': CteSimpSefazNatCargaSimpToJSON(value.natCarga),
        'tarifa': CteSimpSefazTarifaSimpToJSON(value.tarifa),
        'peri': value.peri === undefined ? undefined : ((value.peri as Array<any>).map(CteSimpSefazPeriSimpToJSON)),
    };
}

