/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * ICMS  Isento, não Tributado ou diferido.
 * @export
 * @interface CteSimpSefazICMS45Simp
 */
export interface CteSimpSefazICMS45Simp {
    /**
     * Classificação Tributária do Serviço.
     * Preencher com:
     * * 40 - ICMS isenção
     * * 41 - ICMS não tributada
     * * 51 - ICMS diferido
     * @type {string}
     * @memberof CteSimpSefazICMS45Simp
     */
    CST: string | null;
    /**
     * Valor do ICMS de desoneração.
     * @type {number}
     * @memberof CteSimpSefazICMS45Simp
     */
    vICMSDeson?: number | null;
    /**
     * Código de Benefício Fiscal na UF.
     * Código de Benefício Fiscal utilizado pela UF.
     * @type {string}
     * @memberof CteSimpSefazICMS45Simp
     */
    cBenef?: string | null;
}

/**
 * Check if a given object implements the CteSimpSefazICMS45Simp interface.
 */
export function instanceOfCteSimpSefazICMS45Simp(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "CST" in value;

    return isInstance;
}

export function CteSimpSefazICMS45SimpFromJSON(json: any): CteSimpSefazICMS45Simp {
    return CteSimpSefazICMS45SimpFromJSONTyped(json, false);
}

export function CteSimpSefazICMS45SimpFromJSONTyped(json: any, ignoreDiscriminator: boolean): CteSimpSefazICMS45Simp {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'CST': json['CST'],
        'vICMSDeson': !exists(json, 'vICMSDeson') ? undefined : json['vICMSDeson'],
        'cBenef': !exists(json, 'cBenef') ? undefined : json['cBenef'],
    };
}

export function CteSimpSefazICMS45SimpToJSON(value?: CteSimpSefazICMS45Simp | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'CST': value.CST,
        'vICMSDeson': value.vICMSDeson,
        'cBenef': value.cBenef,
    };
}

