/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CteSimpSefazInfDocInfNFeSimp } from './CteSimpSefazInfDocInfNFeSimp';
import {
    CteSimpSefazInfDocInfNFeSimpFromJSON,
    CteSimpSefazInfDocInfNFeSimpFromJSONTyped,
    CteSimpSefazInfDocInfNFeSimpToJSON,
} from './CteSimpSefazInfDocInfNFeSimp';
import type { CteSimpSefazInfNFSimp } from './CteSimpSefazInfNFSimp';
import {
    CteSimpSefazInfNFSimpFromJSON,
    CteSimpSefazInfNFSimpFromJSONTyped,
    CteSimpSefazInfNFSimpToJSON,
} from './CteSimpSefazInfNFSimp';

/**
 * Informações dos documentos dos conteiners.
 * @export
 * @interface CteSimpSefazInfDocSimp
 */
export interface CteSimpSefazInfDocSimp {
    /**
     * 
     * @type {Array<CteSimpSefazInfNFSimp>}
     * @memberof CteSimpSefazInfDocSimp
     */
    infNF?: Array<CteSimpSefazInfNFSimp>;
    /**
     * 
     * @type {Array<CteSimpSefazInfDocInfNFeSimp>}
     * @memberof CteSimpSefazInfDocSimp
     */
    infNFe?: Array<CteSimpSefazInfDocInfNFeSimp>;
}

/**
 * Check if a given object implements the CteSimpSefazInfDocSimp interface.
 */
export function instanceOfCteSimpSefazInfDocSimp(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CteSimpSefazInfDocSimpFromJSON(json: any): CteSimpSefazInfDocSimp {
    return CteSimpSefazInfDocSimpFromJSONTyped(json, false);
}

export function CteSimpSefazInfDocSimpFromJSONTyped(json: any, ignoreDiscriminator: boolean): CteSimpSefazInfDocSimp {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'infNF': !exists(json, 'infNF') ? undefined : ((json['infNF'] as Array<any>).map(CteSimpSefazInfNFSimpFromJSON)),
        'infNFe': !exists(json, 'infNFe') ? undefined : ((json['infNFe'] as Array<any>).map(CteSimpSefazInfDocInfNFeSimpFromJSON)),
    };
}

export function CteSimpSefazInfDocSimpToJSON(value?: CteSimpSefazInfDocSimp | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'infNF': value.infNF === undefined ? undefined : ((value.infNF as Array<any>).map(CteSimpSefazInfNFSimpToJSON)),
        'infNFe': value.infNFe === undefined ? undefined : ((value.infNFe as Array<any>).map(CteSimpSefazInfDocInfNFeSimpToJSON)),
    };
}

