/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Dados de cada pagamento previsto.
 * @export
 * @interface CteSimpSefazPagamentoRTCSimp
 */
export interface CteSimpSefazPagamentoRTCSimp {
    /**
     * Número sequencial do pagamento.
     * @type {string}
     * @memberof CteSimpSefazPagamentoRTCSimp
     */
    nPag: string | null;
    /**
     * ID específico da transação financeira conforme o meio de pagamento.
     * @type {string}
     * @memberof CteSimpSefazPagamentoRTCSimp
     */
    idTransacao: string | null;
    /**
     * (Meio de pagamento utilizado (ver IT DFe 2026.001).
     * @type {string}
     * @memberof CteSimpSefazPagamentoRTCSimp
     */
    tpMeioPgto: string | null;
    /**
     * CNPJ do recebedor do pagamento.
     * Informar zeros não significativos.
     * @type {string}
     * @memberof CteSimpSefazPagamentoRTCSimp
     */
    CNPJReceb: string | null;
    /**
     * CNPJ base da instituição financeira.
     * Informar zeros não significativos.
     * @type {string}
     * @memberof CteSimpSefazPagamentoRTCSimp
     */
    CNPJBasePSP: string | null;
}

/**
 * Check if a given object implements the CteSimpSefazPagamentoRTCSimp interface.
 */
export function instanceOfCteSimpSefazPagamentoRTCSimp(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "nPag" in value;
    isInstance = isInstance && "idTransacao" in value;
    isInstance = isInstance && "tpMeioPgto" in value;
    isInstance = isInstance && "CNPJReceb" in value;
    isInstance = isInstance && "CNPJBasePSP" in value;

    return isInstance;
}

export function CteSimpSefazPagamentoRTCSimpFromJSON(json: any): CteSimpSefazPagamentoRTCSimp {
    return CteSimpSefazPagamentoRTCSimpFromJSONTyped(json, false);
}

export function CteSimpSefazPagamentoRTCSimpFromJSONTyped(json: any, ignoreDiscriminator: boolean): CteSimpSefazPagamentoRTCSimp {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nPag': json['nPag'],
        'idTransacao': json['idTransacao'],
        'tpMeioPgto': json['tpMeioPgto'],
        'CNPJReceb': json['CNPJReceb'],
        'CNPJBasePSP': json['CNPJBasePSP'],
    };
}

export function CteSimpSefazPagamentoRTCSimpToJSON(value?: CteSimpSefazPagamentoRTCSimp | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nPag': value.nPag,
        'idTransacao': value.idTransacao,
        'tpMeioPgto': value.tpMeioPgto,
        'CNPJReceb': value.CNPJReceb,
        'CNPJBasePSP': value.CNPJBasePSP,
    };
}

