/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CteSefazDetContInfDocInfNF } from './CteSefazDetContInfDocInfNF';
import {
    CteSefazDetContInfDocInfNFFromJSON,
    CteSefazDetContInfDocInfNFFromJSONTyped,
    CteSefazDetContInfDocInfNFToJSON,
} from './CteSefazDetContInfDocInfNF';
import type { CteSefazDetContInfDocInfNFe } from './CteSefazDetContInfDocInfNFe';
import {
    CteSefazDetContInfDocInfNFeFromJSON,
    CteSefazDetContInfDocInfNFeFromJSONTyped,
    CteSefazDetContInfDocInfNFeToJSON,
} from './CteSefazDetContInfDocInfNFe';

/**
 * Informações dos documentos dos conteiners.
 * @export
 * @interface CteSefazDetContInfDoc
 */
export interface CteSefazDetContInfDoc {
    /**
     * 
     * @type {Array<CteSefazDetContInfDocInfNF>}
     * @memberof CteSefazDetContInfDoc
     */
    infNF?: Array<CteSefazDetContInfDocInfNF>;
    /**
     * 
     * @type {Array<CteSefazDetContInfDocInfNFe>}
     * @memberof CteSefazDetContInfDoc
     */
    infNFe?: Array<CteSefazDetContInfDocInfNFe>;
}

/**
 * Check if a given object implements the CteSefazDetContInfDoc interface.
 */
export function instanceOfCteSefazDetContInfDoc(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CteSefazDetContInfDocFromJSON(json: any): CteSefazDetContInfDoc {
    return CteSefazDetContInfDocFromJSONTyped(json, false);
}

export function CteSefazDetContInfDocFromJSONTyped(json: any, ignoreDiscriminator: boolean): CteSefazDetContInfDoc {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'infNF': !exists(json, 'infNF') ? undefined : ((json['infNF'] as Array<any>).map(CteSefazDetContInfDocInfNFFromJSON)),
        'infNFe': !exists(json, 'infNFe') ? undefined : ((json['infNFe'] as Array<any>).map(CteSefazDetContInfDocInfNFeFromJSON)),
    };
}

export function CteSefazDetContInfDocToJSON(value?: CteSefazDetContInfDoc | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'infNF': value.infNF === undefined ? undefined : ((value.infNF as Array<any>).map(CteSefazDetContInfDocInfNFToJSON)),
        'infNFe': value.infNFe === undefined ? undefined : ((value.infNFe as Array<any>).map(CteSefazDetContInfDocInfNFeToJSON)),
    };
}

