/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CteSefazComData } from './CteSefazComData';
import {
    CteSefazComDataFromJSON,
    CteSefazComDataFromJSONTyped,
    CteSefazComDataToJSON,
} from './CteSefazComData';
import type { CteSefazComHora } from './CteSefazComHora';
import {
    CteSefazComHoraFromJSON,
    CteSefazComHoraFromJSONTyped,
    CteSefazComHoraToJSON,
} from './CteSefazComHora';
import type { CteSefazNoInter } from './CteSefazNoInter';
import {
    CteSefazNoInterFromJSON,
    CteSefazNoInterFromJSONTyped,
    CteSefazNoInterToJSON,
} from './CteSefazNoInter';
import type { CteSefazNoPeriodo } from './CteSefazNoPeriodo';
import {
    CteSefazNoPeriodoFromJSON,
    CteSefazNoPeriodoFromJSONTyped,
    CteSefazNoPeriodoToJSON,
} from './CteSefazNoPeriodo';
import type { CteSefazSemData } from './CteSefazSemData';
import {
    CteSefazSemDataFromJSON,
    CteSefazSemDataFromJSONTyped,
    CteSefazSemDataToJSON,
} from './CteSefazSemData';
import type { CteSefazSemHora } from './CteSefazSemHora';
import {
    CteSefazSemHoraFromJSON,
    CteSefazSemHoraFromJSONTyped,
    CteSefazSemHoraToJSON,
} from './CteSefazSemHora';

/**
 * Informações ref. a previsão de entrega.
 * @export
 * @interface CteSefazEntrega
 */
export interface CteSefazEntrega {
    /**
     * 
     * @type {CteSefazSemData}
     * @memberof CteSefazEntrega
     */
    semData?: CteSefazSemData;
    /**
     * 
     * @type {CteSefazComData}
     * @memberof CteSefazEntrega
     */
    comData?: CteSefazComData;
    /**
     * 
     * @type {CteSefazNoPeriodo}
     * @memberof CteSefazEntrega
     */
    noPeriodo?: CteSefazNoPeriodo;
    /**
     * 
     * @type {CteSefazSemHora}
     * @memberof CteSefazEntrega
     */
    semHora?: CteSefazSemHora;
    /**
     * 
     * @type {CteSefazComHora}
     * @memberof CteSefazEntrega
     */
    comHora?: CteSefazComHora;
    /**
     * 
     * @type {CteSefazNoInter}
     * @memberof CteSefazEntrega
     */
    noInter?: CteSefazNoInter;
}

/**
 * Check if a given object implements the CteSefazEntrega interface.
 */
export function instanceOfCteSefazEntrega(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CteSefazEntregaFromJSON(json: any): CteSefazEntrega {
    return CteSefazEntregaFromJSONTyped(json, false);
}

export function CteSefazEntregaFromJSONTyped(json: any, ignoreDiscriminator: boolean): CteSefazEntrega {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'semData': !exists(json, 'semData') ? undefined : CteSefazSemDataFromJSON(json['semData']),
        'comData': !exists(json, 'comData') ? undefined : CteSefazComDataFromJSON(json['comData']),
        'noPeriodo': !exists(json, 'noPeriodo') ? undefined : CteSefazNoPeriodoFromJSON(json['noPeriodo']),
        'semHora': !exists(json, 'semHora') ? undefined : CteSefazSemHoraFromJSON(json['semHora']),
        'comHora': !exists(json, 'comHora') ? undefined : CteSefazComHoraFromJSON(json['comHora']),
        'noInter': !exists(json, 'noInter') ? undefined : CteSefazNoInterFromJSON(json['noInter']),
    };
}

export function CteSefazEntregaToJSON(value?: CteSefazEntrega | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'semData': CteSefazSemDataToJSON(value.semData),
        'comData': CteSefazComDataToJSON(value.comData),
        'noPeriodo': CteSefazNoPeriodoToJSON(value.noPeriodo),
        'semHora': CteSefazSemHoraToJSON(value.semHora),
        'comHora': CteSefazComHoraToJSON(value.comHora),
        'noInter': CteSefazNoInterToJSON(value.noInter),
    };
}

