/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CteSefazNatCarga } from './CteSefazNatCarga';
import {
    CteSefazNatCargaFromJSON,
    CteSefazNatCargaFromJSONTyped,
    CteSefazNatCargaToJSON,
} from './CteSefazNatCarga';
import type { CteSefazPeri } from './CteSefazPeri';
import {
    CteSefazPeriFromJSON,
    CteSefazPeriFromJSONTyped,
    CteSefazPeriToJSON,
} from './CteSefazPeri';
import type { CteSefazTarifa } from './CteSefazTarifa';
import {
    CteSefazTarifaFromJSON,
    CteSefazTarifaFromJSONTyped,
    CteSefazTarifaToJSON,
} from './CteSefazTarifa';

/**
 * Informações do modal Aéreo.
 * @export
 * @interface CteSefazAereo
 */
export interface CteSefazAereo {
    /**
     * Número da Minuta.
     * Documento que precede o CT-e, assinado pelo expedidor, espécie de pedido de serviço.
     * @type {number}
     * @memberof CteSefazAereo
     */
    nMinu?: number | null;
    /**
     * Número Operacional do Conhecimento Aéreo.
     * Representa o número de controle comumente utilizado pelo conhecimento aéreo composto por uma sequência numérica de onze dígitos. Os três primeiros dígitos representam um código que os operadores de transporte aéreo associados à IATA possuem. Em seguida um número de série de sete dígitos determinados pelo operador de transporte aéreo. Para finalizar, um dígito verificador, que é um sistema de módulo sete imponderado o qual divide o número de série do conhecimento aéreo por sete e usa o resto como dígito de verificação.
     * @type {string}
     * @memberof CteSefazAereo
     */
    nOCA?: string | null;
    /**
     * Data prevista da entrega.
     * Formato AAAA-MM-DD.
     * @type {Date}
     * @memberof CteSefazAereo
     */
    dPrevAereo: Date | null;
    /**
     * 
     * @type {CteSefazNatCarga}
     * @memberof CteSefazAereo
     */
    natCarga: CteSefazNatCarga;
    /**
     * 
     * @type {CteSefazTarifa}
     * @memberof CteSefazAereo
     */
    tarifa: CteSefazTarifa;
    /**
     * 
     * @type {Array<CteSefazPeri>}
     * @memberof CteSefazAereo
     */
    peri?: Array<CteSefazPeri>;
}

/**
 * Check if a given object implements the CteSefazAereo interface.
 */
export function instanceOfCteSefazAereo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "dPrevAereo" in value;
    isInstance = isInstance && "natCarga" in value;
    isInstance = isInstance && "tarifa" in value;

    return isInstance;
}

export function CteSefazAereoFromJSON(json: any): CteSefazAereo {
    return CteSefazAereoFromJSONTyped(json, false);
}

export function CteSefazAereoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CteSefazAereo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nMinu': !exists(json, 'nMinu') ? undefined : json['nMinu'],
        'nOCA': !exists(json, 'nOCA') ? undefined : json['nOCA'],
        'dPrevAereo': (json['dPrevAereo'] === null ? null : new Date(json['dPrevAereo'])),
        'natCarga': CteSefazNatCargaFromJSON(json['natCarga']),
        'tarifa': CteSefazTarifaFromJSON(json['tarifa']),
        'peri': !exists(json, 'peri') ? undefined : ((json['peri'] as Array<any>).map(CteSefazPeriFromJSON)),
    };
}

export function CteSefazAereoToJSON(value?: CteSefazAereo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nMinu': value.nMinu,
        'nOCA': value.nOCA,
        'dPrevAereo': (value.dPrevAereo === null ? null : value.dPrevAereo.toISOString().substr(0,10)),
        'natCarga': CteSefazNatCargaToJSON(value.natCarga),
        'tarifa': CteSefazTarifaToJSON(value.tarifa),
        'peri': value.peri === undefined ? undefined : ((value.peri as Array<any>).map(CteSefazPeriToJSON)),
    };
}

