/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Informações da seguradora.
 * @export
 * @interface CteSefazInfSeg
 */
export interface CteSefazInfSeg {
    /**
     * Nome da Seguradora.
     * @type {string}
     * @memberof CteSefazInfSeg
     */
    xSeg: string | null;
    /**
     * Número do CNPJ da seguradora.
     * Obrigatório apenas se responsável pelo seguro for (2) responsável pela contratação do transporte - pessoa jurídica.
     * @type {string}
     * @memberof CteSefazInfSeg
     */
    CNPJ: string | null;
}

/**
 * Check if a given object implements the CteSefazInfSeg interface.
 */
export function instanceOfCteSefazInfSeg(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "xSeg" in value;
    isInstance = isInstance && "CNPJ" in value;

    return isInstance;
}

export function CteSefazInfSegFromJSON(json: any): CteSefazInfSeg {
    return CteSefazInfSegFromJSONTyped(json, false);
}

export function CteSefazInfSegFromJSONTyped(json: any, ignoreDiscriminator: boolean): CteSefazInfSeg {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'xSeg': json['xSeg'],
        'CNPJ': json['CNPJ'],
    };
}

export function CteSefazInfSegToJSON(value?: CteSefazInfSeg | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'xSeg': value.xSeg,
        'CNPJ': value.CNPJ,
    };
}

