/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CteSefazInfSeg } from './CteSefazInfSeg';
import {
    CteSefazInfSegFromJSON,
    CteSefazInfSegFromJSONTyped,
    CteSefazInfSegToJSON,
} from './CteSefazInfSeg';

/**
 * Informações de Seguro do Multimodal.
 * @export
 * @interface CteSefazSeg
 */
export interface CteSefazSeg {
    /**
     * 
     * @type {CteSefazInfSeg}
     * @memberof CteSefazSeg
     */
    infSeg: CteSefazInfSeg;
    /**
     * Número da Apólice.
     * Obrigatório pela lei 11.442/07 (RCTRC).
     * @type {string}
     * @memberof CteSefazSeg
     */
    nApol: string | null;
    /**
     * Número da Averbação.
     * Não é obrigatório, pois muitas averbações ocorrem aapós a emissão do CT, mensalmente, por exemplo.
     * @type {string}
     * @memberof CteSefazSeg
     */
    nAver: string | null;
}

/**
 * Check if a given object implements the CteSefazSeg interface.
 */
export function instanceOfCteSefazSeg(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "infSeg" in value;
    isInstance = isInstance && "nApol" in value;
    isInstance = isInstance && "nAver" in value;

    return isInstance;
}

export function CteSefazSegFromJSON(json: any): CteSefazSeg {
    return CteSefazSegFromJSONTyped(json, false);
}

export function CteSefazSegFromJSONTyped(json: any, ignoreDiscriminator: boolean): CteSefazSeg {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'infSeg': CteSefazInfSegFromJSON(json['infSeg']),
        'nApol': json['nApol'],
        'nAver': json['nAver'],
    };
}

export function CteSefazSegToJSON(value?: CteSefazSeg | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'infSeg': CteSefazInfSegToJSON(value.infSeg),
        'nApol': value.nApol,
        'nAver': value.nAver,
    };
}

