/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CteSefazEmiOcc } from './CteSefazEmiOcc';
import {
    CteSefazEmiOccFromJSON,
    CteSefazEmiOccFromJSONTyped,
    CteSefazEmiOccToJSON,
} from './CteSefazEmiOcc';

/**
 * Ordens de Coleta associados.
 * @export
 * @interface CteSefazOcc
 */
export interface CteSefazOcc {
    /**
     * Série da OCC.
     * @type {string}
     * @memberof CteSefazOcc
     */
    serie?: string | null;
    /**
     * Número da Ordem de coleta.
     * @type {number}
     * @memberof CteSefazOcc
     */
    nOcc: number | null;
    /**
     * Data de emissão da ordem de coleta.
     * Formato AAAA-MM-DD.
     * @type {Date}
     * @memberof CteSefazOcc
     */
    dEmi: Date | null;
    /**
     * 
     * @type {CteSefazEmiOcc}
     * @memberof CteSefazOcc
     */
    emiOcc?: CteSefazEmiOcc;
}

/**
 * Check if a given object implements the CteSefazOcc interface.
 */
export function instanceOfCteSefazOcc(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "nOcc" in value;
    isInstance = isInstance && "dEmi" in value;

    return isInstance;
}

export function CteSefazOccFromJSON(json: any): CteSefazOcc {
    return CteSefazOccFromJSONTyped(json, false);
}

export function CteSefazOccFromJSONTyped(json: any, ignoreDiscriminator: boolean): CteSefazOcc {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'serie': !exists(json, 'serie') ? undefined : json['serie'],
        'nOcc': json['nOcc'],
        'dEmi': (json['dEmi'] === null ? null : new Date(json['dEmi'])),
        'emiOcc': !exists(json, 'emiOcc') ? undefined : CteSefazEmiOccFromJSON(json['emiOcc']),
    };
}

export function CteSefazOccToJSON(value?: CteSefazOcc | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'serie': value.serie,
        'nOcc': value.nOcc,
        'dEmi': (value.dEmi === null ? null : value.dEmi.toISOString().substr(0,10)),
        'emiOcc': CteSefazEmiOccToJSON(value.emiOcc),
    };
}

