/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CteSefazEndereco } from './CteSefazEndereco';
import {
    CteSefazEnderecoFromJSON,
    CteSefazEnderecoFromJSONTyped,
    CteSefazEnderecoToJSON,
} from './CteSefazEndereco';

/**
 * Informações do Recebedor da Carga.
 * @export
 * @interface CteSefazReceb
 */
export interface CteSefazReceb {
    /**
     * Número do CNPJ.
     * Em caso de empresa não estabelecida no Brasil, será informado o CNPJ com zeros.
     * Informar os zeros não significativos.
     * @type {string}
     * @memberof CteSefazReceb
     */
    CNPJ?: string | null;
    /**
     * Número do CPF.
     * Informar os zeros não significativos.
     * @type {string}
     * @memberof CteSefazReceb
     */
    CPF?: string | null;
    /**
     * Inscrição Estadual.
     * Informar a IE do recebedor ou ISENTO se recebedor é contribuinte do ICMS isento de inscrição no cadastro de contribuintes do ICMS. Caso o recebedor não seja contribuinte do ICMS não informar o conteúdo.
     * @type {string}
     * @memberof CteSefazReceb
     */
    IE?: string | null;
    /**
     * Razão Social ou Nome.
     * @type {string}
     * @memberof CteSefazReceb
     */
    xNome: string | null;
    /**
     * Telefone.
     * @type {string}
     * @memberof CteSefazReceb
     */
    fone?: string | null;
    /**
     * 
     * @type {CteSefazEndereco}
     * @memberof CteSefazReceb
     */
    enderReceb: CteSefazEndereco;
    /**
     * Endereço de email.
     * @type {string}
     * @memberof CteSefazReceb
     */
    email?: string | null;
}

/**
 * Check if a given object implements the CteSefazReceb interface.
 */
export function instanceOfCteSefazReceb(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "xNome" in value;
    isInstance = isInstance && "enderReceb" in value;

    return isInstance;
}

export function CteSefazRecebFromJSON(json: any): CteSefazReceb {
    return CteSefazRecebFromJSONTyped(json, false);
}

export function CteSefazRecebFromJSONTyped(json: any, ignoreDiscriminator: boolean): CteSefazReceb {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'CNPJ': !exists(json, 'CNPJ') ? undefined : json['CNPJ'],
        'CPF': !exists(json, 'CPF') ? undefined : json['CPF'],
        'IE': !exists(json, 'IE') ? undefined : json['IE'],
        'xNome': json['xNome'],
        'fone': !exists(json, 'fone') ? undefined : json['fone'],
        'enderReceb': CteSefazEnderecoFromJSON(json['enderReceb']),
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function CteSefazRecebToJSON(value?: CteSefazReceb | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'CNPJ': value.CNPJ,
        'CPF': value.CPF,
        'IE': value.IE,
        'xNome': value.xNome,
        'fone': value.fone,
        'enderReceb': CteSefazEnderecoToJSON(value.enderReceb),
        'email': value.email,
    };
}

