/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Autorizados para acessar o XML da DCe.
 * Informar CNPJ ou CPF. Preencher os zeros não significativos.
 * @export
 * @interface DceSefazAutXML
 */
export interface DceSefazAutXML {
    /**
     * CNPJ do autorizado.
     * Informar zeros não significativos.
     * @type {string}
     * @memberof DceSefazAutXML
     */
    CNPJ?: string | null;
    /**
     * CPF do autorizado.
     * Informar zeros não significativos.
     * @type {string}
     * @memberof DceSefazAutXML
     */
    CPF?: string | null;
}

/**
 * Check if a given object implements the DceSefazAutXML interface.
 */
export function instanceOfDceSefazAutXML(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DceSefazAutXMLFromJSON(json: any): DceSefazAutXML {
    return DceSefazAutXMLFromJSONTyped(json, false);
}

export function DceSefazAutXMLFromJSONTyped(json: any, ignoreDiscriminator: boolean): DceSefazAutXML {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'CNPJ': !exists(json, 'CNPJ') ? undefined : json['CNPJ'],
        'CPF': !exists(json, 'CPF') ? undefined : json['CPF'],
    };
}

export function DceSefazAutXMLToJSON(value?: DceSefazAutXML | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'CNPJ': value.CNPJ,
        'CPF': value.CPF,
    };
}

