/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DceSefazAutXML } from './DceSefazAutXML';
import {
    DceSefazAutXMLFromJSON,
    DceSefazAutXMLFromJSONTyped,
    DceSefazAutXMLToJSON,
} from './DceSefazAutXML';
import type { DceSefazDest } from './DceSefazDest';
import {
    DceSefazDestFromJSON,
    DceSefazDestFromJSONTyped,
    DceSefazDestToJSON,
} from './DceSefazDest';
import type { DceSefazDet } from './DceSefazDet';
import {
    DceSefazDetFromJSON,
    DceSefazDetFromJSONTyped,
    DceSefazDetToJSON,
} from './DceSefazDet';
import type { DceSefazECT } from './DceSefazECT';
import {
    DceSefazECTFromJSON,
    DceSefazECTFromJSONTyped,
    DceSefazECTToJSON,
} from './DceSefazECT';
import type { DceSefazEmit } from './DceSefazEmit';
import {
    DceSefazEmitFromJSON,
    DceSefazEmitFromJSONTyped,
    DceSefazEmitToJSON,
} from './DceSefazEmit';
import type { DceSefazFisco } from './DceSefazFisco';
import {
    DceSefazFiscoFromJSON,
    DceSefazFiscoFromJSONTyped,
    DceSefazFiscoToJSON,
} from './DceSefazFisco';
import type { DceSefazIde } from './DceSefazIde';
import {
    DceSefazIdeFromJSON,
    DceSefazIdeFromJSONTyped,
    DceSefazIdeToJSON,
} from './DceSefazIde';
import type { DceSefazInfAdic } from './DceSefazInfAdic';
import {
    DceSefazInfAdicFromJSON,
    DceSefazInfAdicFromJSONTyped,
    DceSefazInfAdicToJSON,
} from './DceSefazInfAdic';
import type { DceSefazInfDec } from './DceSefazInfDec';
import {
    DceSefazInfDecFromJSON,
    DceSefazInfDecFromJSONTyped,
    DceSefazInfDecToJSON,
} from './DceSefazInfDec';
import type { DceSefazMarketplace } from './DceSefazMarketplace';
import {
    DceSefazMarketplaceFromJSON,
    DceSefazMarketplaceFromJSONTyped,
    DceSefazMarketplaceToJSON,
} from './DceSefazMarketplace';
import type { DceSefazTotal } from './DceSefazTotal';
import {
    DceSefazTotalFromJSON,
    DceSefazTotalFromJSONTyped,
    DceSefazTotalToJSON,
} from './DceSefazTotal';
import type { DceSefazTransp } from './DceSefazTransp';
import {
    DceSefazTranspFromJSON,
    DceSefazTranspFromJSONTyped,
    DceSefazTranspToJSON,
} from './DceSefazTransp';
import type { DceSefazTransportadora } from './DceSefazTransportadora';
import {
    DceSefazTransportadoraFromJSON,
    DceSefazTransportadoraFromJSONTyped,
    DceSefazTransportadoraToJSON,
} from './DceSefazTransportadora';

/**
 * Informações da DCe.
 * @export
 * @interface DceSefazInfDCe
 */
export interface DceSefazInfDCe {
    /**
     * Versão do leiaute.
     * @type {string}
     * @memberof DceSefazInfDCe
     */
    versao: string | null;
    /**
     * Identificador da tag a ser assinada.
     * Informar a chave de acesso precedida do literal "DCe".
     * 
     * *Geramos automaticamente quando nenhum valor é informado.*
     * @type {string}
     * @memberof DceSefazInfDCe
     */
    Id?: string | null;
    /**
     * 
     * @type {DceSefazIde}
     * @memberof DceSefazInfDCe
     */
    ide: DceSefazIde;
    /**
     * 
     * @type {DceSefazEmit}
     * @memberof DceSefazInfDCe
     */
    emit: DceSefazEmit;
    /**
     * 
     * @type {DceSefazFisco}
     * @memberof DceSefazInfDCe
     */
    Fisco?: DceSefazFisco;
    /**
     * 
     * @type {DceSefazMarketplace}
     * @memberof DceSefazInfDCe
     */
    Marketplace?: DceSefazMarketplace;
    /**
     * 
     * @type {DceSefazTransportadora}
     * @memberof DceSefazInfDCe
     */
    Transportadora?: DceSefazTransportadora;
    /**
     * 
     * @type {DceSefazECT}
     * @memberof DceSefazInfDCe
     */
    ECT?: DceSefazECT;
    /**
     * 
     * @type {DceSefazDest}
     * @memberof DceSefazInfDCe
     */
    dest: DceSefazDest;
    /**
     * 
     * @type {Array<DceSefazAutXML>}
     * @memberof DceSefazInfDCe
     */
    autXML?: Array<DceSefazAutXML>;
    /**
     * 
     * @type {Array<DceSefazDet>}
     * @memberof DceSefazInfDCe
     */
    det: Array<DceSefazDet>;
    /**
     * 
     * @type {DceSefazTotal}
     * @memberof DceSefazInfDCe
     */
    total: DceSefazTotal;
    /**
     * 
     * @type {DceSefazTransp}
     * @memberof DceSefazInfDCe
     */
    transp: DceSefazTransp;
    /**
     * 
     * @type {DceSefazInfAdic}
     * @memberof DceSefazInfDCe
     */
    infAdic?: DceSefazInfAdic;
    /**
     * 
     * @type {DceSefazInfDec}
     * @memberof DceSefazInfDCe
     */
    infDec?: DceSefazInfDec;
}

/**
 * Check if a given object implements the DceSefazInfDCe interface.
 */
export function instanceOfDceSefazInfDCe(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "versao" in value;
    isInstance = isInstance && "ide" in value;
    isInstance = isInstance && "emit" in value;
    isInstance = isInstance && "dest" in value;
    isInstance = isInstance && "det" in value;
    isInstance = isInstance && "total" in value;
    isInstance = isInstance && "transp" in value;

    return isInstance;
}

export function DceSefazInfDCeFromJSON(json: any): DceSefazInfDCe {
    return DceSefazInfDCeFromJSONTyped(json, false);
}

export function DceSefazInfDCeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DceSefazInfDCe {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'versao': json['versao'],
        'Id': !exists(json, 'Id') ? undefined : json['Id'],
        'ide': DceSefazIdeFromJSON(json['ide']),
        'emit': DceSefazEmitFromJSON(json['emit']),
        'Fisco': !exists(json, 'Fisco') ? undefined : DceSefazFiscoFromJSON(json['Fisco']),
        'Marketplace': !exists(json, 'Marketplace') ? undefined : DceSefazMarketplaceFromJSON(json['Marketplace']),
        'Transportadora': !exists(json, 'Transportadora') ? undefined : DceSefazTransportadoraFromJSON(json['Transportadora']),
        'ECT': !exists(json, 'ECT') ? undefined : DceSefazECTFromJSON(json['ECT']),
        'dest': DceSefazDestFromJSON(json['dest']),
        'autXML': !exists(json, 'autXML') ? undefined : ((json['autXML'] as Array<any>).map(DceSefazAutXMLFromJSON)),
        'det': ((json['det'] as Array<any>).map(DceSefazDetFromJSON)),
        'total': DceSefazTotalFromJSON(json['total']),
        'transp': DceSefazTranspFromJSON(json['transp']),
        'infAdic': !exists(json, 'infAdic') ? undefined : DceSefazInfAdicFromJSON(json['infAdic']),
        'infDec': !exists(json, 'infDec') ? undefined : DceSefazInfDecFromJSON(json['infDec']),
    };
}

export function DceSefazInfDCeToJSON(value?: DceSefazInfDCe | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'versao': value.versao,
        'Id': value.Id,
        'ide': DceSefazIdeToJSON(value.ide),
        'emit': DceSefazEmitToJSON(value.emit),
        'Fisco': DceSefazFiscoToJSON(value.Fisco),
        'Marketplace': DceSefazMarketplaceToJSON(value.Marketplace),
        'Transportadora': DceSefazTransportadoraToJSON(value.Transportadora),
        'ECT': DceSefazECTToJSON(value.ECT),
        'dest': DceSefazDestToJSON(value.dest),
        'autXML': value.autXML === undefined ? undefined : ((value.autXML as Array<any>).map(DceSefazAutXMLToJSON)),
        'det': ((value.det as Array<any>).map(DceSefazDetToJSON)),
        'total': DceSefazTotalToJSON(value.total),
        'transp': DceSefazTranspToJSON(value.transp),
        'infAdic': DceSefazInfAdicToJSON(value.infAdic),
        'infDec': DceSefazInfDecToJSON(value.infDec),
    };
}

