/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Endereço do destinatário / assinante.
 * @export
 * @interface DceSefazEndeDest
 */
export interface DceSefazEndeDest {
    /**
     * Logradouro.
     * @type {string}
     * @memberof DceSefazEndeDest
     */
    xLgr: string | null;
    /**
     * Número.
     * @type {string}
     * @memberof DceSefazEndeDest
     */
    nro: string | null;
    /**
     * Complemento.
     * @type {string}
     * @memberof DceSefazEndeDest
     */
    xCpl?: string | null;
    /**
     * Bairro.
     * @type {string}
     * @memberof DceSefazEndeDest
     */
    xBairro: string | null;
    /**
     * Código do município (utilizar a tabela do IBGE).
     * @type {string}
     * @memberof DceSefazEndeDest
     */
    cMun: string | null;
    /**
     * Nome do município.
     * @type {string}
     * @memberof DceSefazEndeDest
     */
    xMun: string | null;
    /**
     * Sigla da UF.
     * @type {string}
     * @memberof DceSefazEndeDest
     */
    UF: string | null;
    /**
     * CEP.
     * Informar zeros não significativos.
     * @type {string}
     * @memberof DceSefazEndeDest
     */
    CEP: string | null;
    /**
     * Código do país.
     * Utilizar a tabela do BACEN.
     * @type {string}
     * @memberof DceSefazEndeDest
     */
    cPais: string | null;
    /**
     * Nome do país.
     * @type {string}
     * @memberof DceSefazEndeDest
     */
    xPais: string | null;
    /**
     * Telefone.
     * @type {string}
     * @memberof DceSefazEndeDest
     */
    fone?: string | null;
    /**
     * Endereço de E-mail.
     * @type {string}
     * @memberof DceSefazEndeDest
     */
    email?: string | null;
}

/**
 * Check if a given object implements the DceSefazEndeDest interface.
 */
export function instanceOfDceSefazEndeDest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "xLgr" in value;
    isInstance = isInstance && "nro" in value;
    isInstance = isInstance && "xBairro" in value;
    isInstance = isInstance && "cMun" in value;
    isInstance = isInstance && "xMun" in value;
    isInstance = isInstance && "UF" in value;
    isInstance = isInstance && "CEP" in value;
    isInstance = isInstance && "cPais" in value;
    isInstance = isInstance && "xPais" in value;

    return isInstance;
}

export function DceSefazEndeDestFromJSON(json: any): DceSefazEndeDest {
    return DceSefazEndeDestFromJSONTyped(json, false);
}

export function DceSefazEndeDestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DceSefazEndeDest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'xLgr': json['xLgr'],
        'nro': json['nro'],
        'xCpl': !exists(json, 'xCpl') ? undefined : json['xCpl'],
        'xBairro': json['xBairro'],
        'cMun': json['cMun'],
        'xMun': json['xMun'],
        'UF': json['UF'],
        'CEP': json['CEP'],
        'cPais': json['cPais'],
        'xPais': json['xPais'],
        'fone': !exists(json, 'fone') ? undefined : json['fone'],
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function DceSefazEndeDestToJSON(value?: DceSefazEndeDest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'xLgr': value.xLgr,
        'nro': value.nro,
        'xCpl': value.xCpl,
        'xBairro': value.xBairro,
        'cMun': value.cMun,
        'xMun': value.xMun,
        'UF': value.UF,
        'CEP': value.CEP,
        'cPais': value.cPais,
        'xPais': value.xPais,
        'fone': value.fone,
        'email': value.email,
    };
}

