/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DfeContribuinteEndereco } from './DfeContribuinteEndereco';
import {
    DfeContribuinteEnderecoFromJSON,
    DfeContribuinteEnderecoFromJSONTyped,
    DfeContribuinteEnderecoToJSON,
} from './DfeContribuinteEndereco';

/**
 * Informações cadastrais do contribuinte consultado.
 * @export
 * @interface DfeContribuinteInfCad
 */
export interface DfeContribuinteInfCad {
    /**
     * Número da Inscrição Estadual do contribuinte.
     * @type {string}
     * @memberof DfeContribuinteInfCad
     */
    ie: string | null;
    /**
     * Número do CNPJ  do contribuinte.
     * @type {string}
     * @memberof DfeContribuinteInfCad
     */
    cnpj?: string | null;
    /**
     * Número do CPF do contribuinte.
     * @type {string}
     * @memberof DfeContribuinteInfCad
     */
    cpf?: string | null;
    /**
     * Sigla da UF de localização do contribuinte. Em algumas situações, a UF de localização pode ser diferente da UF consultada. Ex. IE de Substituto Tributário.
     * @type {string}
     * @memberof DfeContribuinteInfCad
     */
    uf: string | null;
    /**
     * Situação cadastral do contribuinte:
     * * 0 - não habilitado
     * * 1 - habilitado
     * @type {number}
     * @memberof DfeContribuinteInfCad
     */
    situacao_cadastral: number | null;
    /**
     * Indicador de contribuinte credenciado a emitir NF-e.
     * * 0 - Não credenciado para emissão da NF-e
     * * 1 - Credenciado
     * * 2 - Credenciado com obrigatoriedade para todas operações
     * * 3 - Credenciado com obrigatoriedade parcial
     * * 4 - a SEFAZ não fornece a informação
     * Este indicador significa apenas que o contribuinte é credenciado para emitir NF-e na SEFAZ consultada.
     * @type {number}
     * @memberof DfeContribuinteInfCad
     */
    indicador_nfe: number | null;
    /**
     * Indicador de contribuinte credenciado a emitir CT-e.
     * * 0 - Não credenciado para emissão da CT-e
     * * 1 - Credenciado
     * * 2 - Credenciado com obrigatoriedade para todas operações
     * * 3 - Credenciado com obrigatoriedade parcial
     * * 4 - a SEFAZ não fornece a informação
     * Este indicador significa apenas que o contribuinte é credenciado para emitir CT-e na SEFAZ consultada.
     * @type {number}
     * @memberof DfeContribuinteInfCad
     */
    indicador_cte: number | null;
    /**
     * Razão Social ou nome do contribuinte.
     * @type {string}
     * @memberof DfeContribuinteInfCad
     */
    nome_razao_social: string | null;
    /**
     * Razão Social ou nome do contribuinte.
     * @type {string}
     * @memberof DfeContribuinteInfCad
     */
    nome_fantasia?: string | null;
    /**
     * Regime de Apuração do ICMS.
     * @type {string}
     * @memberof DfeContribuinteInfCad
     */
    regime_apuracao_icms?: string | null;
    /**
     * CNAE Fiscal do contribuinte.
     * @type {string}
     * @memberof DfeContribuinteInfCad
     */
    cnae?: string | null;
    /**
     * Data de início de atividades do contribuinte.
     * @type {Date}
     * @memberof DfeContribuinteInfCad
     */
    data_inicio_atividade?: Date | null;
    /**
     * Data da última modificação da situação cadastral do contribuinte.
     * @type {Date}
     * @memberof DfeContribuinteInfCad
     */
    data_situacao_cadastral?: Date | null;
    /**
     * Data de ocorrência da baixa do contribuinte.
     * @type {Date}
     * @memberof DfeContribuinteInfCad
     */
    data_fim_atividade?: Date | null;
    /**
     * Inscrição Estadual Única.
     * @type {string}
     * @memberof DfeContribuinteInfCad
     */
    ie_unica?: string | null;
    /**
     * Inscrição Estadual atual.
     * @type {string}
     * @memberof DfeContribuinteInfCad
     */
    ie_atual?: string | null;
    /**
     * 
     * @type {DfeContribuinteEndereco}
     * @memberof DfeContribuinteInfCad
     */
    endereco?: DfeContribuinteEndereco;
}

/**
 * Check if a given object implements the DfeContribuinteInfCad interface.
 */
export function instanceOfDfeContribuinteInfCad(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "ie" in value;
    isInstance = isInstance && "uf" in value;
    isInstance = isInstance && "situacao_cadastral" in value;
    isInstance = isInstance && "indicador_nfe" in value;
    isInstance = isInstance && "indicador_cte" in value;
    isInstance = isInstance && "nome_razao_social" in value;

    return isInstance;
}

export function DfeContribuinteInfCadFromJSON(json: any): DfeContribuinteInfCad {
    return DfeContribuinteInfCadFromJSONTyped(json, false);
}

export function DfeContribuinteInfCadFromJSONTyped(json: any, ignoreDiscriminator: boolean): DfeContribuinteInfCad {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ie': json['ie'],
        'cnpj': !exists(json, 'cnpj') ? undefined : json['cnpj'],
        'cpf': !exists(json, 'cpf') ? undefined : json['cpf'],
        'uf': json['uf'],
        'situacao_cadastral': json['situacao_cadastral'],
        'indicador_nfe': json['indicador_nfe'],
        'indicador_cte': json['indicador_cte'],
        'nome_razao_social': json['nome_razao_social'],
        'nome_fantasia': !exists(json, 'nome_fantasia') ? undefined : json['nome_fantasia'],
        'regime_apuracao_icms': !exists(json, 'regime_apuracao_icms') ? undefined : json['regime_apuracao_icms'],
        'cnae': !exists(json, 'cnae') ? undefined : json['cnae'],
        'data_inicio_atividade': !exists(json, 'data_inicio_atividade') ? undefined : (json['data_inicio_atividade'] === null ? null : new Date(json['data_inicio_atividade'])),
        'data_situacao_cadastral': !exists(json, 'data_situacao_cadastral') ? undefined : (json['data_situacao_cadastral'] === null ? null : new Date(json['data_situacao_cadastral'])),
        'data_fim_atividade': !exists(json, 'data_fim_atividade') ? undefined : (json['data_fim_atividade'] === null ? null : new Date(json['data_fim_atividade'])),
        'ie_unica': !exists(json, 'ie_unica') ? undefined : json['ie_unica'],
        'ie_atual': !exists(json, 'ie_atual') ? undefined : json['ie_atual'],
        'endereco': !exists(json, 'endereco') ? undefined : DfeContribuinteEnderecoFromJSON(json['endereco']),
    };
}

export function DfeContribuinteInfCadToJSON(value?: DfeContribuinteInfCad | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ie': value.ie,
        'cnpj': value.cnpj,
        'cpf': value.cpf,
        'uf': value.uf,
        'situacao_cadastral': value.situacao_cadastral,
        'indicador_nfe': value.indicador_nfe,
        'indicador_cte': value.indicador_cte,
        'nome_razao_social': value.nome_razao_social,
        'nome_fantasia': value.nome_fantasia,
        'regime_apuracao_icms': value.regime_apuracao_icms,
        'cnae': value.cnae,
        'data_inicio_atividade': value.data_inicio_atividade === undefined ? undefined : (value.data_inicio_atividade === null ? null : value.data_inicio_atividade.toISOString().substr(0,10)),
        'data_situacao_cadastral': value.data_situacao_cadastral === undefined ? undefined : (value.data_situacao_cadastral === null ? null : value.data_situacao_cadastral.toISOString().substr(0,10)),
        'data_fim_atividade': value.data_fim_atividade === undefined ? undefined : (value.data_fim_atividade === null ? null : value.data_fim_atividade.toISOString().substr(0,10)),
        'ie_unica': value.ie_unica,
        'ie_atual': value.ie_atual,
        'endereco': DfeContribuinteEnderecoToJSON(value.endereco),
    };
}

