/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DfeAutorEvento } from './DfeAutorEvento';
import {
    DfeAutorEventoFromJSON,
    DfeAutorEventoFromJSONTyped,
    DfeAutorEventoToJSON,
} from './DfeAutorEvento';

/**
 * 
 * @export
 * @interface DfeCancelamento
 */
export interface DfeCancelamento {
    /**
     * Justificativa do cancelamento.
     * @type {string}
     * @memberof DfeCancelamento
     */
    justificativa?: string;
    /**
     * ID único gerado pela API para este evento.
     * @type {string}
     * @memberof DfeCancelamento
     */
    id?: string;
    /**
     * Identificação do ambiente.
     * @type {string}
     * @memberof DfeCancelamento
     */
    ambiente?: DfeCancelamentoAmbienteEnum;
    /**
     * Status do Evento.
     * @type {string}
     * @memberof DfeCancelamento
     */
    status?: DfeCancelamentoStatusEnum;
    /**
     * 
     * @type {DfeAutorEvento}
     * @memberof DfeCancelamento
     */
    autor?: DfeAutorEvento;
    /**
     * Chave de Acesso do documento vinculado ao evento.
     * @type {string}
     * @memberof DfeCancelamento
     */
    chave_acesso?: string;
    /**
     * Data e hora do Evento.
     * @type {Date}
     * @memberof DfeCancelamento
     */
    data_evento?: Date;
    /**
     * Sequencial do evento para o mesmo tipo de evento.
     * @type {number}
     * @memberof DfeCancelamento
     */
    numero_sequencial?: number;
    /**
     * Data e hora do recebimento do Evento pela SEFAZ.
     * @type {Date}
     * @memberof DfeCancelamento
     */
    data_recebimento?: Date | null;
    /**
     * Código do status de registro do Evento.
     * @type {number}
     * @memberof DfeCancelamento
     */
    codigo_status?: number;
    /**
     * Descrição literal do status do registro do Evento.
     * @type {string}
     * @memberof DfeCancelamento
     */
    motivo_status?: string;
    /**
     * Número do Protocolo de registro do Evento.
     * @type {string}
     * @memberof DfeCancelamento
     */
    numero_protocolo?: string;
    /**
     * Código da Mensagem.
     * @type {number}
     * @memberof DfeCancelamento
     */
    codigo_mensagem?: number;
    /**
     * Mensagem da SEFAZ para o emissor.
     * @type {string}
     * @memberof DfeCancelamento
     */
    mensagem?: string;
    /**
     * 
     * @type {string}
     * @memberof DfeCancelamento
     */
    tipo_evento?: string;
}


/**
 * @export
 */
export const DfeCancelamentoAmbienteEnum = {
    Homologacao: 'homologacao',
    Producao: 'producao'
} as const;
export type DfeCancelamentoAmbienteEnum = typeof DfeCancelamentoAmbienteEnum[keyof typeof DfeCancelamentoAmbienteEnum];

/**
 * @export
 */
export const DfeCancelamentoStatusEnum = {
    Pendente: 'pendente',
    Registrado: 'registrado',
    Rejeitado: 'rejeitado',
    Erro: 'erro'
} as const;
export type DfeCancelamentoStatusEnum = typeof DfeCancelamentoStatusEnum[keyof typeof DfeCancelamentoStatusEnum];


/**
 * Check if a given object implements the DfeCancelamento interface.
 */
export function instanceOfDfeCancelamento(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DfeCancelamentoFromJSON(json: any): DfeCancelamento {
    return DfeCancelamentoFromJSONTyped(json, false);
}

export function DfeCancelamentoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DfeCancelamento {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'justificativa': !exists(json, 'justificativa') ? undefined : json['justificativa'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'ambiente': !exists(json, 'ambiente') ? undefined : json['ambiente'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'autor': !exists(json, 'autor') ? undefined : DfeAutorEventoFromJSON(json['autor']),
        'chave_acesso': !exists(json, 'chave_acesso') ? undefined : json['chave_acesso'],
        'data_evento': !exists(json, 'data_evento') ? undefined : (new Date(json['data_evento'])),
        'numero_sequencial': !exists(json, 'numero_sequencial') ? undefined : json['numero_sequencial'],
        'data_recebimento': !exists(json, 'data_recebimento') ? undefined : (json['data_recebimento'] === null ? null : new Date(json['data_recebimento'])),
        'codigo_status': !exists(json, 'codigo_status') ? undefined : json['codigo_status'],
        'motivo_status': !exists(json, 'motivo_status') ? undefined : json['motivo_status'],
        'numero_protocolo': !exists(json, 'numero_protocolo') ? undefined : json['numero_protocolo'],
        'codigo_mensagem': !exists(json, 'codigo_mensagem') ? undefined : json['codigo_mensagem'],
        'mensagem': !exists(json, 'mensagem') ? undefined : json['mensagem'],
        'tipo_evento': !exists(json, 'tipo_evento') ? undefined : json['tipo_evento'],
    };
}

export function DfeCancelamentoToJSON(value?: DfeCancelamento | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'justificativa': value.justificativa,
        'id': value.id,
        'ambiente': value.ambiente,
        'status': value.status,
        'autor': DfeAutorEventoToJSON(value.autor),
        'chave_acesso': value.chave_acesso,
        'data_evento': value.data_evento === undefined ? undefined : (value.data_evento.toISOString()),
        'numero_sequencial': value.numero_sequencial,
        'data_recebimento': value.data_recebimento === undefined ? undefined : (value.data_recebimento === null ? null : value.data_recebimento.toISOString()),
        'codigo_status': value.codigo_status,
        'motivo_status': value.motivo_status,
        'numero_protocolo': value.numero_protocolo,
        'codigo_mensagem': value.codigo_mensagem,
        'mensagem': value.mensagem,
        'tipo_evento': value.tipo_evento,
    };
}

