/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DfeRequisicaoDebug } from './DfeRequisicaoDebug';
import {
    DfeRequisicaoDebugFromJSON,
    DfeRequisicaoDebugFromJSONTyped,
    DfeRequisicaoDebugToJSON,
} from './DfeRequisicaoDebug';

/**
 * 
 * @export
 * @interface DfeDebug
 */
export interface DfeDebug {
    /**
     * Identificador do documento fiscal.
     * @type {string}
     * @memberof DfeDebug
     */
    id?: string;
    /**
     * Tipo do documento: nfe, nfce, mdfe, nfse, etc.
     * @type {string}
     * @memberof DfeDebug
     */
    tipo?: string;
    /**
     * Data e hora da criação do documento, representada no formato UTC (Tempo Universal Coordenado).
     * O valor é retornado no padrão ISO 8601, incluindo o deslocamento de fuso horário 'Z' no final.
     * 
     * Exemplo: "2025-04-15T14:16:47.775Z"
     * @type {Date}
     * @memberof DfeDebug
     */
    created_at?: Date;
    /**
     * Lista de requisições feitas ao autorizador durante o processamento.
     * @type {Array<DfeRequisicaoDebug>}
     * @memberof DfeDebug
     */
    requisicoes?: Array<DfeRequisicaoDebug>;
}

/**
 * Check if a given object implements the DfeDebug interface.
 */
export function instanceOfDfeDebug(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DfeDebugFromJSON(json: any): DfeDebug {
    return DfeDebugFromJSONTyped(json, false);
}

export function DfeDebugFromJSONTyped(json: any, ignoreDiscriminator: boolean): DfeDebug {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'tipo': !exists(json, 'tipo') ? undefined : json['tipo'],
        'created_at': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'requisicoes': !exists(json, 'requisicoes') ? undefined : ((json['requisicoes'] as Array<any>).map(DfeRequisicaoDebugFromJSON)),
    };
}

export function DfeDebugToJSON(value?: DfeDebug | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'tipo': value.tipo,
        'created_at': value.created_at === undefined ? undefined : (value.created_at.toISOString()),
        'requisicoes': value.requisicoes === undefined ? undefined : ((value.requisicoes as Array<any>).map(DfeRequisicaoDebugToJSON)),
    };
}

