/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DistribuicaoNfeNota
 */
export interface DistribuicaoNfeNota {
    /**
     * Chave de Acesso da NF-e.
     * @type {string}
     * @memberof DistribuicaoNfeNota
     */
    chave_acesso?: string | null;
    /**
     * Número do protocolo de autorização.
     * @type {string}
     * @memberof DistribuicaoNfeNota
     */
    numero_protocolo?: string | null;
    /**
     * Tipo da NF-e (0 - entrada; 1 - saída).
     * @type {number}
     * @memberof DistribuicaoNfeNota
     */
    tipo_nfe?: number | null;
    /**
     * Data e hora da emissão do documento fiscal.
     * @type {Date}
     * @memberof DistribuicaoNfeNota
     */
    data_emissao?: Date | null;
    /**
     * Valor total da NF-e.
     * @type {number}
     * @memberof DistribuicaoNfeNota
     */
    valor_nfe?: number | null;
    /**
     * Digest Value da NF-e processada. Utilizado para conferir a integridade da NF-e original.
     * @type {string}
     * @memberof DistribuicaoNfeNota
     */
    digest_value?: string | null;
    /**
     * CPF/CNPJ do emitente.
     * @type {string}
     * @memberof DistribuicaoNfeNota
     */
    emitente_cpf_cnpj?: string | null;
    /**
     * Nome ou Razão Social do emitente.
     * @type {string}
     * @memberof DistribuicaoNfeNota
     */
    emitente_nome_razao_social?: string | null;
    /**
     * Inscrição Estadual do emitente.
     * @type {string}
     * @memberof DistribuicaoNfeNota
     */
    emitente_inscricao_estadual?: string | null;
}

/**
 * Check if a given object implements the DistribuicaoNfeNota interface.
 */
export function instanceOfDistribuicaoNfeNota(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DistribuicaoNfeNotaFromJSON(json: any): DistribuicaoNfeNota {
    return DistribuicaoNfeNotaFromJSONTyped(json, false);
}

export function DistribuicaoNfeNotaFromJSONTyped(json: any, ignoreDiscriminator: boolean): DistribuicaoNfeNota {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'chave_acesso': !exists(json, 'chave_acesso') ? undefined : json['chave_acesso'],
        'numero_protocolo': !exists(json, 'numero_protocolo') ? undefined : json['numero_protocolo'],
        'tipo_nfe': !exists(json, 'tipo_nfe') ? undefined : json['tipo_nfe'],
        'data_emissao': !exists(json, 'data_emissao') ? undefined : (json['data_emissao'] === null ? null : new Date(json['data_emissao'])),
        'valor_nfe': !exists(json, 'valor_nfe') ? undefined : json['valor_nfe'],
        'digest_value': !exists(json, 'digest_value') ? undefined : json['digest_value'],
        'emitente_cpf_cnpj': !exists(json, 'emitente_cpf_cnpj') ? undefined : json['emitente_cpf_cnpj'],
        'emitente_nome_razao_social': !exists(json, 'emitente_nome_razao_social') ? undefined : json['emitente_nome_razao_social'],
        'emitente_inscricao_estadual': !exists(json, 'emitente_inscricao_estadual') ? undefined : json['emitente_inscricao_estadual'],
    };
}

export function DistribuicaoNfeNotaToJSON(value?: DistribuicaoNfeNota | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'chave_acesso': value.chave_acesso,
        'numero_protocolo': value.numero_protocolo,
        'tipo_nfe': value.tipo_nfe,
        'data_emissao': value.data_emissao === undefined ? undefined : (value.data_emissao === null ? null : value.data_emissao.toISOString()),
        'valor_nfe': value.valor_nfe,
        'digest_value': value.digest_value,
        'emitente_cpf_cnpj': value.emitente_cpf_cnpj,
        'emitente_nome_razao_social': value.emitente_nome_razao_social,
        'emitente_inscricao_estadual': value.emitente_inscricao_estadual,
    };
}

