/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DistribuicaoNfeNota } from './DistribuicaoNfeNota';
import {
    DistribuicaoNfeNotaFromJSON,
    DistribuicaoNfeNotaFromJSONTyped,
    DistribuicaoNfeNotaToJSON,
} from './DistribuicaoNfeNota';

/**
 * 
 * @export
 * @interface DistribuicaoNfeNotaListagem
 */
export interface DistribuicaoNfeNotaListagem {
    /**
     * 
     * @type {number}
     * @memberof DistribuicaoNfeNotaListagem
     */
    count?: number;
    /**
     * 
     * @type {Array<DistribuicaoNfeNota>}
     * @memberof DistribuicaoNfeNotaListagem
     */
    data?: Array<DistribuicaoNfeNota>;
}

/**
 * Check if a given object implements the DistribuicaoNfeNotaListagem interface.
 */
export function instanceOfDistribuicaoNfeNotaListagem(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DistribuicaoNfeNotaListagemFromJSON(json: any): DistribuicaoNfeNotaListagem {
    return DistribuicaoNfeNotaListagemFromJSONTyped(json, false);
}

export function DistribuicaoNfeNotaListagemFromJSONTyped(json: any, ignoreDiscriminator: boolean): DistribuicaoNfeNotaListagem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, '@count') ? undefined : json['@count'],
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(DistribuicaoNfeNotaFromJSON)),
    };
}

export function DistribuicaoNfeNotaListagemToJSON(value?: DistribuicaoNfeNotaListagem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '@count': value.count,
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(DistribuicaoNfeNotaToJSON)),
    };
}

