/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DistribuicaoNfePedidoManifestacao
 */
export interface DistribuicaoNfePedidoManifestacao {
    /**
     * CPF ou CNPJ do autor do evento.
     * 
     * *Utilize o valor sem máscara*.
     * @type {string}
     * @memberof DistribuicaoNfePedidoManifestacao
     */
    cpf_cnpj: string;
    /**
     * Identificação do Ambiente.
     * @type {string}
     * @memberof DistribuicaoNfePedidoManifestacao
     */
    ambiente: DistribuicaoNfePedidoManifestacaoAmbienteEnum;
    /**
     * Chave de Acesso da NF-e.
     * @type {string}
     * @memberof DistribuicaoNfePedidoManifestacao
     */
    chave_acesso: string;
    /**
     * Tipo do evento de manifestação do destinatário.
     * 
     * Valores disponíveis:
     * * `210200` - Confirmação da operação;
     * * `210210` - Ciência da operação;
     * * `210220` - Desconhecimento da operação;
     * * `210240` - Operação não realizada.
     * @type {string}
     * @memberof DistribuicaoNfePedidoManifestacao
     */
    tipo_evento: string;
    /**
     * Justificativa para o desconhecimento ou não-realização da operação.
     * 
     * **Nota**: Campo obrigatório para o evento `210240` (operação não realizada).
     * @type {string}
     * @memberof DistribuicaoNfePedidoManifestacao
     */
    justificativa?: string | null;
}


/**
 * @export
 */
export const DistribuicaoNfePedidoManifestacaoAmbienteEnum = {
    Homologacao: 'homologacao',
    Producao: 'producao'
} as const;
export type DistribuicaoNfePedidoManifestacaoAmbienteEnum = typeof DistribuicaoNfePedidoManifestacaoAmbienteEnum[keyof typeof DistribuicaoNfePedidoManifestacaoAmbienteEnum];


/**
 * Check if a given object implements the DistribuicaoNfePedidoManifestacao interface.
 */
export function instanceOfDistribuicaoNfePedidoManifestacao(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "cpf_cnpj" in value;
    isInstance = isInstance && "ambiente" in value;
    isInstance = isInstance && "chave_acesso" in value;
    isInstance = isInstance && "tipo_evento" in value;

    return isInstance;
}

export function DistribuicaoNfePedidoManifestacaoFromJSON(json: any): DistribuicaoNfePedidoManifestacao {
    return DistribuicaoNfePedidoManifestacaoFromJSONTyped(json, false);
}

export function DistribuicaoNfePedidoManifestacaoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DistribuicaoNfePedidoManifestacao {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cpf_cnpj': json['cpf_cnpj'],
        'ambiente': json['ambiente'],
        'chave_acesso': json['chave_acesso'],
        'tipo_evento': json['tipo_evento'],
        'justificativa': !exists(json, 'justificativa') ? undefined : json['justificativa'],
    };
}

export function DistribuicaoNfePedidoManifestacaoToJSON(value?: DistribuicaoNfePedidoManifestacao | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cpf_cnpj': value.cpf_cnpj,
        'ambiente': value.ambiente,
        'chave_acesso': value.chave_acesso,
        'tipo_evento': value.tipo_evento,
        'justificativa': value.justificativa,
    };
}

