/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EmailAttachment } from './EmailAttachment';
import {
    EmailAttachmentFromJSON,
    EmailAttachmentFromJSONTyped,
    EmailAttachmentToJSON,
} from './EmailAttachment';
import type { EmailEvent } from './EmailEvent';
import {
    EmailEventFromJSON,
    EmailEventFromJSONTyped,
    EmailEventToJSON,
} from './EmailEvent';

/**
 * 
 * @export
 * @interface Email
 */
export interface Email {
    /**
     * ID único gerado pela API para este email.
     * 
     * Utilize-o no endpoint de <a href="#tag/Email/operation/ConsultarEmail">consulta de email</a>
     * para obter informações detalhadas sobre o envio do email e
     * rastrear todos os eventos relacionados, como envio, entrega, falhas e outros
     * eventos relevantes.
     * @type {string}
     * @memberof Email
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Email
     */
    status?: EmailStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof Email
     */
    sent_at?: Date | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof Email
     */
    to?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Email
     */
    cc?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Email
     */
    reply_to?: string;
    /**
     * 
     * @type {string}
     * @memberof Email
     */
    subject?: string;
    /**
     * 
     * @type {Array<EmailAttachment>}
     * @memberof Email
     */
    attachments?: Array<EmailAttachment>;
    /**
     * 
     * @type {Array<EmailEvent>}
     * @memberof Email
     */
    events?: Array<EmailEvent>;
}


/**
 * @export
 */
export const EmailStatusEnum = {
    Pending: 'pending',
    Sending: 'sending',
    Sent: 'sent',
    Delivered: 'delivered',
    DeliveryDelayed: 'delivery_delayed',
    Bounced: 'bounced',
    Complained: 'complained',
    Rejected: 'rejected',
    Cancelled: 'cancelled',
    Failed: 'failed'
} as const;
export type EmailStatusEnum = typeof EmailStatusEnum[keyof typeof EmailStatusEnum];


/**
 * Check if a given object implements the Email interface.
 */
export function instanceOfEmail(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function EmailFromJSON(json: any): Email {
    return EmailFromJSONTyped(json, false);
}

export function EmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): Email {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'sent_at': !exists(json, 'sent_at') ? undefined : (json['sent_at'] === null ? null : new Date(json['sent_at'])),
        'to': !exists(json, 'to') ? undefined : json['to'],
        'cc': !exists(json, 'cc') ? undefined : json['cc'],
        'reply_to': !exists(json, 'reply_to') ? undefined : json['reply_to'],
        'subject': !exists(json, 'subject') ? undefined : json['subject'],
        'attachments': !exists(json, 'attachments') ? undefined : ((json['attachments'] as Array<any>).map(EmailAttachmentFromJSON)),
        'events': !exists(json, 'events') ? undefined : ((json['events'] as Array<any>).map(EmailEventFromJSON)),
    };
}

export function EmailToJSON(value?: Email | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'status': value.status,
        'sent_at': value.sent_at === undefined ? undefined : (value.sent_at === null ? null : value.sent_at.toISOString()),
        'to': value.to,
        'cc': value.cc,
        'reply_to': value.reply_to,
        'subject': value.subject,
        'attachments': value.attachments === undefined ? undefined : ((value.attachments as Array<any>).map(EmailAttachmentToJSON)),
        'events': value.events === undefined ? undefined : ((value.events as Array<any>).map(EmailEventToJSON)),
    };
}

