/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailStatusResponse
 */
export interface EmailStatusResponse {
    /**
     * ID único gerado pela API para este email.
     * 
     * Utilize-o no endpoint de <a href="#tag/Email/operation/ConsultarEmail">consulta de email</a>
     * para obter informações detalhadas sobre o envio do email e
     * rastrear todos os eventos relacionados, como envio, entrega, falhas e outros
     * eventos relevantes.
     * @type {string}
     * @memberof EmailStatusResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EmailStatusResponse
     */
    status?: EmailStatusResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof EmailStatusResponse
     */
    status_message?: string | null;
}


/**
 * @export
 */
export const EmailStatusResponseStatusEnum = {
    Pending: 'pending',
    Sending: 'sending',
    Sent: 'sent',
    Delivered: 'delivered',
    DeliveryDelayed: 'delivery_delayed',
    Bounced: 'bounced',
    Complained: 'complained',
    Rejected: 'rejected',
    Cancelled: 'cancelled',
    Failed: 'failed'
} as const;
export type EmailStatusResponseStatusEnum = typeof EmailStatusResponseStatusEnum[keyof typeof EmailStatusResponseStatusEnum];


/**
 * Check if a given object implements the EmailStatusResponse interface.
 */
export function instanceOfEmailStatusResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function EmailStatusResponseFromJSON(json: any): EmailStatusResponse {
    return EmailStatusResponseFromJSONTyped(json, false);
}

export function EmailStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailStatusResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'status_message': !exists(json, 'status_message') ? undefined : json['status_message'],
    };
}

export function EmailStatusResponseToJSON(value?: EmailStatusResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'status': value.status,
        'status_message': value.status_message,
    };
}

