/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Configurações do CSC (Código de Segurança do Contribuinte) para emissão
 * da NFC-e.
 * 
 * Se informado `id_csc` e `csc`, será utilizada a versão 2 do QR Code da
 * NFC-e. Para utilizar a versão 3 do QR Code (NT 2025.001), que dispensa o
 * CSC, envie `id_csc` igual a 0 (zero) e `csc` como string vazia.
 * 
 * Observação: emitente pessoa física (CPF) utilizar sempre a versão 3 do
 * QR Code.
 * @export
 * @interface EmpresaConfigNfceSefaz
 */
export interface EmpresaConfigNfceSefaz {
    /**
     * Número de identificação do CSC.
     * @type {number}
     * @memberof EmpresaConfigNfceSefaz
     */
    id_csc?: number;
    /**
     * Código do CSC.
     * @type {string}
     * @memberof EmpresaConfigNfceSefaz
     */
    csc?: string;
}

/**
 * Check if a given object implements the EmpresaConfigNfceSefaz interface.
 */
export function instanceOfEmpresaConfigNfceSefaz(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EmpresaConfigNfceSefazFromJSON(json: any): EmpresaConfigNfceSefaz {
    return EmpresaConfigNfceSefazFromJSONTyped(json, false);
}

export function EmpresaConfigNfceSefazFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmpresaConfigNfceSefaz {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id_csc': !exists(json, 'id_csc') ? undefined : json['id_csc'],
        'csc': !exists(json, 'csc') ? undefined : json['csc'],
    };
}

export function EmpresaConfigNfceSefazToJSON(value?: EmpresaConfigNfceSefaz | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id_csc': value.id_csc,
        'csc': value.csc,
    };
}

