/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmpresaConfigDce
 */
export interface EmpresaConfigDce {
    /**
     * Indica se a empresa irá emitir em produção ou homologação.
     * @type {string}
     * @memberof EmpresaConfigDce
     */
    ambiente: EmpresaConfigDceAmbienteEnum;
}


/**
 * @export
 */
export const EmpresaConfigDceAmbienteEnum = {
    Homologacao: 'homologacao',
    Producao: 'producao'
} as const;
export type EmpresaConfigDceAmbienteEnum = typeof EmpresaConfigDceAmbienteEnum[keyof typeof EmpresaConfigDceAmbienteEnum];


/**
 * Check if a given object implements the EmpresaConfigDce interface.
 */
export function instanceOfEmpresaConfigDce(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "ambiente" in value;

    return isInstance;
}

export function EmpresaConfigDceFromJSON(json: any): EmpresaConfigDce {
    return EmpresaConfigDceFromJSONTyped(json, false);
}

export function EmpresaConfigDceFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmpresaConfigDce {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ambiente': json['ambiente'],
    };
}

export function EmpresaConfigDceToJSON(value?: EmpresaConfigDce | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ambiente': value.ambiente,
    };
}

