/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmpresaPedidoCadastroCertificado
 */
export interface EmpresaPedidoCadastroCertificado {
    /**
     * Binário do certificado digital (.pfx ou .p12) codificado em base64.
     * @type {string}
     * @memberof EmpresaPedidoCadastroCertificado
     */
    certificado: string;
    /**
     * Senha do certificado.
     * @type {string}
     * @memberof EmpresaPedidoCadastroCertificado
     */
    password: string;
}

/**
 * Check if a given object implements the EmpresaPedidoCadastroCertificado interface.
 */
export function instanceOfEmpresaPedidoCadastroCertificado(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "certificado" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function EmpresaPedidoCadastroCertificadoFromJSON(json: any): EmpresaPedidoCadastroCertificado {
    return EmpresaPedidoCadastroCertificadoFromJSONTyped(json, false);
}

export function EmpresaPedidoCadastroCertificadoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmpresaPedidoCadastroCertificado {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'certificado': json['certificado'],
        'password': json['password'],
    };
}

export function EmpresaPedidoCadastroCertificadoToJSON(value?: EmpresaPedidoCadastroCertificado | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'certificado': value.certificado,
        'password': value.password,
    };
}

