/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EnderExtSimples } from './EnderExtSimples';
import {
    EnderExtSimplesFromJSON,
    EnderExtSimplesFromJSONTyped,
    EnderExtSimplesToJSON,
} from './EnderExtSimples';

/**
 * Grupo de informações relativas ao endereço da atividade, evento ou local do serviço prestado.
 * @export
 * @interface EnderecoSimples
 */
export interface EnderecoSimples {
    /**
     * Número do CEP.
     * @type {string}
     * @memberof EnderecoSimples
     */
    CEP?: string | null;
    /**
     * 
     * @type {EnderExtSimples}
     * @memberof EnderecoSimples
     */
    endExt?: EnderExtSimples;
    /**
     * Tipo e nome do logradouro da localização do imóvel.
     * @type {string}
     * @memberof EnderecoSimples
     */
    xLgr: string | null;
    /**
     * Tipo do Logradouro.
     * 
     * **Atenção**: Para emissões pelo Sistema Nacional NFS-e, esse campo é ignorado.
     * @type {string}
     * @memberof EnderecoSimples
     */
    tpLgr?: string | null;
    /**
     * Número do imóvel.
     * @type {string}
     * @memberof EnderecoSimples
     */
    nro: string | null;
    /**
     * Complemento do endereço.
     * @type {string}
     * @memberof EnderecoSimples
     */
    xCpl?: string | null;
    /**
     * Bairro.
     * @type {string}
     * @memberof EnderecoSimples
     */
    xBairro: string | null;
}

/**
 * Check if a given object implements the EnderecoSimples interface.
 */
export function instanceOfEnderecoSimples(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "xLgr" in value;
    isInstance = isInstance && "nro" in value;
    isInstance = isInstance && "xBairro" in value;

    return isInstance;
}

export function EnderecoSimplesFromJSON(json: any): EnderecoSimples {
    return EnderecoSimplesFromJSONTyped(json, false);
}

export function EnderecoSimplesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnderecoSimples {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'CEP': !exists(json, 'CEP') ? undefined : json['CEP'],
        'endExt': !exists(json, 'endExt') ? undefined : EnderExtSimplesFromJSON(json['endExt']),
        'xLgr': json['xLgr'],
        'tpLgr': !exists(json, 'tpLgr') ? undefined : json['tpLgr'],
        'nro': json['nro'],
        'xCpl': !exists(json, 'xCpl') ? undefined : json['xCpl'],
        'xBairro': json['xBairro'],
    };
}

export function EnderecoSimplesToJSON(value?: EnderecoSimples | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'CEP': value.CEP,
        'endExt': EnderExtSimplesToJSON(value.endExt),
        'xLgr': value.xLgr,
        'tpLgr': value.tpLgr,
        'nro': value.nro,
        'xCpl': value.xCpl,
        'xBairro': value.xBairro,
    };
}

