/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ListaDocDedRed } from './ListaDocDedRed';
import {
    ListaDocDedRedFromJSON,
    ListaDocDedRedFromJSONTyped,
    ListaDocDedRedToJSON,
} from './ListaDocDedRed';

/**
 * Grupo de informações relativas ao valores para dedução/redução do valor da base de cálculo (valor do serviço).
 * @export
 * @interface InfoDedRed
 */
export interface InfoDedRed {
    /**
     * Valor percentual padrão para dedução/redução do valor do serviço.
     * @type {number}
     * @memberof InfoDedRed
     */
    pDR?: number | null;
    /**
     * Valor monetário padrão para dedução/redução do valor do serviço.
     * @type {number}
     * @memberof InfoDedRed
     */
    vDR?: number | null;
    /**
     * 
     * @type {ListaDocDedRed}
     * @memberof InfoDedRed
     */
    documentos?: ListaDocDedRed;
}

/**
 * Check if a given object implements the InfoDedRed interface.
 */
export function instanceOfInfoDedRed(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InfoDedRedFromJSON(json: any): InfoDedRed {
    return InfoDedRedFromJSONTyped(json, false);
}

export function InfoDedRedFromJSONTyped(json: any, ignoreDiscriminator: boolean): InfoDedRed {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pDR': !exists(json, 'pDR') ? undefined : json['pDR'],
        'vDR': !exists(json, 'vDR') ? undefined : json['vDR'],
        'documentos': !exists(json, 'documentos') ? undefined : ListaDocDedRedFromJSON(json['documentos']),
    };
}

export function InfoDedRedToJSON(value?: InfoDedRed | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pDR': value.pDR,
        'vDR': value.vDR,
        'documentos': ListaDocDedRedToJSON(value.documentos),
    };
}

