/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TribFederal } from './TribFederal';
import {
    TribFederalFromJSON,
    TribFederalFromJSONTyped,
    TribFederalToJSON,
} from './TribFederal';
import type { TribMunicipal } from './TribMunicipal';
import {
    TribMunicipalFromJSON,
    TribMunicipalFromJSONTyped,
    TribMunicipalToJSON,
} from './TribMunicipal';
import type { TribTotal } from './TribTotal';
import {
    TribTotalFromJSON,
    TribTotalFromJSONTyped,
    TribTotalToJSON,
} from './TribTotal';

/**
 * Grupo de informações relacionados aos tributos relacionados ao serviço prestado.
 * @export
 * @interface InfoTributacao
 */
export interface InfoTributacao {
    /**
     * 
     * @type {TribMunicipal}
     * @memberof InfoTributacao
     */
    tribMun: TribMunicipal;
    /**
     * 
     * @type {TribFederal}
     * @memberof InfoTributacao
     */
    tribFed?: TribFederal;
    /**
     * 
     * @type {TribTotal}
     * @memberof InfoTributacao
     */
    totTrib?: TribTotal;
}

/**
 * Check if a given object implements the InfoTributacao interface.
 */
export function instanceOfInfoTributacao(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "tribMun" in value;

    return isInstance;
}

export function InfoTributacaoFromJSON(json: any): InfoTributacao {
    return InfoTributacaoFromJSONTyped(json, false);
}

export function InfoTributacaoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InfoTributacao {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tribMun': TribMunicipalFromJSON(json['tribMun']),
        'tribFed': !exists(json, 'tribFed') ? undefined : TribFederalFromJSON(json['tribFed']),
        'totTrib': !exists(json, 'totTrib') ? undefined : TribTotalFromJSON(json['totTrib']),
    };
}

export function InfoTributacaoToJSON(value?: InfoTributacao | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tribMun': TribMunicipalToJSON(value.tribMun),
        'tribFed': TribFederalToJSON(value.tribFed),
        'totTrib': TribTotalToJSON(value.totTrib),
    };
}

