/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Endereco } from './Endereco';
import {
    EnderecoFromJSON,
    EnderecoFromJSONTyped,
    EnderecoToJSON,
} from './Endereco';

/**
 * Grupo de informações do DPS relativas ao Tomador de Serviços.
 * @export
 * @interface InfoTomador
 */
export interface InfoTomador {
    /**
     * Indica se o tomador do serviço - um órgão público.
     * 
     * **Atenção**: Para emissões pelo Sistema Nacional NFS-e, esse campo é ignorado.
     * @type {boolean}
     * @memberof InfoTomador
     */
    orgaoPublico?: boolean | null;
    /**
     * Número do CNPJ.
     * @type {string}
     * @memberof InfoTomador
     */
    CNPJ?: string | null;
    /**
     * Número do CPF.
     * @type {string}
     * @memberof InfoTomador
     */
    CPF?: string | null;
    /**
     * Número de Identificação Fiscal fornecido por órgão de administração tributária no exterior.
     * @type {string}
     * @memberof InfoTomador
     */
    NIF?: string | null;
    /**
     * Motivo para não informação do NIF:
     * * 0 - Não informado na nota de origem
     * * 1 - Dispensado do NIF
     * * 2 - Não exigência do NIF
     * @type {number}
     * @memberof InfoTomador
     */
    cNaoNIF?: number | null;
    /**
     * Número do Cadastro de Atividade Econômica da Pessoa Física (CAEPF).
     * @type {string}
     * @memberof InfoTomador
     */
    CAEPF?: string | null;
    /**
     * Número da inscrição municipal.
     * @type {string}
     * @memberof InfoTomador
     */
    IM?: string | null;
    /**
     * Número da inscrição estadual.
     * 
     * **Atenção**: Para emissões pelo Sistema Nacional NFS-e, esse campo é ignorado.
     * @type {string}
     * @memberof InfoTomador
     */
    IE?: string | null;
    /**
     * Nome/Nome Empresarial.
     * @type {string}
     * @memberof InfoTomador
     */
    xNome: string | null;
    /**
     * 
     * @type {Endereco}
     * @memberof InfoTomador
     */
    end?: Endereco;
    /**
     * Número do telefone do prestador:
     * Preencher com o Código DDD + número do telefone.
     * Nas operações com exterior é permitido informar o código do país + código da localidade + número do telefone).
     * @type {string}
     * @memberof InfoTomador
     */
    fone?: string | null;
    /**
     * * E-mail
     * @type {string}
     * @memberof InfoTomador
     */
    email?: string | null;
}

/**
 * Check if a given object implements the InfoTomador interface.
 */
export function instanceOfInfoTomador(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "xNome" in value;

    return isInstance;
}

export function InfoTomadorFromJSON(json: any): InfoTomador {
    return InfoTomadorFromJSONTyped(json, false);
}

export function InfoTomadorFromJSONTyped(json: any, ignoreDiscriminator: boolean): InfoTomador {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orgaoPublico': !exists(json, 'orgaoPublico') ? undefined : json['orgaoPublico'],
        'CNPJ': !exists(json, 'CNPJ') ? undefined : json['CNPJ'],
        'CPF': !exists(json, 'CPF') ? undefined : json['CPF'],
        'NIF': !exists(json, 'NIF') ? undefined : json['NIF'],
        'cNaoNIF': !exists(json, 'cNaoNIF') ? undefined : json['cNaoNIF'],
        'CAEPF': !exists(json, 'CAEPF') ? undefined : json['CAEPF'],
        'IM': !exists(json, 'IM') ? undefined : json['IM'],
        'IE': !exists(json, 'IE') ? undefined : json['IE'],
        'xNome': json['xNome'],
        'end': !exists(json, 'end') ? undefined : EnderecoFromJSON(json['end']),
        'fone': !exists(json, 'fone') ? undefined : json['fone'],
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function InfoTomadorToJSON(value?: InfoTomador | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'orgaoPublico': value.orgaoPublico,
        'CNPJ': value.CNPJ,
        'CPF': value.CPF,
        'NIF': value.NIF,
        'cNaoNIF': value.cNaoNIF,
        'CAEPF': value.CAEPF,
        'IM': value.IM,
        'IE': value.IE,
        'xNome': value.xNome,
        'end': EnderecoToJSON(value.end),
        'fone': value.fone,
        'email': value.email,
    };
}

