/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MdfeSefazComp } from './MdfeSefazComp';
import {
    MdfeSefazCompFromJSON,
    MdfeSefazCompFromJSONTyped,
    MdfeSefazCompToJSON,
} from './MdfeSefazComp';
import type { MdfeSefazInfBanc } from './MdfeSefazInfBanc';
import {
    MdfeSefazInfBancFromJSON,
    MdfeSefazInfBancFromJSONTyped,
    MdfeSefazInfBancToJSON,
} from './MdfeSefazInfBanc';
import type { MdfeSefazInfPrazo } from './MdfeSefazInfPrazo';
import {
    MdfeSefazInfPrazoFromJSON,
    MdfeSefazInfPrazoFromJSONTyped,
    MdfeSefazInfPrazoToJSON,
} from './MdfeSefazInfPrazo';

/**
 * Informações do Pagamento do Contrato.
 * @export
 * @interface MdfeSefazInfPag
 */
export interface MdfeSefazInfPag {
    /**
     * Razão social ou Nome do respnsável pelo pagamento.
     * @type {string}
     * @memberof MdfeSefazInfPag
     */
    xNome?: string | null;
    /**
     * Número do CPF do responsável pelo pgto.
     * Informar os zeros não significativos.
     * @type {string}
     * @memberof MdfeSefazInfPag
     */
    CPF?: string | null;
    /**
     * Número do CNPJ do responsável pelo pgto.
     * Informar os zeros não significativos.
     * @type {string}
     * @memberof MdfeSefazInfPag
     */
    CNPJ?: string | null;
    /**
     * Identificador do responsável pelo pgto em caso de ser estrangeiro.
     * @type {string}
     * @memberof MdfeSefazInfPag
     */
    idEstrangeiro?: string | null;
    /**
     * 
     * @type {Array<MdfeSefazComp>}
     * @memberof MdfeSefazInfPag
     */
    Comp: Array<MdfeSefazComp>;
    /**
     * Valor Total do Contrato.
     * @type {number}
     * @memberof MdfeSefazInfPag
     */
    vContrato: number | null;
    /**
     * Indicador de operação de transporte de alto desempenho.
     * Operação de transporte com utilização de veículos de frotas dedicadas ou fidelizadas.
     * Preencher com “1” para indicar operação de transporte de alto desempenho, demais casos não informar a tag.
     * @type {number}
     * @memberof MdfeSefazInfPag
     */
    indAltoDesemp?: number | null;
    /**
     * Indicador da Forma de Pagamento:0-Pagamento à Vista
     * * 1 - Pagamento à Prazo
     * @type {number}
     * @memberof MdfeSefazInfPag
     */
    indPag: number | null;
    /**
     * Valor do Adiantamento (usar apenas em pagamento à Prazo.
     * @type {number}
     * @memberof MdfeSefazInfPag
     */
    vAdiant?: number | null;
    /**
     * Indicador para declarar concordância em antecipar o adiantamento.
     * Informar a tag somente se for autorizado antecipar o adiantamento.
     * @type {number}
     * @memberof MdfeSefazInfPag
     */
    indAntecipaAdiant?: number | null;
    /**
     * 
     * @type {Array<MdfeSefazInfPrazo>}
     * @memberof MdfeSefazInfPag
     */
    infPrazo?: Array<MdfeSefazInfPrazo>;
    /**
     * Tipo de Permissão em relação a antecipação das parcelas.
     * * 0 - Não permite antecipar
     * * 1 - Permite antecipar as parcelas
     * * 2 - Permite antecipar as parcelas mediante confirmação
     * @type {number}
     * @memberof MdfeSefazInfPag
     */
    tpAntecip?: number | null;
    /**
     * 
     * @type {MdfeSefazInfBanc}
     * @memberof MdfeSefazInfPag
     */
    infBanc: MdfeSefazInfBanc;
}

/**
 * Check if a given object implements the MdfeSefazInfPag interface.
 */
export function instanceOfMdfeSefazInfPag(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "Comp" in value;
    isInstance = isInstance && "vContrato" in value;
    isInstance = isInstance && "indPag" in value;
    isInstance = isInstance && "infBanc" in value;

    return isInstance;
}

export function MdfeSefazInfPagFromJSON(json: any): MdfeSefazInfPag {
    return MdfeSefazInfPagFromJSONTyped(json, false);
}

export function MdfeSefazInfPagFromJSONTyped(json: any, ignoreDiscriminator: boolean): MdfeSefazInfPag {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'xNome': !exists(json, 'xNome') ? undefined : json['xNome'],
        'CPF': !exists(json, 'CPF') ? undefined : json['CPF'],
        'CNPJ': !exists(json, 'CNPJ') ? undefined : json['CNPJ'],
        'idEstrangeiro': !exists(json, 'idEstrangeiro') ? undefined : json['idEstrangeiro'],
        'Comp': ((json['Comp'] as Array<any>).map(MdfeSefazCompFromJSON)),
        'vContrato': json['vContrato'],
        'indAltoDesemp': !exists(json, 'indAltoDesemp') ? undefined : json['indAltoDesemp'],
        'indPag': json['indPag'],
        'vAdiant': !exists(json, 'vAdiant') ? undefined : json['vAdiant'],
        'indAntecipaAdiant': !exists(json, 'indAntecipaAdiant') ? undefined : json['indAntecipaAdiant'],
        'infPrazo': !exists(json, 'infPrazo') ? undefined : ((json['infPrazo'] as Array<any>).map(MdfeSefazInfPrazoFromJSON)),
        'tpAntecip': !exists(json, 'tpAntecip') ? undefined : json['tpAntecip'],
        'infBanc': MdfeSefazInfBancFromJSON(json['infBanc']),
    };
}

export function MdfeSefazInfPagToJSON(value?: MdfeSefazInfPag | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'xNome': value.xNome,
        'CPF': value.CPF,
        'CNPJ': value.CNPJ,
        'idEstrangeiro': value.idEstrangeiro,
        'Comp': ((value.Comp as Array<any>).map(MdfeSefazCompToJSON)),
        'vContrato': value.vContrato,
        'indAltoDesemp': value.indAltoDesemp,
        'indPag': value.indPag,
        'vAdiant': value.vAdiant,
        'indAntecipaAdiant': value.indAntecipaAdiant,
        'infPrazo': value.infPrazo === undefined ? undefined : ((value.infPrazo as Array<any>).map(MdfeSefazInfPrazoToJSON)),
        'tpAntecip': value.tpAntecip,
        'infBanc': MdfeSefazInfBancToJSON(value.infBanc),
    };
}

