/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Preenchido quando for  transporte de produtos classificados pela ONU como perigosos.
 * @export
 * @interface MdfeSefazInfMDFeTranspPeri
 */
export interface MdfeSefazInfMDFeTranspPeri {
    /**
     * Número ONU/UN.
     * Ver a legislação de transporte de produtos perigosos aplicadas ao modal.
     * @type {string}
     * @memberof MdfeSefazInfMDFeTranspPeri
     */
    nONU: string | null;
    /**
     * Nome apropriado para embarque do produto.
     * Ver a legislação de transporte de produtos perigosos aplicada ao modo de transporte.
     * @type {string}
     * @memberof MdfeSefazInfMDFeTranspPeri
     */
    xNomeAE?: string | null;
    /**
     * Classe ou subclasse/divisão, e risco subsidiário/risco secundário.
     * Ver a legislação de transporte de produtos perigosos aplicadas ao modal.
     * @type {string}
     * @memberof MdfeSefazInfMDFeTranspPeri
     */
    xClaRisco?: string | null;
    /**
     * Grupo de Embalagem.
     * Ver a legislação de transporte de produtos perigosos aplicadas ao modal
     * Preenchimento obrigatório para o modal aéreo.
     * A legislação para o modal rodoviário e ferroviário não atribui grupo de embalagem para todos os produtos, portanto haverá casos de não preenchimento desse campo.
     * @type {string}
     * @memberof MdfeSefazInfMDFeTranspPeri
     */
    grEmb?: string | null;
    /**
     * Quantidade total por produto.
     * Preencher conforme a legislação de transporte de produtos perigosos aplicada ao modal.
     * @type {string}
     * @memberof MdfeSefazInfMDFeTranspPeri
     */
    qTotProd: string | null;
    /**
     * Quantidade e Tipo de volumes.
     * Preencher conforme a legislação de transporte de produtos perigosos aplicada ao modal.
     * @type {string}
     * @memberof MdfeSefazInfMDFeTranspPeri
     */
    qVolTipo?: string | null;
}

/**
 * Check if a given object implements the MdfeSefazInfMDFeTranspPeri interface.
 */
export function instanceOfMdfeSefazInfMDFeTranspPeri(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "nONU" in value;
    isInstance = isInstance && "qTotProd" in value;

    return isInstance;
}

export function MdfeSefazInfMDFeTranspPeriFromJSON(json: any): MdfeSefazInfMDFeTranspPeri {
    return MdfeSefazInfMDFeTranspPeriFromJSONTyped(json, false);
}

export function MdfeSefazInfMDFeTranspPeriFromJSONTyped(json: any, ignoreDiscriminator: boolean): MdfeSefazInfMDFeTranspPeri {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nONU': json['nONU'],
        'xNomeAE': !exists(json, 'xNomeAE') ? undefined : json['xNomeAE'],
        'xClaRisco': !exists(json, 'xClaRisco') ? undefined : json['xClaRisco'],
        'grEmb': !exists(json, 'grEmb') ? undefined : json['grEmb'],
        'qTotProd': json['qTotProd'],
        'qVolTipo': !exists(json, 'qVolTipo') ? undefined : json['qVolTipo'],
    };
}

export function MdfeSefazInfMDFeTranspPeriToJSON(value?: MdfeSefazInfMDFeTranspPeri | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nONU': value.nONU,
        'xNomeAE': value.xNomeAE,
        'xClaRisco': value.xClaRisco,
        'grEmb': value.grEmb,
        'qTotProd': value.qTotProd,
        'qVolTipo': value.qVolTipo,
    };
}

