/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Informações das Undades de Carga vazias.
 * @export
 * @interface MdfeSefazInfUnidCargaVazia
 */
export interface MdfeSefazInfUnidCargaVazia {
    /**
     * Identificação da unidades de carga vazia.
     * @type {string}
     * @memberof MdfeSefazInfUnidCargaVazia
     */
    idUnidCargaVazia: string | null;
    /**
     * Tipo da unidade de carga vazia.
     * * 1 - Container
     * * 2 - ULD
     * * 3 - Pallet
     * * 4 - Outros
     * @type {number}
     * @memberof MdfeSefazInfUnidCargaVazia
     */
    tpUnidCargaVazia: number | null;
}

/**
 * Check if a given object implements the MdfeSefazInfUnidCargaVazia interface.
 */
export function instanceOfMdfeSefazInfUnidCargaVazia(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "idUnidCargaVazia" in value;
    isInstance = isInstance && "tpUnidCargaVazia" in value;

    return isInstance;
}

export function MdfeSefazInfUnidCargaVaziaFromJSON(json: any): MdfeSefazInfUnidCargaVazia {
    return MdfeSefazInfUnidCargaVaziaFromJSONTyped(json, false);
}

export function MdfeSefazInfUnidCargaVaziaFromJSONTyped(json: any, ignoreDiscriminator: boolean): MdfeSefazInfUnidCargaVazia {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'idUnidCargaVazia': json['idUnidCargaVazia'],
        'tpUnidCargaVazia': json['tpUnidCargaVazia'],
    };
}

export function MdfeSefazInfUnidCargaVaziaToJSON(value?: MdfeSefazInfUnidCargaVazia | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'idUnidCargaVazia': value.idUnidCargaVazia,
        'tpUnidCargaVazia': value.tpUnidCargaVazia,
    };
}

