/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MdfeSefazAereo } from './MdfeSefazAereo';
import {
    MdfeSefazAereoFromJSON,
    MdfeSefazAereoFromJSONTyped,
    MdfeSefazAereoToJSON,
} from './MdfeSefazAereo';
import type { MdfeSefazAquav } from './MdfeSefazAquav';
import {
    MdfeSefazAquavFromJSON,
    MdfeSefazAquavFromJSONTyped,
    MdfeSefazAquavToJSON,
} from './MdfeSefazAquav';
import type { MdfeSefazFerrov } from './MdfeSefazFerrov';
import {
    MdfeSefazFerrovFromJSON,
    MdfeSefazFerrovFromJSONTyped,
    MdfeSefazFerrovToJSON,
} from './MdfeSefazFerrov';
import type { MdfeSefazRodo } from './MdfeSefazRodo';
import {
    MdfeSefazRodoFromJSON,
    MdfeSefazRodoFromJSONTyped,
    MdfeSefazRodoToJSON,
} from './MdfeSefazRodo';

/**
 * Informações do modal.
 * @export
 * @interface MdfeSefazInfModal
 */
export interface MdfeSefazInfModal {
    /**
     * Versão do leiaute específico para o Modal.
     * @type {string}
     * @memberof MdfeSefazInfModal
     */
    versaoModal: string | null;
    /**
     * 
     * @type {MdfeSefazAereo}
     * @memberof MdfeSefazInfModal
     */
    aereo?: MdfeSefazAereo;
    /**
     * 
     * @type {MdfeSefazRodo}
     * @memberof MdfeSefazInfModal
     */
    rodo?: MdfeSefazRodo;
    /**
     * 
     * @type {MdfeSefazAquav}
     * @memberof MdfeSefazInfModal
     */
    aquav?: MdfeSefazAquav;
    /**
     * 
     * @type {MdfeSefazFerrov}
     * @memberof MdfeSefazInfModal
     */
    ferrov?: MdfeSefazFerrov;
}

/**
 * Check if a given object implements the MdfeSefazInfModal interface.
 */
export function instanceOfMdfeSefazInfModal(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "versaoModal" in value;

    return isInstance;
}

export function MdfeSefazInfModalFromJSON(json: any): MdfeSefazInfModal {
    return MdfeSefazInfModalFromJSONTyped(json, false);
}

export function MdfeSefazInfModalFromJSONTyped(json: any, ignoreDiscriminator: boolean): MdfeSefazInfModal {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'versaoModal': json['versaoModal'],
        'aereo': !exists(json, 'aereo') ? undefined : MdfeSefazAereoFromJSON(json['aereo']),
        'rodo': !exists(json, 'rodo') ? undefined : MdfeSefazRodoFromJSON(json['rodo']),
        'aquav': !exists(json, 'aquav') ? undefined : MdfeSefazAquavFromJSON(json['aquav']),
        'ferrov': !exists(json, 'ferrov') ? undefined : MdfeSefazFerrovFromJSON(json['ferrov']),
    };
}

export function MdfeSefazInfModalToJSON(value?: MdfeSefazInfModal | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'versaoModal': value.versaoModal,
        'aereo': MdfeSefazAereoToJSON(value.aereo),
        'rodo': MdfeSefazRodoToJSON(value.rodo),
        'aquav': MdfeSefazAquavToJSON(value.aquav),
        'ferrov': MdfeSefazFerrovToJSON(value.ferrov),
    };
}

