/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MdfeSefazInfEmbComb } from './MdfeSefazInfEmbComb';
import {
    MdfeSefazInfEmbCombFromJSON,
    MdfeSefazInfEmbCombFromJSONTyped,
    MdfeSefazInfEmbCombToJSON,
} from './MdfeSefazInfEmbComb';
import type { MdfeSefazInfTermCarreg } from './MdfeSefazInfTermCarreg';
import {
    MdfeSefazInfTermCarregFromJSON,
    MdfeSefazInfTermCarregFromJSONTyped,
    MdfeSefazInfTermCarregToJSON,
} from './MdfeSefazInfTermCarreg';
import type { MdfeSefazInfTermDescarreg } from './MdfeSefazInfTermDescarreg';
import {
    MdfeSefazInfTermDescarregFromJSON,
    MdfeSefazInfTermDescarregFromJSONTyped,
    MdfeSefazInfTermDescarregToJSON,
} from './MdfeSefazInfTermDescarreg';
import type { MdfeSefazInfUnidCargaVazia } from './MdfeSefazInfUnidCargaVazia';
import {
    MdfeSefazInfUnidCargaVaziaFromJSON,
    MdfeSefazInfUnidCargaVaziaFromJSONTyped,
    MdfeSefazInfUnidCargaVaziaToJSON,
} from './MdfeSefazInfUnidCargaVazia';
import type { MdfeSefazInfUnidTranspVazia } from './MdfeSefazInfUnidTranspVazia';
import {
    MdfeSefazInfUnidTranspVaziaFromJSON,
    MdfeSefazInfUnidTranspVaziaFromJSONTyped,
    MdfeSefazInfUnidTranspVaziaToJSON,
} from './MdfeSefazInfUnidTranspVazia';

/**
 * Informações do modal Aquaviário.
 * @export
 * @interface MdfeSefazAquav
 */
export interface MdfeSefazAquav {
    /**
     * Irin do navio sempre deverá ser informado.
     * @type {string}
     * @memberof MdfeSefazAquav
     */
    irin: string | null;
    /**
     * Código do tipo de embarcação.
     * Preencher com código da Tabela de Tipo de Embarcação definida no Ministério dos Transportes.
     * @type {string}
     * @memberof MdfeSefazAquav
     */
    tpEmb: string | null;
    /**
     * Código da embarcação.
     * @type {string}
     * @memberof MdfeSefazAquav
     */
    cEmbar: string | null;
    /**
     * Nome da embarcação.
     * @type {string}
     * @memberof MdfeSefazAquav
     */
    xEmbar: string | null;
    /**
     * Número da Viagem.
     * @type {string}
     * @memberof MdfeSefazAquav
     */
    nViag: string | null;
    /**
     * Código do Porto de Embarque.
     * Preencher de acordo com Tabela de Portos definida no Ministério dos Transportes.
     * @type {string}
     * @memberof MdfeSefazAquav
     */
    cPrtEmb: string | null;
    /**
     * Código do Porto de Destino.
     * Preencher de acordo com Tabela de Portos definida no Ministério dos Transportes.
     * @type {string}
     * @memberof MdfeSefazAquav
     */
    cPrtDest: string | null;
    /**
     * Porto de Transbordo.
     * @type {string}
     * @memberof MdfeSefazAquav
     */
    prtTrans?: string | null;
    /**
     * Tipo de Navegação.
     * Preencher com:
     * * 0 - Interior
     * * 1 - Cabotagem
     * @type {number}
     * @memberof MdfeSefazAquav
     */
    tpNav?: number | null;
    /**
     * 
     * @type {Array<MdfeSefazInfTermCarreg>}
     * @memberof MdfeSefazAquav
     */
    infTermCarreg?: Array<MdfeSefazInfTermCarreg>;
    /**
     * 
     * @type {Array<MdfeSefazInfTermDescarreg>}
     * @memberof MdfeSefazAquav
     */
    infTermDescarreg?: Array<MdfeSefazInfTermDescarreg>;
    /**
     * 
     * @type {Array<MdfeSefazInfEmbComb>}
     * @memberof MdfeSefazAquav
     */
    infEmbComb?: Array<MdfeSefazInfEmbComb>;
    /**
     * 
     * @type {Array<MdfeSefazInfUnidCargaVazia>}
     * @memberof MdfeSefazAquav
     */
    infUnidCargaVazia?: Array<MdfeSefazInfUnidCargaVazia>;
    /**
     * 
     * @type {Array<MdfeSefazInfUnidTranspVazia>}
     * @memberof MdfeSefazAquav
     */
    infUnidTranspVazia?: Array<MdfeSefazInfUnidTranspVazia>;
    /**
     * Maritime Mobile Service Identify.
     * Preencher com o MMSI (Maritime Mobile Service Identify) fornecido pela ANATEL ou autoridade de telecomunicações de origem da embarcação.
     * @type {string}
     * @memberof MdfeSefazAquav
     */
    MMSI?: string | null;
}

/**
 * Check if a given object implements the MdfeSefazAquav interface.
 */
export function instanceOfMdfeSefazAquav(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "irin" in value;
    isInstance = isInstance && "tpEmb" in value;
    isInstance = isInstance && "cEmbar" in value;
    isInstance = isInstance && "xEmbar" in value;
    isInstance = isInstance && "nViag" in value;
    isInstance = isInstance && "cPrtEmb" in value;
    isInstance = isInstance && "cPrtDest" in value;

    return isInstance;
}

export function MdfeSefazAquavFromJSON(json: any): MdfeSefazAquav {
    return MdfeSefazAquavFromJSONTyped(json, false);
}

export function MdfeSefazAquavFromJSONTyped(json: any, ignoreDiscriminator: boolean): MdfeSefazAquav {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'irin': json['irin'],
        'tpEmb': json['tpEmb'],
        'cEmbar': json['cEmbar'],
        'xEmbar': json['xEmbar'],
        'nViag': json['nViag'],
        'cPrtEmb': json['cPrtEmb'],
        'cPrtDest': json['cPrtDest'],
        'prtTrans': !exists(json, 'prtTrans') ? undefined : json['prtTrans'],
        'tpNav': !exists(json, 'tpNav') ? undefined : json['tpNav'],
        'infTermCarreg': !exists(json, 'infTermCarreg') ? undefined : ((json['infTermCarreg'] as Array<any>).map(MdfeSefazInfTermCarregFromJSON)),
        'infTermDescarreg': !exists(json, 'infTermDescarreg') ? undefined : ((json['infTermDescarreg'] as Array<any>).map(MdfeSefazInfTermDescarregFromJSON)),
        'infEmbComb': !exists(json, 'infEmbComb') ? undefined : ((json['infEmbComb'] as Array<any>).map(MdfeSefazInfEmbCombFromJSON)),
        'infUnidCargaVazia': !exists(json, 'infUnidCargaVazia') ? undefined : ((json['infUnidCargaVazia'] as Array<any>).map(MdfeSefazInfUnidCargaVaziaFromJSON)),
        'infUnidTranspVazia': !exists(json, 'infUnidTranspVazia') ? undefined : ((json['infUnidTranspVazia'] as Array<any>).map(MdfeSefazInfUnidTranspVaziaFromJSON)),
        'MMSI': !exists(json, 'MMSI') ? undefined : json['MMSI'],
    };
}

export function MdfeSefazAquavToJSON(value?: MdfeSefazAquav | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'irin': value.irin,
        'tpEmb': value.tpEmb,
        'cEmbar': value.cEmbar,
        'xEmbar': value.xEmbar,
        'nViag': value.nViag,
        'cPrtEmb': value.cPrtEmb,
        'cPrtDest': value.cPrtDest,
        'prtTrans': value.prtTrans,
        'tpNav': value.tpNav,
        'infTermCarreg': value.infTermCarreg === undefined ? undefined : ((value.infTermCarreg as Array<any>).map(MdfeSefazInfTermCarregToJSON)),
        'infTermDescarreg': value.infTermDescarreg === undefined ? undefined : ((value.infTermDescarreg as Array<any>).map(MdfeSefazInfTermDescarregToJSON)),
        'infEmbComb': value.infEmbComb === undefined ? undefined : ((value.infEmbComb as Array<any>).map(MdfeSefazInfEmbCombToJSON)),
        'infUnidCargaVazia': value.infUnidCargaVazia === undefined ? undefined : ((value.infUnidCargaVazia as Array<any>).map(MdfeSefazInfUnidCargaVaziaToJSON)),
        'infUnidTranspVazia': value.infUnidTranspVazia === undefined ? undefined : ((value.infUnidTranspVazia as Array<any>).map(MdfeSefazInfUnidTranspVaziaToJSON)),
        'MMSI': value.MMSI,
    };
}

