/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Informações dos Municípios de Carregamento.
 * @export
 * @interface MdfeSefazInfMunCarrega
 */
export interface MdfeSefazInfMunCarrega {
    /**
     * Código do Município de Carregamento.
     * @type {string}
     * @memberof MdfeSefazInfMunCarrega
     */
    cMunCarrega: string | null;
    /**
     * Nome do Município de Carregamento.
     * @type {string}
     * @memberof MdfeSefazInfMunCarrega
     */
    xMunCarrega: string | null;
}

/**
 * Check if a given object implements the MdfeSefazInfMunCarrega interface.
 */
export function instanceOfMdfeSefazInfMunCarrega(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "cMunCarrega" in value;
    isInstance = isInstance && "xMunCarrega" in value;

    return isInstance;
}

export function MdfeSefazInfMunCarregaFromJSON(json: any): MdfeSefazInfMunCarrega {
    return MdfeSefazInfMunCarregaFromJSONTyped(json, false);
}

export function MdfeSefazInfMunCarregaFromJSONTyped(json: any, ignoreDiscriminator: boolean): MdfeSefazInfMunCarrega {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cMunCarrega': json['cMunCarrega'],
        'xMunCarrega': json['xMunCarrega'],
    };
}

export function MdfeSefazInfMunCarregaToJSON(value?: MdfeSefazInfMunCarrega | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cMunCarrega': value.cMunCarrega,
        'xMunCarrega': value.xMunCarrega,
    };
}

