/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MdfePedidoEmissao } from './MdfePedidoEmissao';
import {
    MdfePedidoEmissaoFromJSON,
    MdfePedidoEmissaoFromJSONTyped,
    MdfePedidoEmissaoToJSON,
} from './MdfePedidoEmissao';

/**
 * 
 * @export
 * @interface MdfePedidoEmissaoLote
 */
export interface MdfePedidoEmissaoLote {
    /**
     * 
     * @type {Array<MdfePedidoEmissao>}
     * @memberof MdfePedidoEmissaoLote
     */
    documentos?: Array<MdfePedidoEmissao>;
    /**
     * Identificação do Ambiente.
     * @type {string}
     * @memberof MdfePedidoEmissaoLote
     */
    ambiente: MdfePedidoEmissaoLoteAmbienteEnum;
    /**
     * Seu identificador para este documento. Opcional, ajuda a evitar o envio duplicado de um mesmo documento.
     * @type {string}
     * @memberof MdfePedidoEmissaoLote
     */
    referencia?: string;
    /**
     * 
     * @type {string}
     * @memberof MdfePedidoEmissaoLote
     */
    id_lote: string;
}


/**
 * @export
 */
export const MdfePedidoEmissaoLoteAmbienteEnum = {
    Homologacao: 'homologacao',
    Producao: 'producao'
} as const;
export type MdfePedidoEmissaoLoteAmbienteEnum = typeof MdfePedidoEmissaoLoteAmbienteEnum[keyof typeof MdfePedidoEmissaoLoteAmbienteEnum];


/**
 * Check if a given object implements the MdfePedidoEmissaoLote interface.
 */
export function instanceOfMdfePedidoEmissaoLote(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "ambiente" in value;
    isInstance = isInstance && "id_lote" in value;

    return isInstance;
}

export function MdfePedidoEmissaoLoteFromJSON(json: any): MdfePedidoEmissaoLote {
    return MdfePedidoEmissaoLoteFromJSONTyped(json, false);
}

export function MdfePedidoEmissaoLoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): MdfePedidoEmissaoLote {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'documentos': !exists(json, 'documentos') ? undefined : ((json['documentos'] as Array<any>).map(MdfePedidoEmissaoFromJSON)),
        'ambiente': json['ambiente'],
        'referencia': !exists(json, 'referencia') ? undefined : json['referencia'],
        'id_lote': json['id_lote'],
    };
}

export function MdfePedidoEmissaoLoteToJSON(value?: MdfePedidoEmissaoLote | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'documentos': value.documentos === undefined ? undefined : ((value.documentos as Array<any>).map(MdfePedidoEmissaoToJSON)),
        'ambiente': value.ambiente,
        'referencia': value.referencia,
        'id_lote': value.id_lote,
    };
}

