/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Informações da composição do trem.
 * @export
 * @interface MdfeSefazTrem
 */
export interface MdfeSefazTrem {
    /**
     * Prefixo do Trem.
     * @type {string}
     * @memberof MdfeSefazTrem
     */
    xPref: string | null;
    /**
     * Data e hora de liberação do trem na origem.
     * @type {Date}
     * @memberof MdfeSefazTrem
     */
    dhTrem?: Date | null;
    /**
     * Origem do Trem.
     * Sigla da estação de origem.
     * @type {string}
     * @memberof MdfeSefazTrem
     */
    xOri: string | null;
    /**
     * Destino do Trem.
     * Sigla da estação de destino.
     * @type {string}
     * @memberof MdfeSefazTrem
     */
    xDest: string | null;
    /**
     * Quantidade de vagões carregados.
     * @type {number}
     * @memberof MdfeSefazTrem
     */
    qVag: number | null;
}

/**
 * Check if a given object implements the MdfeSefazTrem interface.
 */
export function instanceOfMdfeSefazTrem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "xPref" in value;
    isInstance = isInstance && "xOri" in value;
    isInstance = isInstance && "xDest" in value;
    isInstance = isInstance && "qVag" in value;

    return isInstance;
}

export function MdfeSefazTremFromJSON(json: any): MdfeSefazTrem {
    return MdfeSefazTremFromJSONTyped(json, false);
}

export function MdfeSefazTremFromJSONTyped(json: any, ignoreDiscriminator: boolean): MdfeSefazTrem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'xPref': json['xPref'],
        'dhTrem': !exists(json, 'dhTrem') ? undefined : (json['dhTrem'] === null ? null : new Date(json['dhTrem'])),
        'xOri': json['xOri'],
        'xDest': json['xDest'],
        'qVag': json['qVag'],
    };
}

export function MdfeSefazTremToJSON(value?: MdfeSefazTrem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'xPref': value.xPref,
        'dhTrem': value.dhTrem === undefined ? undefined : (value.dhTrem === null ? null : value.dhTrem.toISOString()),
        'xOri': value.xOri,
        'xDest': value.xDest,
        'qVag': value.qVag,
    };
}

