/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MdfeSefazDisp } from './MdfeSefazDisp';
import {
    MdfeSefazDispFromJSON,
    MdfeSefazDispFromJSONTyped,
    MdfeSefazDispToJSON,
} from './MdfeSefazDisp';

/**
 * Informações de Vale Pedágio.
 * Outras informações sobre Vale-Pedágio obrigatório que não tenham campos específicos devem ser informadas no campo de observações gerais de uso livre pelo contribuinte, visando atender as determinações legais vigentes.
 * @export
 * @interface MdfeSefazValePed
 */
export interface MdfeSefazValePed {
    /**
     * 
     * @type {Array<MdfeSefazDisp>}
     * @memberof MdfeSefazValePed
     */
    disp: Array<MdfeSefazDisp>;
    /**
     * Categoria de Combinação Veicular.
     * Preencher com:
     * 02 Veículo Comercial 2 eixos
     * 0
     * 4 Veículo Comercial 3 eixos
     * 06 Veículo Comercial 4 eixos
     * 0
     * 7 Veículo Comercial 5 eixos
     * 0
     * 8 Veículo Comercial 6 eixos
     * 10 Veículo Comercial 7 eixos
     * 11 Veículo Comercial 8 eixos
     * 12 Veículo Comercial 9 eixos
     * 13 Veículo Comercial 10 eixos
     * 14 Veículo Comercial Acima de 10 eixos.
     * @type {string}
     * @memberof MdfeSefazValePed
     */
    categCombVeic?: string | null;
}

/**
 * Check if a given object implements the MdfeSefazValePed interface.
 */
export function instanceOfMdfeSefazValePed(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "disp" in value;

    return isInstance;
}

export function MdfeSefazValePedFromJSON(json: any): MdfeSefazValePed {
    return MdfeSefazValePedFromJSONTyped(json, false);
}

export function MdfeSefazValePedFromJSONTyped(json: any, ignoreDiscriminator: boolean): MdfeSefazValePed {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'disp': ((json['disp'] as Array<any>).map(MdfeSefazDispFromJSON)),
        'categCombVeic': !exists(json, 'categCombVeic') ? undefined : json['categCombVeic'],
    };
}

export function MdfeSefazValePedToJSON(value?: MdfeSefazValePed | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'disp': ((value.disp as Array<any>).map(MdfeSefazDispToJSON)),
        'categCombVeic': value.categCombVeic,
    };
}

