/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Informações do Percurso do MDF-e.
 * @export
 * @interface MdfeSefazInfPercurso
 */
export interface MdfeSefazInfPercurso {
    /**
     * Sigla das Unidades da Federação do percurso do veículo.
     * Não é necessário repetir as UF de Início e Fim.
     * @type {string}
     * @memberof MdfeSefazInfPercurso
     */
    UFPer: string | null;
}

/**
 * Check if a given object implements the MdfeSefazInfPercurso interface.
 */
export function instanceOfMdfeSefazInfPercurso(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "UFPer" in value;

    return isInstance;
}

export function MdfeSefazInfPercursoFromJSON(json: any): MdfeSefazInfPercurso {
    return MdfeSefazInfPercursoFromJSONTyped(json, false);
}

export function MdfeSefazInfPercursoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MdfeSefazInfPercurso {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'UFPer': json['UFPer'],
    };
}

export function MdfeSefazInfPercursoToJSON(value?: MdfeSefazInfPercurso | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'UFPer': value.UFPer,
    };
}

