/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MdfeSefazInfLotacao } from './MdfeSefazInfLotacao';
import {
    MdfeSefazInfLotacaoFromJSON,
    MdfeSefazInfLotacaoFromJSONTyped,
    MdfeSefazInfLotacaoToJSON,
} from './MdfeSefazInfLotacao';

/**
 * Produto predominante.
 * Informar a descrição do produto predominante, conforme o item de maior valor financeiro conforme Resolução ANTT n° 5.867 de 2020).
 * @export
 * @interface MdfeSefazProdPred
 */
export interface MdfeSefazProdPred {
    /**
     * Tipo de Carga.
     * Conforme Resolução ANTT nº.  5.849/2019.
     * * 01 - Granel sólido
     * * 02 - Granel líquido
     * * 03 - Frigorificada
     * * 04 - Conteinerizada
     * * 05 - Carga Geral
     * * 06 - Neogranel
     * * 07 - Perigosa (granel sólido)
     * * 08 - Perigosa (granel líquido)
     * * 09 - Perigosa (carga frigorificada)
     * * 10 - Perigosa (conteinerizada)
     * * 11 - Perigosa (carga geral)
     * * 12 - Granel pressurizada
     * @type {string}
     * @memberof MdfeSefazProdPred
     */
    tpCarga: string | null;
    /**
     * Descrição do produto.
     * @type {string}
     * @memberof MdfeSefazProdPred
     */
    xProd: string | null;
    /**
     * GTIN (Global Trade Item Number) do produto, antigo código EAN ou código de barras.
     * @type {string}
     * @memberof MdfeSefazProdPred
     */
    cEAN?: string | null;
    /**
     * Código NCM.
     * @type {string}
     * @memberof MdfeSefazProdPred
     */
    NCM?: string | null;
    /**
     * 
     * @type {MdfeSefazInfLotacao}
     * @memberof MdfeSefazProdPred
     */
    infLotacao?: MdfeSefazInfLotacao;
}

/**
 * Check if a given object implements the MdfeSefazProdPred interface.
 */
export function instanceOfMdfeSefazProdPred(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "tpCarga" in value;
    isInstance = isInstance && "xProd" in value;

    return isInstance;
}

export function MdfeSefazProdPredFromJSON(json: any): MdfeSefazProdPred {
    return MdfeSefazProdPredFromJSONTyped(json, false);
}

export function MdfeSefazProdPredFromJSONTyped(json: any, ignoreDiscriminator: boolean): MdfeSefazProdPred {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tpCarga': json['tpCarga'],
        'xProd': json['xProd'],
        'cEAN': !exists(json, 'cEAN') ? undefined : json['cEAN'],
        'NCM': !exists(json, 'NCM') ? undefined : json['NCM'],
        'infLotacao': !exists(json, 'infLotacao') ? undefined : MdfeSefazInfLotacaoFromJSON(json['infLotacao']),
    };
}

export function MdfeSefazProdPredToJSON(value?: MdfeSefazProdPred | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tpCarga': value.tpCarga,
        'xProd': value.xProd,
        'cEAN': value.cEAN,
        'NCM': value.NCM,
        'infLotacao': MdfeSefazInfLotacaoToJSON(value.infLotacao),
    };
}

