/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Grupo de informações do PIX.
 * @export
 * @interface NfcomSefazGPIX
 */
export interface NfcomSefazGPIX {
    /**
     * URL do QRCode do PIX que será apresentado na fatura.
     * @type {string}
     * @memberof NfcomSefazGPIX
     */
    urlQRCodePIX: string | null;
}

/**
 * Check if a given object implements the NfcomSefazGPIX interface.
 */
export function instanceOfNfcomSefazGPIX(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "urlQRCodePIX" in value;

    return isInstance;
}

export function NfcomSefazGPIXFromJSON(json: any): NfcomSefazGPIX {
    return NfcomSefazGPIXFromJSONTyped(json, false);
}

export function NfcomSefazGPIXFromJSONTyped(json: any, ignoreDiscriminator: boolean): NfcomSefazGPIX {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'urlQRCodePIX': json['urlQRCodePIX'],
    };
}

export function NfcomSefazGPIXToJSON(value?: NfcomSefazGPIX | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'urlQRCodePIX': value.urlQRCodePIX,
    };
}

