/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NfcomSefazGProc } from './NfcomSefazGProc';
import {
    NfcomSefazGProcFromJSON,
    NfcomSefazGProcFromJSONTyped,
    NfcomSefazGProcToJSON,
} from './NfcomSefazGProc';

/**
 * Grupo Processo referenciado.
 * Este grupo somente deverá ser preenchido quando houver processo judicial ou administrativo que altere valores.
 * @export
 * @interface NfcomSefazGProcRef
 */
export interface NfcomSefazGProcRef {
    /**
     * Valor unitário do item.
     * Informar o valor sem a influência da decisão judicial/administrativa.
     * @type {number}
     * @memberof NfcomSefazGProcRef
     */
    vItem: number | null;
    /**
     * Quantidade Faturada.
     * Informar a quantidade de comercialização do produto .
     * @type {number}
     * @memberof NfcomSefazGProcRef
     */
    qFaturada: number | null;
    /**
     * Valor total do item.
     * @type {number}
     * @memberof NfcomSefazGProcRef
     */
    vProd: number | null;
    /**
     * Valor do Desconto.
     * @type {number}
     * @memberof NfcomSefazGProcRef
     */
    vDesc?: number | null;
    /**
     * Outras despesas acessórias.
     * @type {number}
     * @memberof NfcomSefazGProcRef
     */
    vOutro?: number | null;
    /**
     * Indicador de devolução do valor do item.
     * * 1 - Devolução do valor do item
     * @type {number}
     * @memberof NfcomSefazGProcRef
     */
    indDevolucao?: number | null;
    /**
     * Valor da BC do ICMS.
     * @type {number}
     * @memberof NfcomSefazGProcRef
     */
    vBC?: number | null;
    /**
     * Alíquota do ICMS.
     * @type {number}
     * @memberof NfcomSefazGProcRef
     */
    pICMS?: number | null;
    /**
     * Valor do ICMS.
     * @type {number}
     * @memberof NfcomSefazGProcRef
     */
    vICMS?: number | null;
    /**
     * Valor do PIS.
     * @type {number}
     * @memberof NfcomSefazGProcRef
     */
    vPIS?: number | null;
    /**
     * Valor do COFINS.
     * @type {number}
     * @memberof NfcomSefazGProcRef
     */
    vCOFINS?: number | null;
    /**
     * Valor do Fundo de Combate à Pobreza (FCP).
     * @type {number}
     * @memberof NfcomSefazGProcRef
     */
    vFCP?: number | null;
    /**
     * 
     * @type {Array<NfcomSefazGProc>}
     * @memberof NfcomSefazGProcRef
     */
    gProc: Array<NfcomSefazGProc>;
}

/**
 * Check if a given object implements the NfcomSefazGProcRef interface.
 */
export function instanceOfNfcomSefazGProcRef(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "vItem" in value;
    isInstance = isInstance && "qFaturada" in value;
    isInstance = isInstance && "vProd" in value;
    isInstance = isInstance && "gProc" in value;

    return isInstance;
}

export function NfcomSefazGProcRefFromJSON(json: any): NfcomSefazGProcRef {
    return NfcomSefazGProcRefFromJSONTyped(json, false);
}

export function NfcomSefazGProcRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): NfcomSefazGProcRef {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'vItem': json['vItem'],
        'qFaturada': json['qFaturada'],
        'vProd': json['vProd'],
        'vDesc': !exists(json, 'vDesc') ? undefined : json['vDesc'],
        'vOutro': !exists(json, 'vOutro') ? undefined : json['vOutro'],
        'indDevolucao': !exists(json, 'indDevolucao') ? undefined : json['indDevolucao'],
        'vBC': !exists(json, 'vBC') ? undefined : json['vBC'],
        'pICMS': !exists(json, 'pICMS') ? undefined : json['pICMS'],
        'vICMS': !exists(json, 'vICMS') ? undefined : json['vICMS'],
        'vPIS': !exists(json, 'vPIS') ? undefined : json['vPIS'],
        'vCOFINS': !exists(json, 'vCOFINS') ? undefined : json['vCOFINS'],
        'vFCP': !exists(json, 'vFCP') ? undefined : json['vFCP'],
        'gProc': ((json['gProc'] as Array<any>).map(NfcomSefazGProcFromJSON)),
    };
}

export function NfcomSefazGProcRefToJSON(value?: NfcomSefazGProcRef | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'vItem': value.vItem,
        'qFaturada': value.qFaturada,
        'vProd': value.vProd,
        'vDesc': value.vDesc,
        'vOutro': value.vOutro,
        'indDevolucao': value.indDevolucao,
        'vBC': value.vBC,
        'pICMS': value.pICMS,
        'vICMS': value.vICMS,
        'vPIS': value.vPIS,
        'vCOFINS': value.vCOFINS,
        'vFCP': value.vFCP,
        'gProc': ((value.gProc as Array<any>).map(NfcomSefazGProcToJSON)),
    };
}

