/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NfcomSefazGProcRef } from './NfcomSefazGProcRef';
import {
    NfcomSefazGProcRefFromJSON,
    NfcomSefazGProcRefFromJSONTyped,
    NfcomSefazGProcRefToJSON,
} from './NfcomSefazGProcRef';
import type { NfcomSefazGRessarc } from './NfcomSefazGRessarc';
import {
    NfcomSefazGRessarcFromJSON,
    NfcomSefazGRessarcFromJSONTyped,
    NfcomSefazGRessarcToJSON,
} from './NfcomSefazGRessarc';
import type { NfcomSefazImposto } from './NfcomSefazImposto';
import {
    NfcomSefazImpostoFromJSON,
    NfcomSefazImpostoFromJSONTyped,
    NfcomSefazImpostoToJSON,
} from './NfcomSefazImposto';
import type { NfcomSefazProd } from './NfcomSefazProd';
import {
    NfcomSefazProdFromJSON,
    NfcomSefazProdFromJSONTyped,
    NfcomSefazProdToJSON,
} from './NfcomSefazProd';

/**
 * Detalhamento de Produtos e Serviços.
 * @export
 * @interface NfcomSefazDet
 */
export interface NfcomSefazDet {
    /**
     * Número do item da NFCom.
     * @type {number}
     * @memberof NfcomSefazDet
     */
    nItem: number | null;
    /**
     * Chave de Acesso da NFCom anterior.
     * Informar chave de acesso de referencia anterior
     * TAG OPCIONAL, DEVE SER INFORMADA APENAS NOS CASOS PREVISTOS DE NOTA ANTERIOR REFERENCIADA.
     * @type {string}
     * @memberof NfcomSefazDet
     */
    chNFComAnt?: string | null;
    /**
     * Número do item da NFCom anterior.
     * Informar nro do item da chave de acesso de referencia anterior
     * TAG OPCIONAL, DEVE SER INFORMADA APENAS NOS CASOS PREVISTOS DE NOTA ANTERIOR REFERENCIADA.
     * @type {string}
     * @memberof NfcomSefazDet
     */
    nItemAnt?: string | null;
    /**
     * Indicador de Nota anterior em papel no faturamento centralizado.
     * Informa que a NFCom Anterior de Faturamento centralizado não é eletrônica.
     * @type {number}
     * @memberof NfcomSefazDet
     */
    indNFComAntPapelFatCentral?: number | null;
    /**
     * 
     * @type {NfcomSefazProd}
     * @memberof NfcomSefazDet
     */
    prod: NfcomSefazProd;
    /**
     * 
     * @type {NfcomSefazImposto}
     * @memberof NfcomSefazDet
     */
    imposto: NfcomSefazImposto;
    /**
     * 
     * @type {NfcomSefazGProcRef}
     * @memberof NfcomSefazDet
     */
    gProcRef?: NfcomSefazGProcRef;
    /**
     * 
     * @type {NfcomSefazGRessarc}
     * @memberof NfcomSefazDet
     */
    gRessarc?: NfcomSefazGRessarc;
    /**
     * Informações adicionais do produto (norma referenciada, informações complementares, etc).
     * @type {string}
     * @memberof NfcomSefazDet
     */
    infAdProd?: string | null;
}

/**
 * Check if a given object implements the NfcomSefazDet interface.
 */
export function instanceOfNfcomSefazDet(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "nItem" in value;
    isInstance = isInstance && "prod" in value;
    isInstance = isInstance && "imposto" in value;

    return isInstance;
}

export function NfcomSefazDetFromJSON(json: any): NfcomSefazDet {
    return NfcomSefazDetFromJSONTyped(json, false);
}

export function NfcomSefazDetFromJSONTyped(json: any, ignoreDiscriminator: boolean): NfcomSefazDet {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nItem': json['nItem'],
        'chNFComAnt': !exists(json, 'chNFComAnt') ? undefined : json['chNFComAnt'],
        'nItemAnt': !exists(json, 'nItemAnt') ? undefined : json['nItemAnt'],
        'indNFComAntPapelFatCentral': !exists(json, 'indNFComAntPapelFatCentral') ? undefined : json['indNFComAntPapelFatCentral'],
        'prod': NfcomSefazProdFromJSON(json['prod']),
        'imposto': NfcomSefazImpostoFromJSON(json['imposto']),
        'gProcRef': !exists(json, 'gProcRef') ? undefined : NfcomSefazGProcRefFromJSON(json['gProcRef']),
        'gRessarc': !exists(json, 'gRessarc') ? undefined : NfcomSefazGRessarcFromJSON(json['gRessarc']),
        'infAdProd': !exists(json, 'infAdProd') ? undefined : json['infAdProd'],
    };
}

export function NfcomSefazDetToJSON(value?: NfcomSefazDet | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nItem': value.nItem,
        'chNFComAnt': value.chNFComAnt,
        'nItemAnt': value.nItemAnt,
        'indNFComAntPapelFatCentral': value.indNFComAntPapelFatCentral,
        'prod': NfcomSefazProdToJSON(value.prod),
        'imposto': NfcomSefazImpostoToJSON(value.imposto),
        'gProcRef': NfcomSefazGProcRefToJSON(value.gProcRef),
        'gRessarc': NfcomSefazGRessarcToJSON(value.gRessarc),
        'infAdProd': value.infAdProd,
    };
}

