/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NfcomSefazDevTrib } from './NfcomSefazDevTrib';
import {
    NfcomSefazDevTribFromJSON,
    NfcomSefazDevTribFromJSONTyped,
    NfcomSefazDevTribToJSON,
} from './NfcomSefazDevTrib';
import type { NfcomSefazDif } from './NfcomSefazDif';
import {
    NfcomSefazDifFromJSON,
    NfcomSefazDifFromJSONTyped,
    NfcomSefazDifToJSON,
} from './NfcomSefazDif';
import type { NfcomSefazRed } from './NfcomSefazRed';
import {
    NfcomSefazRedFromJSON,
    NfcomSefazRedFromJSONTyped,
    NfcomSefazRedToJSON,
} from './NfcomSefazRed';

/**
 * Grupo de Informações do IBS no Município.
 * @export
 * @interface NfcomSefazGIBSMun
 */
export interface NfcomSefazGIBSMun {
    /**
     * Aliquota do IBS Municipal (em percentual).
     * @type {number}
     * @memberof NfcomSefazGIBSMun
     */
    pIBSMun: number | null;
    /**
     * 
     * @type {NfcomSefazDif}
     * @memberof NfcomSefazGIBSMun
     */
    gDif?: NfcomSefazDif;
    /**
     * 
     * @type {NfcomSefazDevTrib}
     * @memberof NfcomSefazGIBSMun
     */
    gDevTrib?: NfcomSefazDevTrib;
    /**
     * 
     * @type {NfcomSefazRed}
     * @memberof NfcomSefazGIBSMun
     */
    gRed?: NfcomSefazRed;
    /**
     * Valor do IBS Municipal.
     * @type {number}
     * @memberof NfcomSefazGIBSMun
     */
    vIBSMun: number | null;
}

/**
 * Check if a given object implements the NfcomSefazGIBSMun interface.
 */
export function instanceOfNfcomSefazGIBSMun(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "pIBSMun" in value;
    isInstance = isInstance && "vIBSMun" in value;

    return isInstance;
}

export function NfcomSefazGIBSMunFromJSON(json: any): NfcomSefazGIBSMun {
    return NfcomSefazGIBSMunFromJSONTyped(json, false);
}

export function NfcomSefazGIBSMunFromJSONTyped(json: any, ignoreDiscriminator: boolean): NfcomSefazGIBSMun {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pIBSMun': json['pIBSMun'],
        'gDif': !exists(json, 'gDif') ? undefined : NfcomSefazDifFromJSON(json['gDif']),
        'gDevTrib': !exists(json, 'gDevTrib') ? undefined : NfcomSefazDevTribFromJSON(json['gDevTrib']),
        'gRed': !exists(json, 'gRed') ? undefined : NfcomSefazRedFromJSON(json['gRed']),
        'vIBSMun': json['vIBSMun'],
    };
}

export function NfcomSefazGIBSMunToJSON(value?: NfcomSefazGIBSMun | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pIBSMun': value.pIBSMun,
        'gDif': NfcomSefazDifToJSON(value.gDif),
        'gDevTrib': NfcomSefazDevTribToJSON(value.gDevTrib),
        'gRed': NfcomSefazRedToJSON(value.gRed),
        'vIBSMun': value.vIBSMun,
    };
}

