/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NfeSefazInfNFe } from './NfeSefazInfNFe';
import {
    NfeSefazInfNFeFromJSON,
    NfeSefazInfNFeFromJSONTyped,
    NfeSefazInfNFeToJSON,
} from './NfeSefazInfNFe';
import type { NfeSefazInfNFeSupl } from './NfeSefazInfNFeSupl';
import {
    NfeSefazInfNFeSuplFromJSON,
    NfeSefazInfNFeSuplFromJSONTyped,
    NfeSefazInfNFeSuplToJSON,
} from './NfeSefazInfNFeSupl';

/**
 * 
 * @export
 * @interface NfePedidoEmissao
 */
export interface NfePedidoEmissao {
    /**
     * 
     * @type {NfeSefazInfNFe}
     * @memberof NfePedidoEmissao
     */
    infNFe: NfeSefazInfNFe;
    /**
     * 
     * @type {NfeSefazInfNFeSupl}
     * @memberof NfePedidoEmissao
     */
    infNFeSupl?: NfeSefazInfNFeSupl;
    /**
     * Identificação do Ambiente.
     * @type {string}
     * @memberof NfePedidoEmissao
     */
    ambiente: NfePedidoEmissaoAmbienteEnum;
    /**
     * Seu identificador único para este documento. Opcional, ajuda a evitar o envio duplicado de um mesmo documento.
     * @type {string}
     * @memberof NfePedidoEmissao
     */
    referencia?: string | null;
}


/**
 * @export
 */
export const NfePedidoEmissaoAmbienteEnum = {
    Homologacao: 'homologacao',
    Producao: 'producao'
} as const;
export type NfePedidoEmissaoAmbienteEnum = typeof NfePedidoEmissaoAmbienteEnum[keyof typeof NfePedidoEmissaoAmbienteEnum];


/**
 * Check if a given object implements the NfePedidoEmissao interface.
 */
export function instanceOfNfePedidoEmissao(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "infNFe" in value;
    isInstance = isInstance && "ambiente" in value;

    return isInstance;
}

export function NfePedidoEmissaoFromJSON(json: any): NfePedidoEmissao {
    return NfePedidoEmissaoFromJSONTyped(json, false);
}

export function NfePedidoEmissaoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NfePedidoEmissao {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'infNFe': NfeSefazInfNFeFromJSON(json['infNFe']),
        'infNFeSupl': !exists(json, 'infNFeSupl') ? undefined : NfeSefazInfNFeSuplFromJSON(json['infNFeSupl']),
        'ambiente': json['ambiente'],
        'referencia': !exists(json, 'referencia') ? undefined : json['referencia'],
    };
}

export function NfePedidoEmissaoToJSON(value?: NfePedidoEmissao | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'infNFe': NfeSefazInfNFeToJSON(value.infNFe),
        'infNFeSupl': NfeSefazInfNFeSuplToJSON(value.infNFeSupl),
        'ambiente': value.ambiente,
        'referencia': value.referencia,
    };
}

