/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NfeSefazImpostoDevolIPI } from './NfeSefazImpostoDevolIPI';
import {
    NfeSefazImpostoDevolIPIFromJSON,
    NfeSefazImpostoDevolIPIFromJSONTyped,
    NfeSefazImpostoDevolIPIToJSON,
} from './NfeSefazImpostoDevolIPI';

/**
 * 
 * @export
 * @interface NfeSefazImpostoDevol
 */
export interface NfeSefazImpostoDevol {
    /**
     * Percentual de mercadoria devolvida.
     * @type {number}
     * @memberof NfeSefazImpostoDevol
     */
    pDevol: number | null;
    /**
     * 
     * @type {NfeSefazImpostoDevolIPI}
     * @memberof NfeSefazImpostoDevol
     */
    IPI: NfeSefazImpostoDevolIPI;
}

/**
 * Check if a given object implements the NfeSefazImpostoDevol interface.
 */
export function instanceOfNfeSefazImpostoDevol(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "pDevol" in value;
    isInstance = isInstance && "IPI" in value;

    return isInstance;
}

export function NfeSefazImpostoDevolFromJSON(json: any): NfeSefazImpostoDevol {
    return NfeSefazImpostoDevolFromJSONTyped(json, false);
}

export function NfeSefazImpostoDevolFromJSONTyped(json: any, ignoreDiscriminator: boolean): NfeSefazImpostoDevol {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pDevol': json['pDevol'],
        'IPI': NfeSefazImpostoDevolIPIFromJSON(json['IPI']),
    };
}

export function NfeSefazImpostoDevolToJSON(value?: NfeSefazImpostoDevol | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pDevol': value.pDevol,
        'IPI': NfeSefazImpostoDevolIPIToJSON(value.IPI),
    };
}

