/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Tributção pelo ICMS 51 - Diferimento. A exigência do preenchimento das informações do ICMS diferido fica à critério de cada UF.
 * @export
 * @interface NfeSefazICMS51
 */
export interface NfeSefazICMS51 {
    /**
     * Origem da mercadoria:
     * * 0 - Nacional, exceto as indicadas nos códigos 3, 4, 5 e 8;
     * * 1 - Estrangeira - Importação direta, exceto a indicada no código 6;
     * * 2 - Estrangeira - Adquirida no mercado interno, exceto a indicada no código 7;
     * * 3 - Nacional, mercadoria ou bem com Conteúdo de Importação superior a 40%% e inferior ou igual a 70%%;
     * * 4 - Nacional, cuja produção tenha sido feita em conformidade com os processos produtivos básicos de que tratam as legislações citadas nos Ajustes;
     * * 5 - Nacional, mercadoria ou bem com Conteúdo de Importação inferior ou igual a 40%%;
     * * 6 - Estrangeira - Importação direta, sem similar nacional, constante em lista da CAMEX e gás natural;
     * * 7 - Estrangeira - Adquirida no mercado interno, sem similar nacional, constante lista CAMEX e gás natural;
     * * 8 - Nacional, mercadoria ou bem com Conteúdo de Importação superior a 70%%.
     * @type {number}
     * @memberof NfeSefazICMS51
     */
    orig: number | null;
    /**
     * Tributação pelo ICMS 51 - Tributação com Diferimento.
     * @type {string}
     * @memberof NfeSefazICMS51
     */
    CST: string | null;
    /**
     * Modalidade de determinação da BC do ICMS:
     * * 0 - Margem Valor Agregado (%%)
     * * 1 - Pauta (valor)
     * * 2 - Preço Tabelado Máximo (valor)
     * * 3 - Valor da Operação
     * @type {number}
     * @memberof NfeSefazICMS51
     */
    modBC?: number | null;
    /**
     * Percentual de redução da BC.
     * @type {number}
     * @memberof NfeSefazICMS51
     */
    pRedBC?: number | null;
    /**
     * Código de Benefício Fiscal na UF aplicado ao item quando houver RBC.
     * @type {string}
     * @memberof NfeSefazICMS51
     */
    cBenefRBC?: string | null;
    /**
     * Valor da BC do ICMS.
     * @type {number}
     * @memberof NfeSefazICMS51
     */
    vBC?: number | null;
    /**
     * Alíquota do imposto.
     * @type {number}
     * @memberof NfeSefazICMS51
     */
    pICMS?: number | null;
    /**
     * Valor do ICMS da Operação.
     * @type {number}
     * @memberof NfeSefazICMS51
     */
    vICMSOp?: number | null;
    /**
     * Percentual do diferemento.
     * @type {number}
     * @memberof NfeSefazICMS51
     */
    pDif?: number | null;
    /**
     * Valor do ICMS da diferido.
     * @type {number}
     * @memberof NfeSefazICMS51
     */
    vICMSDif?: number | null;
    /**
     * Valor do ICMS.
     * @type {number}
     * @memberof NfeSefazICMS51
     */
    vICMS?: number | null;
    /**
     * Valor da Base de cálculo do FCP.
     * @type {number}
     * @memberof NfeSefazICMS51
     */
    vBCFCP?: number | null;
    /**
     * Percentual de ICMS relativo ao Fundo de Combate à Pobreza (FCP).
     * @type {number}
     * @memberof NfeSefazICMS51
     */
    pFCP?: number | null;
    /**
     * Valor do ICMS relativo ao Fundo de Combate à Pobreza (FCP).
     * @type {number}
     * @memberof NfeSefazICMS51
     */
    vFCP?: number | null;
    /**
     * Percentual do diferimento do ICMS relativo ao Fundo de Combate à Pobreza (FCP).
     * @type {number}
     * @memberof NfeSefazICMS51
     */
    pFCPDif?: number | null;
    /**
     * Valor do ICMS relativo ao Fundo de Combate à Pobreza (FCP) diferido.
     * @type {number}
     * @memberof NfeSefazICMS51
     */
    vFCPDif?: number | null;
    /**
     * Valor efetivo do ICMS relativo ao Fundo de Combate à Pobreza (FCP).
     * @type {number}
     * @memberof NfeSefazICMS51
     */
    vFCPEfet?: number | null;
}

/**
 * Check if a given object implements the NfeSefazICMS51 interface.
 */
export function instanceOfNfeSefazICMS51(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "orig" in value;
    isInstance = isInstance && "CST" in value;

    return isInstance;
}

export function NfeSefazICMS51FromJSON(json: any): NfeSefazICMS51 {
    return NfeSefazICMS51FromJSONTyped(json, false);
}

export function NfeSefazICMS51FromJSONTyped(json: any, ignoreDiscriminator: boolean): NfeSefazICMS51 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orig': json['orig'],
        'CST': json['CST'],
        'modBC': !exists(json, 'modBC') ? undefined : json['modBC'],
        'pRedBC': !exists(json, 'pRedBC') ? undefined : json['pRedBC'],
        'cBenefRBC': !exists(json, 'cBenefRBC') ? undefined : json['cBenefRBC'],
        'vBC': !exists(json, 'vBC') ? undefined : json['vBC'],
        'pICMS': !exists(json, 'pICMS') ? undefined : json['pICMS'],
        'vICMSOp': !exists(json, 'vICMSOp') ? undefined : json['vICMSOp'],
        'pDif': !exists(json, 'pDif') ? undefined : json['pDif'],
        'vICMSDif': !exists(json, 'vICMSDif') ? undefined : json['vICMSDif'],
        'vICMS': !exists(json, 'vICMS') ? undefined : json['vICMS'],
        'vBCFCP': !exists(json, 'vBCFCP') ? undefined : json['vBCFCP'],
        'pFCP': !exists(json, 'pFCP') ? undefined : json['pFCP'],
        'vFCP': !exists(json, 'vFCP') ? undefined : json['vFCP'],
        'pFCPDif': !exists(json, 'pFCPDif') ? undefined : json['pFCPDif'],
        'vFCPDif': !exists(json, 'vFCPDif') ? undefined : json['vFCPDif'],
        'vFCPEfet': !exists(json, 'vFCPEfet') ? undefined : json['vFCPEfet'],
    };
}

export function NfeSefazICMS51ToJSON(value?: NfeSefazICMS51 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'orig': value.orig,
        'CST': value.CST,
        'modBC': value.modBC,
        'pRedBC': value.pRedBC,
        'cBenefRBC': value.cBenefRBC,
        'vBC': value.vBC,
        'pICMS': value.pICMS,
        'vICMSOp': value.vICMSOp,
        'pDif': value.pDif,
        'vICMSDif': value.vICMSDif,
        'vICMS': value.vICMS,
        'vBCFCP': value.vBCFCP,
        'pFCP': value.pFCP,
        'vFCP': value.vFCP,
        'pFCPDif': value.pFCPDif,
        'vFCPDif': value.vFCPDif,
        'vFCPEfet': value.vFCPEfet,
    };
}

