/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NfeSefazCIDE } from './NfeSefazCIDE';
import {
    NfeSefazCIDEFromJSON,
    NfeSefazCIDEFromJSONTyped,
    NfeSefazCIDEToJSON,
} from './NfeSefazCIDE';
import type { NfeSefazEncerrante } from './NfeSefazEncerrante';
import {
    NfeSefazEncerranteFromJSON,
    NfeSefazEncerranteFromJSONTyped,
    NfeSefazEncerranteToJSON,
} from './NfeSefazEncerrante';
import type { NfeSefazOrigComb } from './NfeSefazOrigComb';
import {
    NfeSefazOrigCombFromJSON,
    NfeSefazOrigCombFromJSONTyped,
    NfeSefazOrigCombToJSON,
} from './NfeSefazOrigComb';

/**
 * Informar apenas para operações com combustíveis líquidos.
 * @export
 * @interface NfeSefazComb
 */
export interface NfeSefazComb {
    /**
     * Código de produto da ANP. codificação de produtos do SIMP (http://www.anp.gov.br).
     * @type {number}
     * @memberof NfeSefazComb
     */
    cProdANP: number | null;
    /**
     * Descrição do Produto conforme ANP. Utilizar a descrição de produtos do Sistema de Informações de Movimentação de Produtos - SIMP (http://www.anp.gov.br/simp/).
     * @type {string}
     * @memberof NfeSefazComb
     */
    descANP: string | null;
    /**
     * Percentual do GLP derivado do petróleo no produto GLP (cProdANP=210203001). Informar em número decimal o percentual do GLP derivado de petróleo no produto GLP. Valores 0 a 100.
     * @type {number}
     * @memberof NfeSefazComb
     */
    pGLP?: number | null;
    /**
     * Percentual de gás natural nacional - GLGNn para o produto GLP (cProdANP=210203001). Informar em número decimal o percentual do Gás Natural Nacional - GLGNn para o produto GLP. Valores de 0 a 100.
     * @type {number}
     * @memberof NfeSefazComb
     */
    pGNn?: number | null;
    /**
     * Percentual de gás natural importado GLGNi para o produto GLP (cProdANP=210203001). Informar em número deciaml o percentual do Gás Natural Importado - GLGNi para o produto GLP. Valores de 0 a 100.
     * @type {number}
     * @memberof NfeSefazComb
     */
    pGNi?: number | null;
    /**
     * Valor de partida (cProdANP=210203001). Deve ser informado neste campo o valor por quilograma sem ICMS.
     * @type {number}
     * @memberof NfeSefazComb
     */
    vPart?: number | null;
    /**
     * Código de autorização / registro do CODIF. Informar apenas quando a UF utilizar o CODIF (Sistema de Controle do 			Diferimento do Imposto nas Operações com AEAC - Álcool Etílico Anidro Combustível).
     * @type {string}
     * @memberof NfeSefazComb
     */
    CODIF?: string | null;
    /**
     * Quantidade de combustível
     * faturada à temperatura ambiente.
     * Informar quando a quantidade
     * faturada informada no campo
     * qCom (I10) tiver sido ajustada para
     * uma temperatura diferente da
     * ambiente.
     * @type {number}
     * @memberof NfeSefazComb
     */
    qTemp?: number | null;
    /**
     * Sigla da UF de Consumo.
     * @type {string}
     * @memberof NfeSefazComb
     */
    UFCons: string | null;
    /**
     * 
     * @type {NfeSefazCIDE}
     * @memberof NfeSefazComb
     */
    CIDE?: NfeSefazCIDE;
    /**
     * 
     * @type {NfeSefazEncerrante}
     * @memberof NfeSefazComb
     */
    encerrante?: NfeSefazEncerrante;
    /**
     * Percentual do índice de mistura do Biodiesel (B100) no Óleo Diesel B instituído pelo órgão regulamentador.
     * @type {number}
     * @memberof NfeSefazComb
     */
    pBio?: number | null;
    /**
     * 
     * @type {Array<NfeSefazOrigComb>}
     * @memberof NfeSefazComb
     */
    origComb?: Array<NfeSefazOrigComb>;
}

/**
 * Check if a given object implements the NfeSefazComb interface.
 */
export function instanceOfNfeSefazComb(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "cProdANP" in value;
    isInstance = isInstance && "descANP" in value;
    isInstance = isInstance && "UFCons" in value;

    return isInstance;
}

export function NfeSefazCombFromJSON(json: any): NfeSefazComb {
    return NfeSefazCombFromJSONTyped(json, false);
}

export function NfeSefazCombFromJSONTyped(json: any, ignoreDiscriminator: boolean): NfeSefazComb {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cProdANP': json['cProdANP'],
        'descANP': json['descANP'],
        'pGLP': !exists(json, 'pGLP') ? undefined : json['pGLP'],
        'pGNn': !exists(json, 'pGNn') ? undefined : json['pGNn'],
        'pGNi': !exists(json, 'pGNi') ? undefined : json['pGNi'],
        'vPart': !exists(json, 'vPart') ? undefined : json['vPart'],
        'CODIF': !exists(json, 'CODIF') ? undefined : json['CODIF'],
        'qTemp': !exists(json, 'qTemp') ? undefined : json['qTemp'],
        'UFCons': json['UFCons'],
        'CIDE': !exists(json, 'CIDE') ? undefined : NfeSefazCIDEFromJSON(json['CIDE']),
        'encerrante': !exists(json, 'encerrante') ? undefined : NfeSefazEncerranteFromJSON(json['encerrante']),
        'pBio': !exists(json, 'pBio') ? undefined : json['pBio'],
        'origComb': !exists(json, 'origComb') ? undefined : ((json['origComb'] as Array<any>).map(NfeSefazOrigCombFromJSON)),
    };
}

export function NfeSefazCombToJSON(value?: NfeSefazComb | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cProdANP': value.cProdANP,
        'descANP': value.descANP,
        'pGLP': value.pGLP,
        'pGNn': value.pGNn,
        'pGNi': value.pGNi,
        'vPart': value.vPart,
        'CODIF': value.CODIF,
        'qTemp': value.qTemp,
        'UFCons': value.UFCons,
        'CIDE': NfeSefazCIDEToJSON(value.CIDE),
        'encerrante': NfeSefazEncerranteToJSON(value.encerrante),
        'pBio': value.pBio,
        'origComb': value.origComb === undefined ? undefined : ((value.origComb as Array<any>).map(NfeSefazOrigCombToJSON)),
    };
}

