/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NfeSefazIPINT } from './NfeSefazIPINT';
import {
    NfeSefazIPINTFromJSON,
    NfeSefazIPINTFromJSONTyped,
    NfeSefazIPINTToJSON,
} from './NfeSefazIPINT';
import type { NfeSefazIPITrib } from './NfeSefazIPITrib';
import {
    NfeSefazIPITribFromJSON,
    NfeSefazIPITribFromJSONTyped,
    NfeSefazIPITribToJSON,
} from './NfeSefazIPITrib';

/**
 * 
 * @export
 * @interface NfeSefazIpi
 */
export interface NfeSefazIpi {
    /**
     * CNPJ do produtor da mercadoria, quando diferente do emitente. Somente para os casos de exportação direta ou indireta.
     * @type {string}
     * @memberof NfeSefazIpi
     */
    CNPJProd?: string | null;
    /**
     * Código do selo de controle do IPI.
     * @type {string}
     * @memberof NfeSefazIpi
     */
    cSelo?: string | null;
    /**
     * Quantidade de selo de controle do IPI.
     * @type {number}
     * @memberof NfeSefazIpi
     */
    qSelo?: number | null;
    /**
     * Código de Enquadramento Legal do IPI (tabela a ser criada pela RFB).
     * @type {string}
     * @memberof NfeSefazIpi
     */
    cEnq: string | null;
    /**
     * 
     * @type {NfeSefazIPITrib}
     * @memberof NfeSefazIpi
     */
    IPITrib?: NfeSefazIPITrib;
    /**
     * 
     * @type {NfeSefazIPINT}
     * @memberof NfeSefazIpi
     */
    IPINT?: NfeSefazIPINT;
}

/**
 * Check if a given object implements the NfeSefazIpi interface.
 */
export function instanceOfNfeSefazIpi(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "cEnq" in value;

    return isInstance;
}

export function NfeSefazIpiFromJSON(json: any): NfeSefazIpi {
    return NfeSefazIpiFromJSONTyped(json, false);
}

export function NfeSefazIpiFromJSONTyped(json: any, ignoreDiscriminator: boolean): NfeSefazIpi {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'CNPJProd': !exists(json, 'CNPJProd') ? undefined : json['CNPJProd'],
        'cSelo': !exists(json, 'cSelo') ? undefined : json['cSelo'],
        'qSelo': !exists(json, 'qSelo') ? undefined : json['qSelo'],
        'cEnq': json['cEnq'],
        'IPITrib': !exists(json, 'IPITrib') ? undefined : NfeSefazIPITribFromJSON(json['IPITrib']),
        'IPINT': !exists(json, 'IPINT') ? undefined : NfeSefazIPINTFromJSON(json['IPINT']),
    };
}

export function NfeSefazIpiToJSON(value?: NfeSefazIpi | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'CNPJProd': value.CNPJProd,
        'cSelo': value.cSelo,
        'qSelo': value.qSelo,
        'cEnq': value.cEnq,
        'IPITrib': NfeSefazIPITribToJSON(value.IPITrib),
        'IPINT': NfeSefazIPINTToJSON(value.IPINT),
    };
}

