/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Tributação pelo ICMS
 * * 00 - Tributada integralmente
 * @export
 * @interface NfeSefazICMS00
 */
export interface NfeSefazICMS00 {
    /**
     * Origem da mercadoria:
     * * 0 - Nacional, exceto as indicadas nos códigos 3, 4, 5 e 8;
     * * 1 - Estrangeira - Importação direta, exceto a indicada no código 6;
     * * 2 - Estrangeira - Adquirida no mercado interno, exceto a indicada no código 7;
     * * 3 - Nacional, mercadoria ou bem com Conteúdo de Importação superior a 40%% e inferior ou igual a 70%%;
     * * 4 - Nacional, cuja produção tenha sido feita em conformidade com os processos produtivos básicos de que tratam as legislações citadas nos Ajustes;
     * * 5 - Nacional, mercadoria ou bem com Conteúdo de Importação inferior ou igual a 40%%;
     * * 6 - Estrangeira - Importação direta, sem similar nacional, constante em lista da CAMEX e gás natural;
     * * 7 - Estrangeira - Adquirida no mercado interno, sem similar nacional, constante lista CAMEX e gás natural;
     * * 8 - Nacional, mercadoria ou bem com Conteúdo de Importação superior a 70%%.
     * @type {number}
     * @memberof NfeSefazICMS00
     */
    orig: number | null;
    /**
     * Tributção pelo ICMS
     * * 00 - Tributada integralmente
     * @type {string}
     * @memberof NfeSefazICMS00
     */
    CST: string | null;
    /**
     * Modalidade de determinação da BC do ICMS:
     * * 0 - Margem Valor Agregado (%%)
     * * 1 - Pauta (valor)
     * * 2 - Preço Tabelado Máximo (valor)
     * * 3 - Valor da Operação
     * @type {number}
     * @memberof NfeSefazICMS00
     */
    modBC: number | null;
    /**
     * Valor da BC do ICMS.
     * @type {number}
     * @memberof NfeSefazICMS00
     */
    vBC: number | null;
    /**
     * Alíquota do ICMS.
     * @type {number}
     * @memberof NfeSefazICMS00
     */
    pICMS: number | null;
    /**
     * Valor do ICMS.
     * @type {number}
     * @memberof NfeSefazICMS00
     */
    vICMS: number | null;
    /**
     * Percentual de ICMS relativo ao Fundo de Combate à Pobreza (FCP).
     * @type {number}
     * @memberof NfeSefazICMS00
     */
    pFCP?: number | null;
    /**
     * Valor do ICMS relativo ao Fundo de Combate à Pobreza (FCP).
     * @type {number}
     * @memberof NfeSefazICMS00
     */
    vFCP?: number | null;
}

/**
 * Check if a given object implements the NfeSefazICMS00 interface.
 */
export function instanceOfNfeSefazICMS00(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "orig" in value;
    isInstance = isInstance && "CST" in value;
    isInstance = isInstance && "modBC" in value;
    isInstance = isInstance && "vBC" in value;
    isInstance = isInstance && "pICMS" in value;
    isInstance = isInstance && "vICMS" in value;

    return isInstance;
}

export function NfeSefazICMS00FromJSON(json: any): NfeSefazICMS00 {
    return NfeSefazICMS00FromJSONTyped(json, false);
}

export function NfeSefazICMS00FromJSONTyped(json: any, ignoreDiscriminator: boolean): NfeSefazICMS00 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orig': json['orig'],
        'CST': json['CST'],
        'modBC': json['modBC'],
        'vBC': json['vBC'],
        'pICMS': json['pICMS'],
        'vICMS': json['vICMS'],
        'pFCP': !exists(json, 'pFCP') ? undefined : json['pFCP'],
        'vFCP': !exists(json, 'vFCP') ? undefined : json['vFCP'],
    };
}

export function NfeSefazICMS00ToJSON(value?: NfeSefazICMS00 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'orig': value.orig,
        'CST': value.CST,
        'modBC': value.modBC,
        'vBC': value.vBC,
        'pICMS': value.pICMS,
        'vICMS': value.vICMS,
        'pFCP': value.pFCP,
        'vFCP': value.vFCP,
    };
}

