/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Informações do grupo de "encerrante".
 * @export
 * @interface NfeSefazEncerrante
 */
export interface NfeSefazEncerrante {
    /**
     * Numero de identificação do Bico utilizado no abastecimento.
     * @type {number}
     * @memberof NfeSefazEncerrante
     */
    nBico: number | null;
    /**
     * Numero de identificação da bomba ao qual o bico está interligado.
     * @type {number}
     * @memberof NfeSefazEncerrante
     */
    nBomba?: number | null;
    /**
     * Numero de identificação do tanque ao qual o bico está interligado.
     * @type {number}
     * @memberof NfeSefazEncerrante
     */
    nTanque: number | null;
    /**
     * Valor do Encerrante no ínicio do abastecimento.
     * @type {number}
     * @memberof NfeSefazEncerrante
     */
    vEncIni: number | null;
    /**
     * Valor do Encerrante no final do abastecimento.
     * @type {number}
     * @memberof NfeSefazEncerrante
     */
    vEncFin: number | null;
}

/**
 * Check if a given object implements the NfeSefazEncerrante interface.
 */
export function instanceOfNfeSefazEncerrante(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "nBico" in value;
    isInstance = isInstance && "nTanque" in value;
    isInstance = isInstance && "vEncIni" in value;
    isInstance = isInstance && "vEncFin" in value;

    return isInstance;
}

export function NfeSefazEncerranteFromJSON(json: any): NfeSefazEncerrante {
    return NfeSefazEncerranteFromJSONTyped(json, false);
}

export function NfeSefazEncerranteFromJSONTyped(json: any, ignoreDiscriminator: boolean): NfeSefazEncerrante {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nBico': json['nBico'],
        'nBomba': !exists(json, 'nBomba') ? undefined : json['nBomba'],
        'nTanque': json['nTanque'],
        'vEncIni': json['vEncIni'],
        'vEncFin': json['vEncFin'],
    };
}

export function NfeSefazEncerranteToJSON(value?: NfeSefazEncerrante | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nBico': value.nBico,
        'nBomba': value.nBomba,
        'nTanque': value.nTanque,
        'vEncIni': value.vEncIni,
        'vEncFin': value.vEncFin,
    };
}

