/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Armamentos.
 * @export
 * @interface NfeSefazArma
 */
export interface NfeSefazArma {
    /**
     * Indicador do tipo de arma de fogo (0 - Uso permitido; 1 - Uso restrito).
     * @type {number}
     * @memberof NfeSefazArma
     */
    tpArma: number | null;
    /**
     * Número de série da arma.
     * @type {string}
     * @memberof NfeSefazArma
     */
    nSerie: string | null;
    /**
     * Número de série do cano.
     * @type {string}
     * @memberof NfeSefazArma
     */
    nCano: string | null;
    /**
     * Descrição completa da arma, compreendendo: calibre, marca, capacidade, tipo de funcionamento, comprimento e demais elementos que permitam a sua perfeita identificação.
     * @type {string}
     * @memberof NfeSefazArma
     */
    descr: string | null;
}

/**
 * Check if a given object implements the NfeSefazArma interface.
 */
export function instanceOfNfeSefazArma(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "tpArma" in value;
    isInstance = isInstance && "nSerie" in value;
    isInstance = isInstance && "nCano" in value;
    isInstance = isInstance && "descr" in value;

    return isInstance;
}

export function NfeSefazArmaFromJSON(json: any): NfeSefazArma {
    return NfeSefazArmaFromJSONTyped(json, false);
}

export function NfeSefazArmaFromJSONTyped(json: any, ignoreDiscriminator: boolean): NfeSefazArma {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tpArma': json['tpArma'],
        'nSerie': json['nSerie'],
        'nCano': json['nCano'],
        'descr': json['descr'],
    };
}

export function NfeSefazArmaToJSON(value?: NfeSefazArma | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tpArma': value.tpArma,
        'nSerie': value.nSerie,
        'nCano': value.nCano,
        'descr': value.descr,
    };
}

