/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * grupo do detalhamento de Medicamentos e de matérias-primas farmacêuticas.
 * @export
 * @interface NfeSefazMed
 */
export interface NfeSefazMed {
    /**
     * Utilizar o número do registro ANVISA  ou preencher com o literal “ISENTO”, no caso de medicamento isento de registro na ANVISA.
     * @type {string}
     * @memberof NfeSefazMed
     */
    cProdANVISA: string | null;
    /**
     * Obs.: Para medicamento isento de registro na ANVISA, informar o número da decisão que o isenta, como por exemplo o número da Resolução da Diretoria Colegiada da ANVISA (RDC).
     * @type {string}
     * @memberof NfeSefazMed
     */
    xMotivoIsencao?: string | null;
    /**
     * Preço Máximo ao Consumidor.
     * @type {number}
     * @memberof NfeSefazMed
     */
    vPMC: number | null;
}

/**
 * Check if a given object implements the NfeSefazMed interface.
 */
export function instanceOfNfeSefazMed(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "cProdANVISA" in value;
    isInstance = isInstance && "vPMC" in value;

    return isInstance;
}

export function NfeSefazMedFromJSON(json: any): NfeSefazMed {
    return NfeSefazMedFromJSONTyped(json, false);
}

export function NfeSefazMedFromJSONTyped(json: any, ignoreDiscriminator: boolean): NfeSefazMed {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cProdANVISA': json['cProdANVISA'],
        'xMotivoIsencao': !exists(json, 'xMotivoIsencao') ? undefined : json['xMotivoIsencao'],
        'vPMC': json['vPMC'],
    };
}

export function NfeSefazMedToJSON(value?: NfeSefazMed | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cProdANVISA': value.cProdANVISA,
        'xMotivoIsencao': value.xMotivoIsencao,
        'vPMC': value.vPMC,
    };
}

