/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Endereço do emitente.
 * 
 * *Caso não seja informado, será utilizado o do cadastro da empresa.*
 * @export
 * @interface NfeSefazEnderEmi
 */
export interface NfeSefazEnderEmi {
    /**
     * Logradouro.
     * 
     * *Caso não seja informado, será utilizado o do cadastro da empresa.*
     * @type {string}
     * @memberof NfeSefazEnderEmi
     */
    xLgr?: string | null;
    /**
     * Número.
     * 
     * *Caso não seja informado, será utilizado o do cadastro da empresa.*
     * @type {string}
     * @memberof NfeSefazEnderEmi
     */
    nro?: string | null;
    /**
     * Complemento.
     * 
     * *Caso não seja informado, será utilizado o do cadastro da empresa.*
     * @type {string}
     * @memberof NfeSefazEnderEmi
     */
    xCpl?: string | null;
    /**
     * Bairro.
     * 
     * *Caso não seja informado, será utilizado o do cadastro da empresa.*
     * @type {string}
     * @memberof NfeSefazEnderEmi
     */
    xBairro?: string | null;
    /**
     * Código do município.
     * 
     * *Caso não seja informado, será utilizado o do cadastro da empresa.*
     * @type {string}
     * @memberof NfeSefazEnderEmi
     */
    cMun?: string | null;
    /**
     * Nome do município.
     * 
     * *Caso não seja informado, será utilizado o do cadastro da empresa.*
     * @type {string}
     * @memberof NfeSefazEnderEmi
     */
    xMun?: string | null;
    /**
     * Sigla da UF.
     * 
     * *Caso não seja informado, será utilizado o do cadastro da empresa.*
     * @type {string}
     * @memberof NfeSefazEnderEmi
     */
    UF?: string | null;
    /**
     * CEP - NT 2011/004.
     * 
     * *Caso não seja informado, será utilizado o do cadastro da empresa.*
     * @type {string}
     * @memberof NfeSefazEnderEmi
     */
    CEP?: string | null;
    /**
     * Código do país.
     * 
     * *Caso não seja informado, será utilizado o do cadastro da empresa.*
     * @type {string}
     * @memberof NfeSefazEnderEmi
     */
    cPais?: string | null;
    /**
     * Nome do país.
     * 
     * *Caso não seja informado, será utilizado o do cadastro da empresa.*
     * @type {string}
     * @memberof NfeSefazEnderEmi
     */
    xPais?: string | null;
    /**
     * Preencher com Código DDD + número do telefone (v.2.0).
     * 
     * *Caso não seja informado, será utilizado o do cadastro da empresa.*
     * @type {string}
     * @memberof NfeSefazEnderEmi
     */
    fone?: string | null;
}

/**
 * Check if a given object implements the NfeSefazEnderEmi interface.
 */
export function instanceOfNfeSefazEnderEmi(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NfeSefazEnderEmiFromJSON(json: any): NfeSefazEnderEmi {
    return NfeSefazEnderEmiFromJSONTyped(json, false);
}

export function NfeSefazEnderEmiFromJSONTyped(json: any, ignoreDiscriminator: boolean): NfeSefazEnderEmi {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'xLgr': !exists(json, 'xLgr') ? undefined : json['xLgr'],
        'nro': !exists(json, 'nro') ? undefined : json['nro'],
        'xCpl': !exists(json, 'xCpl') ? undefined : json['xCpl'],
        'xBairro': !exists(json, 'xBairro') ? undefined : json['xBairro'],
        'cMun': !exists(json, 'cMun') ? undefined : json['cMun'],
        'xMun': !exists(json, 'xMun') ? undefined : json['xMun'],
        'UF': !exists(json, 'UF') ? undefined : json['UF'],
        'CEP': !exists(json, 'CEP') ? undefined : json['CEP'],
        'cPais': !exists(json, 'cPais') ? undefined : json['cPais'],
        'xPais': !exists(json, 'xPais') ? undefined : json['xPais'],
        'fone': !exists(json, 'fone') ? undefined : json['fone'],
    };
}

export function NfeSefazEnderEmiToJSON(value?: NfeSefazEnderEmi | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'xLgr': value.xLgr,
        'nro': value.nro,
        'xCpl': value.xCpl,
        'xBairro': value.xBairro,
        'cMun': value.cMun,
        'xMun': value.xMun,
        'UF': value.UF,
        'CEP': value.CEP,
        'cPais': value.cPais,
        'xPais': value.xPais,
        'fone': value.fone,
    };
}

