/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Grupo de Informações do Intermediador da Transação.
 * @export
 * @interface NfeSefazInfIntermed
 */
export interface NfeSefazInfIntermed {
    /**
     * CNPJ do Intermediador da Transação (agenciador, plataforma de delivery, marketplace e similar) de serviços e de negócios.
     * @type {string}
     * @memberof NfeSefazInfIntermed
     */
    CNPJ: string | null;
    /**
     * Identificador cadastrado no intermediador.
     * @type {string}
     * @memberof NfeSefazInfIntermed
     */
    idCadIntTran: string | null;
}

/**
 * Check if a given object implements the NfeSefazInfIntermed interface.
 */
export function instanceOfNfeSefazInfIntermed(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "CNPJ" in value;
    isInstance = isInstance && "idCadIntTran" in value;

    return isInstance;
}

export function NfeSefazInfIntermedFromJSON(json: any): NfeSefazInfIntermed {
    return NfeSefazInfIntermedFromJSONTyped(json, false);
}

export function NfeSefazInfIntermedFromJSONTyped(json: any, ignoreDiscriminator: boolean): NfeSefazInfIntermed {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'CNPJ': json['CNPJ'],
        'idCadIntTran': json['idCadIntTran'],
    };
}

export function NfeSefazInfIntermedToJSON(value?: NfeSefazInfIntermed | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'CNPJ': value.CNPJ,
        'idCadIntTran': value.idCadIntTran,
    };
}

