/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NfeSefazDeduc } from './NfeSefazDeduc';
import {
    NfeSefazDeducFromJSON,
    NfeSefazDeducFromJSONTyped,
    NfeSefazDeducToJSON,
} from './NfeSefazDeduc';
import type { NfeSefazForDia } from './NfeSefazForDia';
import {
    NfeSefazForDiaFromJSON,
    NfeSefazForDiaFromJSONTyped,
    NfeSefazForDiaToJSON,
} from './NfeSefazForDia';

/**
 * Informações de registro aquisições de cana.
 * @export
 * @interface NfeSefazCana
 */
export interface NfeSefazCana {
    /**
     * Identificação da safra.
     * @type {string}
     * @memberof NfeSefazCana
     */
    safra: string | null;
    /**
     * Mês e Ano de Referência, formato: MM/AAAA.
     * @type {string}
     * @memberof NfeSefazCana
     */
    ref: string | null;
    /**
     * 
     * @type {Array<NfeSefazForDia>}
     * @memberof NfeSefazCana
     */
    forDia: Array<NfeSefazForDia>;
    /**
     * Total do mês.
     * @type {number}
     * @memberof NfeSefazCana
     */
    qTotMes: number | null;
    /**
     * Total Anterior.
     * @type {number}
     * @memberof NfeSefazCana
     */
    qTotAnt: number | null;
    /**
     * Total Geral.
     * @type {number}
     * @memberof NfeSefazCana
     */
    qTotGer: number | null;
    /**
     * 
     * @type {Array<NfeSefazDeduc>}
     * @memberof NfeSefazCana
     */
    deduc?: Array<NfeSefazDeduc>;
    /**
     * Valor  dos fornecimentos.
     * @type {number}
     * @memberof NfeSefazCana
     */
    vFor: number | null;
    /**
     * Valor Total das Deduções.
     * @type {number}
     * @memberof NfeSefazCana
     */
    vTotDed: number | null;
    /**
     * Valor Líquido dos fornecimentos.
     * @type {number}
     * @memberof NfeSefazCana
     */
    vLiqFor: number | null;
}

/**
 * Check if a given object implements the NfeSefazCana interface.
 */
export function instanceOfNfeSefazCana(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "safra" in value;
    isInstance = isInstance && "ref" in value;
    isInstance = isInstance && "forDia" in value;
    isInstance = isInstance && "qTotMes" in value;
    isInstance = isInstance && "qTotAnt" in value;
    isInstance = isInstance && "qTotGer" in value;
    isInstance = isInstance && "vFor" in value;
    isInstance = isInstance && "vTotDed" in value;
    isInstance = isInstance && "vLiqFor" in value;

    return isInstance;
}

export function NfeSefazCanaFromJSON(json: any): NfeSefazCana {
    return NfeSefazCanaFromJSONTyped(json, false);
}

export function NfeSefazCanaFromJSONTyped(json: any, ignoreDiscriminator: boolean): NfeSefazCana {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'safra': json['safra'],
        'ref': json['ref'],
        'forDia': ((json['forDia'] as Array<any>).map(NfeSefazForDiaFromJSON)),
        'qTotMes': json['qTotMes'],
        'qTotAnt': json['qTotAnt'],
        'qTotGer': json['qTotGer'],
        'deduc': !exists(json, 'deduc') ? undefined : ((json['deduc'] as Array<any>).map(NfeSefazDeducFromJSON)),
        'vFor': json['vFor'],
        'vTotDed': json['vTotDed'],
        'vLiqFor': json['vLiqFor'],
    };
}

export function NfeSefazCanaToJSON(value?: NfeSefazCana | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'safra': value.safra,
        'ref': value.ref,
        'forDia': ((value.forDia as Array<any>).map(NfeSefazForDiaToJSON)),
        'qTotMes': value.qTotMes,
        'qTotAnt': value.qTotAnt,
        'qTotGer': value.qTotGer,
        'deduc': value.deduc === undefined ? undefined : ((value.deduc as Array<any>).map(NfeSefazDeducToJSON)),
        'vFor': value.vFor,
        'vTotDed': value.vTotDed,
        'vLiqFor': value.vLiqFor,
    };
}

