/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NfeSefazDup } from './NfeSefazDup';
import {
    NfeSefazDupFromJSON,
    NfeSefazDupFromJSONTyped,
    NfeSefazDupToJSON,
} from './NfeSefazDup';
import type { NfeSefazFat } from './NfeSefazFat';
import {
    NfeSefazFatFromJSON,
    NfeSefazFatFromJSONTyped,
    NfeSefazFatToJSON,
} from './NfeSefazFat';

/**
 * Dados da cobrança da NF-e.
 * @export
 * @interface NfeSefazCobr
 */
export interface NfeSefazCobr {
    /**
     * 
     * @type {NfeSefazFat}
     * @memberof NfeSefazCobr
     */
    fat?: NfeSefazFat;
    /**
     * 
     * @type {Array<NfeSefazDup>}
     * @memberof NfeSefazCobr
     */
    dup?: Array<NfeSefazDup>;
}

/**
 * Check if a given object implements the NfeSefazCobr interface.
 */
export function instanceOfNfeSefazCobr(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NfeSefazCobrFromJSON(json: any): NfeSefazCobr {
    return NfeSefazCobrFromJSONTyped(json, false);
}

export function NfeSefazCobrFromJSONTyped(json: any, ignoreDiscriminator: boolean): NfeSefazCobr {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fat': !exists(json, 'fat') ? undefined : NfeSefazFatFromJSON(json['fat']),
        'dup': !exists(json, 'dup') ? undefined : ((json['dup'] as Array<any>).map(NfeSefazDupFromJSON)),
    };
}

export function NfeSefazCobrToJSON(value?: NfeSefazCobr | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fat': NfeSefazFatToJSON(value.fat),
        'dup': value.dup === undefined ? undefined : ((value.dup as Array<any>).map(NfeSefazDupToJSON)),
    };
}

