/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Dados da retenção  ICMS do Transporte.
 * @export
 * @interface NfeSefazRetTransp
 */
export interface NfeSefazRetTransp {
    /**
     * Valor do Serviço.
     * @type {number}
     * @memberof NfeSefazRetTransp
     */
    vServ: number | null;
    /**
     * BC da Retenção do ICMS.
     * @type {number}
     * @memberof NfeSefazRetTransp
     */
    vBCRet: number | null;
    /**
     * Alíquota da Retenção.
     * @type {number}
     * @memberof NfeSefazRetTransp
     */
    pICMSRet: number | null;
    /**
     * Valor do ICMS Retido.
     * @type {number}
     * @memberof NfeSefazRetTransp
     */
    vICMSRet: number | null;
    /**
     * Código Fiscal de Operações e Prestações.
     * @type {string}
     * @memberof NfeSefazRetTransp
     */
    CFOP: string | null;
    /**
     * Código do Município de Ocorrência do Fato Gerador (utilizar a tabela do IBGE).
     * @type {string}
     * @memberof NfeSefazRetTransp
     */
    cMunFG: string | null;
}

/**
 * Check if a given object implements the NfeSefazRetTransp interface.
 */
export function instanceOfNfeSefazRetTransp(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "vServ" in value;
    isInstance = isInstance && "vBCRet" in value;
    isInstance = isInstance && "pICMSRet" in value;
    isInstance = isInstance && "vICMSRet" in value;
    isInstance = isInstance && "CFOP" in value;
    isInstance = isInstance && "cMunFG" in value;

    return isInstance;
}

export function NfeSefazRetTranspFromJSON(json: any): NfeSefazRetTransp {
    return NfeSefazRetTranspFromJSONTyped(json, false);
}

export function NfeSefazRetTranspFromJSONTyped(json: any, ignoreDiscriminator: boolean): NfeSefazRetTransp {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'vServ': json['vServ'],
        'vBCRet': json['vBCRet'],
        'pICMSRet': json['pICMSRet'],
        'vICMSRet': json['vICMSRet'],
        'CFOP': json['CFOP'],
        'cMunFG': json['cMunFG'],
    };
}

export function NfeSefazRetTranspToJSON(value?: NfeSefazRetTransp | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'vServ': value.vServ,
        'vBCRet': value.vBCRet,
        'pICMSRet': value.pICMSRet,
        'vICMSRet': value.vICMSRet,
        'CFOP': value.CFOP,
        'cMunFG': value.cMunFG,
    };
}

