/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NfeSefazObsCont } from './NfeSefazObsCont';
import {
    NfeSefazObsContFromJSON,
    NfeSefazObsContFromJSONTyped,
    NfeSefazObsContToJSON,
} from './NfeSefazObsCont';
import type { NfeSefazObsFisco } from './NfeSefazObsFisco';
import {
    NfeSefazObsFiscoFromJSON,
    NfeSefazObsFiscoFromJSONTyped,
    NfeSefazObsFiscoToJSON,
} from './NfeSefazObsFisco';

/**
 * Grupo de observações de uso livre (para o item da NF-e).
 * @export
 * @interface NfeSefazObsItem
 */
export interface NfeSefazObsItem {
    /**
     * 
     * @type {NfeSefazObsCont}
     * @memberof NfeSefazObsItem
     */
    obsCont?: NfeSefazObsCont;
    /**
     * 
     * @type {NfeSefazObsFisco}
     * @memberof NfeSefazObsItem
     */
    obsFisco?: NfeSefazObsFisco;
}

/**
 * Check if a given object implements the NfeSefazObsItem interface.
 */
export function instanceOfNfeSefazObsItem(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NfeSefazObsItemFromJSON(json: any): NfeSefazObsItem {
    return NfeSefazObsItemFromJSONTyped(json, false);
}

export function NfeSefazObsItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): NfeSefazObsItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'obsCont': !exists(json, 'obsCont') ? undefined : NfeSefazObsContFromJSON(json['obsCont']),
        'obsFisco': !exists(json, 'obsFisco') ? undefined : NfeSefazObsFiscoFromJSON(json['obsFisco']),
    };
}

export function NfeSefazObsItemToJSON(value?: NfeSefazObsItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'obsCont': NfeSefazObsContToJSON(value.obsCont),
        'obsFisco': NfeSefazObsFiscoToJSON(value.obsFisco),
    };
}

