/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Código de Situação Tributária do PIS.
 * * 04 - Operação Tributável - Tributação Monofásica - (Alíquota Zero)
 * * 06 - Operação Tributável - Alíquota Zero
 * * 07 - Operação Isenta da contribuição
 * * 08 - Operação Sem Incidência da contribuição
 * * 09 - Operação com suspensão da contribuição
 * @export
 * @interface NfeSefazPISNT
 */
export interface NfeSefazPISNT {
    /**
     * Código de Situação Tributária do PIS.
     * * 04 - Operação Tributável - Tributação Monofásica - (Alíquota Zero)
     * * 05 - Operação Tributável (ST)
     * * 06 - Operação Tributável - Alíquota Zero
     * * 07 - Operação Isenta da contribuição
     * * 08 - Operação Sem Incidência da contribuição
     * * 09 - Operação com suspensão da contribuição
     * @type {string}
     * @memberof NfeSefazPISNT
     */
    CST: string | null;
}

/**
 * Check if a given object implements the NfeSefazPISNT interface.
 */
export function instanceOfNfeSefazPISNT(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "CST" in value;

    return isInstance;
}

export function NfeSefazPISNTFromJSON(json: any): NfeSefazPISNT {
    return NfeSefazPISNTFromJSONTyped(json, false);
}

export function NfeSefazPISNTFromJSONTyped(json: any, ignoreDiscriminator: boolean): NfeSefazPISNT {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'CST': json['CST'],
    };
}

export function NfeSefazPISNTToJSON(value?: NfeSefazPISNT | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'CST': value.CST,
    };
}

