/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Deduções - Taxas e Contribuições.
 * @export
 * @interface NfeSefazDeduc
 */
export interface NfeSefazDeduc {
    /**
     * Descrição da Dedução.
     * @type {string}
     * @memberof NfeSefazDeduc
     */
    xDed: string | null;
    /**
     * valor da dedução.
     * @type {number}
     * @memberof NfeSefazDeduc
     */
    vDed: number | null;
}

/**
 * Check if a given object implements the NfeSefazDeduc interface.
 */
export function instanceOfNfeSefazDeduc(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "xDed" in value;
    isInstance = isInstance && "vDed" in value;

    return isInstance;
}

export function NfeSefazDeducFromJSON(json: any): NfeSefazDeduc {
    return NfeSefazDeducFromJSONTyped(json, false);
}

export function NfeSefazDeducFromJSONTyped(json: any, ignoreDiscriminator: boolean): NfeSefazDeduc {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'xDed': json['xDed'],
        'vDed': json['vDed'],
    };
}

export function NfeSefazDeducToJSON(value?: NfeSefazDeduc | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'xDed': value.xDed,
        'vDed': value.vDed,
    };
}

