/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Tributação monofásica própria e com responsabilidade pela retenção sobre combustíveis.
 * @export
 * @interface NfeSefazICMS15
 */
export interface NfeSefazICMS15 {
    /**
     * Origem da mercadoria:
     * * 0 - Nacional, exceto as indicadas nos códigos 3, 4, 5 e 8;
     * * 1 - Estrangeira - Importação direta, exceto a indicada no código 6;
     * * 2 - Estrangeira - Adquirida no mercado interno, exceto a indicada no código 7;
     * * 3 - Nacional, mercadoria ou bem com Conteúdo de Importação superior a 40%% e inferior ou igual a 70%%;
     * * 4 - Nacional, cuja produção tenha sido feita em conformidade com os processos produtivos básicos de que tratam as legislações citadas nos Ajustes;
     * * 5 - Nacional, mercadoria ou bem com Conteúdo de Importação inferior ou igual a 40%%;
     * * 6 - Estrangeira - Importação direta, sem similar nacional, constante em lista da CAMEX e gás natural;
     * * 7 - Estrangeira - Adquirida no mercado interno, sem similar nacional, constante lista CAMEX e gás natural;
     * * 8 - Nacional, mercadoria ou bem com Conteúdo de Importação superior a 70%%.
     * @type {number}
     * @memberof NfeSefazICMS15
     */
    orig: number | null;
    /**
     * Tributção pelo ICMS
     * * 15 - Tributação monofásica própria e com responsabilidade pela retenção sobre combustíveis
     * @type {string}
     * @memberof NfeSefazICMS15
     */
    CST: string | null;
    /**
     * Quantidade tributada.
     * @type {number}
     * @memberof NfeSefazICMS15
     */
    qBCMono?: number | null;
    /**
     * Alíquota ad rem do imposto.
     * @type {number}
     * @memberof NfeSefazICMS15
     */
    adRemICMS: number | null;
    /**
     * Valor do ICMS próprio.
     * @type {number}
     * @memberof NfeSefazICMS15
     */
    vICMSMono: number | null;
    /**
     * Quantidade tributada sujeita a retenção.
     * @type {number}
     * @memberof NfeSefazICMS15
     */
    qBCMonoReten?: number | null;
    /**
     * Alíquota ad rem do imposto com retenção.
     * @type {number}
     * @memberof NfeSefazICMS15
     */
    adRemICMSReten: number | null;
    /**
     * Valor do ICMS com retenção.
     * @type {number}
     * @memberof NfeSefazICMS15
     */
    vICMSMonoReten: number | null;
    /**
     * Percentual de redução do valor da alíquota ad rem do ICMS.
     * @type {number}
     * @memberof NfeSefazICMS15
     */
    pRedAdRem?: number | null;
    /**
     * Motivo da redução do adrem
     * * 1 - Transporte coletivo de passageiros
     * * 9 - Outros
     * @type {number}
     * @memberof NfeSefazICMS15
     */
    motRedAdRem?: number | null;
}

/**
 * Check if a given object implements the NfeSefazICMS15 interface.
 */
export function instanceOfNfeSefazICMS15(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "orig" in value;
    isInstance = isInstance && "CST" in value;
    isInstance = isInstance && "adRemICMS" in value;
    isInstance = isInstance && "vICMSMono" in value;
    isInstance = isInstance && "adRemICMSReten" in value;
    isInstance = isInstance && "vICMSMonoReten" in value;

    return isInstance;
}

export function NfeSefazICMS15FromJSON(json: any): NfeSefazICMS15 {
    return NfeSefazICMS15FromJSONTyped(json, false);
}

export function NfeSefazICMS15FromJSONTyped(json: any, ignoreDiscriminator: boolean): NfeSefazICMS15 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orig': json['orig'],
        'CST': json['CST'],
        'qBCMono': !exists(json, 'qBCMono') ? undefined : json['qBCMono'],
        'adRemICMS': json['adRemICMS'],
        'vICMSMono': json['vICMSMono'],
        'qBCMonoReten': !exists(json, 'qBCMonoReten') ? undefined : json['qBCMonoReten'],
        'adRemICMSReten': json['adRemICMSReten'],
        'vICMSMonoReten': json['vICMSMonoReten'],
        'pRedAdRem': !exists(json, 'pRedAdRem') ? undefined : json['pRedAdRem'],
        'motRedAdRem': !exists(json, 'motRedAdRem') ? undefined : json['motRedAdRem'],
    };
}

export function NfeSefazICMS15ToJSON(value?: NfeSefazICMS15 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'orig': value.orig,
        'CST': value.CST,
        'qBCMono': value.qBCMono,
        'adRemICMS': value.adRemICMS,
        'vICMSMono': value.vICMSMono,
        'qBCMonoReten': value.qBCMonoReten,
        'adRemICMSReten': value.adRemICMSReten,
        'vICMSMonoReten': value.vICMSMonoReten,
        'pRedAdRem': value.pRedAdRem,
        'motRedAdRem': value.motRedAdRem,
    };
}

