/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DPS } from './DPS';
import {
    DPSFromJSON,
    DPSFromJSONTyped,
    DPSToJSON,
} from './DPS';
import type { NfseCancelamento } from './NfseCancelamento';
import {
    NfseCancelamentoFromJSON,
    NfseCancelamentoFromJSONTyped,
    NfseCancelamentoToJSON,
} from './NfseCancelamento';
import type { NfseMensagemRetorno } from './NfseMensagemRetorno';
import {
    NfseMensagemRetornoFromJSON,
    NfseMensagemRetornoFromJSONTyped,
    NfseMensagemRetornoToJSON,
} from './NfseMensagemRetorno';
import type { Rps } from './Rps';
import {
    RpsFromJSON,
    RpsFromJSONTyped,
    RpsToJSON,
} from './Rps';

/**
 * 
 * @export
 * @interface Nfse
 */
export interface Nfse {
    /**
     * ID único da nota gerado automaticamente pela API.
     * @type {string}
     * @memberof Nfse
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof Nfse
     */
    created_at?: Date;
    /**
     * 
     * @type {string}
     * @memberof Nfse
     */
    status?: NfseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Nfse
     */
    numero?: string;
    /**
     * 
     * @type {string}
     * @memberof Nfse
     */
    codigo_verificacao?: string;
    /**
     * 
     * @type {string}
     * @memberof Nfse
     */
    link_url?: string;
    /**
     * 
     * @type {Date}
     * @memberof Nfse
     */
    data_emissao?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Nfse
     */
    ambiente?: NfseAmbienteEnum;
    /**
     * 
     * @type {string}
     * @memberof Nfse
     */
    referencia?: string;
    /**
     * 
     * @type {DPS}
     * @memberof Nfse
     */
    DPS?: DPS;
    /**
     * 
     * @type {NfseCancelamento}
     * @memberof Nfse
     */
    cancelamento?: NfseCancelamento;
    /**
     * 
     * @type {Array<NfseMensagemRetorno>}
     * @memberof Nfse
     */
    mensagens?: Array<NfseMensagemRetorno>;
    /**
     * 
     * @type {Rps}
     * @memberof Nfse
     */
    declaracao_prestacao_servico?: Rps;
}


/**
 * @export
 */
export const NfseStatusEnum = {
    Processando: 'processando',
    Autorizada: 'autorizada',
    Negada: 'negada',
    Cancelada: 'cancelada',
    Substituida: 'substituida',
    Erro: 'erro'
} as const;
export type NfseStatusEnum = typeof NfseStatusEnum[keyof typeof NfseStatusEnum];

/**
 * @export
 */
export const NfseAmbienteEnum = {
    Homologacao: 'homologacao',
    Producao: 'producao'
} as const;
export type NfseAmbienteEnum = typeof NfseAmbienteEnum[keyof typeof NfseAmbienteEnum];


/**
 * Check if a given object implements the Nfse interface.
 */
export function instanceOfNfse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NfseFromJSON(json: any): Nfse {
    return NfseFromJSONTyped(json, false);
}

export function NfseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Nfse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'created_at': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'status': !exists(json, 'status') ? undefined : json['status'],
        'numero': !exists(json, 'numero') ? undefined : json['numero'],
        'codigo_verificacao': !exists(json, 'codigo_verificacao') ? undefined : json['codigo_verificacao'],
        'link_url': !exists(json, 'link_url') ? undefined : json['link_url'],
        'data_emissao': !exists(json, 'data_emissao') ? undefined : (json['data_emissao'] === null ? null : new Date(json['data_emissao'])),
        'ambiente': !exists(json, 'ambiente') ? undefined : json['ambiente'],
        'referencia': !exists(json, 'referencia') ? undefined : json['referencia'],
        'DPS': !exists(json, 'DPS') ? undefined : DPSFromJSON(json['DPS']),
        'cancelamento': !exists(json, 'cancelamento') ? undefined : NfseCancelamentoFromJSON(json['cancelamento']),
        'mensagens': !exists(json, 'mensagens') ? undefined : ((json['mensagens'] as Array<any>).map(NfseMensagemRetornoFromJSON)),
        'declaracao_prestacao_servico': !exists(json, 'declaracao_prestacao_servico') ? undefined : RpsFromJSON(json['declaracao_prestacao_servico']),
    };
}

export function NfseToJSON(value?: Nfse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'created_at': value.created_at === undefined ? undefined : (value.created_at.toISOString()),
        'status': value.status,
        'numero': value.numero,
        'codigo_verificacao': value.codigo_verificacao,
        'link_url': value.link_url,
        'data_emissao': value.data_emissao === undefined ? undefined : (value.data_emissao === null ? null : value.data_emissao.toISOString()),
        'ambiente': value.ambiente,
        'referencia': value.referencia,
        'DPS': DPSToJSON(value.DPS),
        'cancelamento': NfseCancelamentoToJSON(value.cancelamento),
        'mensagens': value.mensagens === undefined ? undefined : ((value.mensagens as Array<any>).map(NfseMensagemRetornoToJSON)),
        'declaracao_prestacao_servico': RpsToJSON(value.declaracao_prestacao_servico),
    };
}

