/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpsDadosTomadorEndereco } from './RpsDadosTomadorEndereco';
import {
    RpsDadosTomadorEnderecoFromJSON,
    RpsDadosTomadorEnderecoFromJSONTyped,
    RpsDadosTomadorEnderecoToJSON,
} from './RpsDadosTomadorEndereco';

/**
 * 
 * @export
 * @interface RpsDadosTomador
 */
export interface RpsDadosTomador {
    /**
     * CPF ou CNPJ do tomador/destinatário.
     * @type {string}
     * @memberof RpsDadosTomador
     */
    cpf_cnpj?: string;
    /**
     * Inscrição Municipal do tomador/destinatário.
     * @type {string}
     * @memberof RpsDadosTomador
     */
    inscricao_municipal?: string;
    /**
     * Nome ou Razão Social do tomador/destinatário.
     * @type {string}
     * @memberof RpsDadosTomador
     */
    nome_razao_social: string;
    /**
     * Telefone do tomador/destinatário.
     * @type {string}
     * @memberof RpsDadosTomador
     */
    fone?: string;
    /**
     * Email do tomador/destinatário.
     * @type {string}
     * @memberof RpsDadosTomador
     */
    email?: string;
    /**
     * 
     * @type {RpsDadosTomadorEndereco}
     * @memberof RpsDadosTomador
     */
    endereco?: RpsDadosTomadorEndereco;
}

/**
 * Check if a given object implements the RpsDadosTomador interface.
 */
export function instanceOfRpsDadosTomador(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "nome_razao_social" in value;

    return isInstance;
}

export function RpsDadosTomadorFromJSON(json: any): RpsDadosTomador {
    return RpsDadosTomadorFromJSONTyped(json, false);
}

export function RpsDadosTomadorFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpsDadosTomador {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cpf_cnpj': !exists(json, 'cpf_cnpj') ? undefined : json['cpf_cnpj'],
        'inscricao_municipal': !exists(json, 'inscricao_municipal') ? undefined : json['inscricao_municipal'],
        'nome_razao_social': json['nome_razao_social'],
        'fone': !exists(json, 'fone') ? undefined : json['fone'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'endereco': !exists(json, 'endereco') ? undefined : RpsDadosTomadorEnderecoFromJSON(json['endereco']),
    };
}

export function RpsDadosTomadorToJSON(value?: RpsDadosTomador | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cpf_cnpj': value.cpf_cnpj,
        'inscricao_municipal': value.inscricao_municipal,
        'nome_razao_social': value.nome_razao_social,
        'fone': value.fone,
        'email': value.email,
        'endereco': RpsDadosTomadorEnderecoToJSON(value.endereco),
    };
}

