/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Nfse } from './Nfse';
import {
    NfseFromJSON,
    NfseFromJSONTyped,
    NfseToJSON,
} from './Nfse';

/**
 * 
 * @export
 * @interface RpsLote
 */
export interface RpsLote {
    /**
     * ID único do lote gerado automaticamente pela API.
     * @type {string}
     * @memberof RpsLote
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof RpsLote
     */
    created_at?: Date;
    /**
     * 
     * @type {string}
     * @memberof RpsLote
     */
    status?: RpsLoteStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof RpsLote
     */
    numero?: string;
    /**
     * 
     * @type {string}
     * @memberof RpsLote
     */
    ambiente?: RpsLoteAmbienteEnum;
    /**
     * 
     * @type {string}
     * @memberof RpsLote
     */
    referencia?: string;
    /**
     * 
     * @type {Array<Nfse>}
     * @memberof RpsLote
     */
    notas?: Array<Nfse>;
}


/**
 * @export
 */
export const RpsLoteStatusEnum = {
    Novo: 'novo',
    FilaEnvio: 'fila_envio',
    FilaConsulta: 'fila_consulta',
    Processado: 'processado',
    Erro: 'erro'
} as const;
export type RpsLoteStatusEnum = typeof RpsLoteStatusEnum[keyof typeof RpsLoteStatusEnum];

/**
 * @export
 */
export const RpsLoteAmbienteEnum = {
    Homologacao: 'homologacao',
    Producao: 'producao'
} as const;
export type RpsLoteAmbienteEnum = typeof RpsLoteAmbienteEnum[keyof typeof RpsLoteAmbienteEnum];


/**
 * Check if a given object implements the RpsLote interface.
 */
export function instanceOfRpsLote(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RpsLoteFromJSON(json: any): RpsLote {
    return RpsLoteFromJSONTyped(json, false);
}

export function RpsLoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpsLote {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'created_at': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'status': !exists(json, 'status') ? undefined : json['status'],
        'numero': !exists(json, 'numero') ? undefined : json['numero'],
        'ambiente': !exists(json, 'ambiente') ? undefined : json['ambiente'],
        'referencia': !exists(json, 'referencia') ? undefined : json['referencia'],
        'notas': !exists(json, 'notas') ? undefined : ((json['notas'] as Array<any>).map(NfseFromJSON)),
    };
}

export function RpsLoteToJSON(value?: RpsLote | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'created_at': value.created_at === undefined ? undefined : (value.created_at.toISOString()),
        'status': value.status,
        'numero': value.numero,
        'ambiente': value.ambiente,
        'referencia': value.referencia,
        'notas': value.notas === undefined ? undefined : ((value.notas as Array<any>).map(NfseToJSON)),
    };
}

