/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpsServicoValores
 */
export interface RpsServicoValores {
    /**
     * Valor unitário do serviço.
     * @type {number}
     * @memberof RpsServicoValores
     */
    valor_unitario: number;
    /**
     * Valor total do serviço.
     * @type {number}
     * @memberof RpsServicoValores
     */
    valor_servicos?: number;
    /**
     * 
     * @type {number}
     * @memberof RpsServicoValores
     */
    valor_deducoes?: number;
    /**
     * 
     * @type {number}
     * @memberof RpsServicoValores
     */
    valor_pis?: number;
    /**
     * 
     * @type {number}
     * @memberof RpsServicoValores
     */
    valor_cofins?: number;
    /**
     * 
     * @type {number}
     * @memberof RpsServicoValores
     */
    valor_inss?: number;
    /**
     * 
     * @type {number}
     * @memberof RpsServicoValores
     */
    valor_ir?: number;
    /**
     * 
     * @type {number}
     * @memberof RpsServicoValores
     */
    valor_csll?: number;
    /**
     * 
     * @type {number}
     * @memberof RpsServicoValores
     */
    valor_outras_retencoes?: number;
    /**
     * 
     * @type {number}
     * @memberof RpsServicoValores
     */
    valor_iss?: number;
    /**
     * 
     * @type {number}
     * @memberof RpsServicoValores
     */
    valor_iss_retido?: number;
    /**
     * 
     * @type {number}
     * @memberof RpsServicoValores
     */
    valor_liquido?: number;
    /**
     * 
     * @type {number}
     * @memberof RpsServicoValores
     */
    aliquota_iss?: number;
    /**
     * 
     * @type {number}
     * @memberof RpsServicoValores
     */
    aliquota_pis?: number;
    /**
     * 
     * @type {number}
     * @memberof RpsServicoValores
     */
    aliquota_cofins?: number;
    /**
     * 
     * @type {number}
     * @memberof RpsServicoValores
     */
    aliquota_inss?: number;
    /**
     * 
     * @type {number}
     * @memberof RpsServicoValores
     */
    aliquota_ir?: number;
    /**
     * 
     * @type {number}
     * @memberof RpsServicoValores
     */
    aliquota_csll?: number;
    /**
     * 
     * @type {number}
     * @memberof RpsServicoValores
     */
    desconto_incondicionado?: number;
    /**
     * 
     * @type {number}
     * @memberof RpsServicoValores
     */
    desconto_condicionado?: number;
}

/**
 * Check if a given object implements the RpsServicoValores interface.
 */
export function instanceOfRpsServicoValores(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "valor_unitario" in value;

    return isInstance;
}

export function RpsServicoValoresFromJSON(json: any): RpsServicoValores {
    return RpsServicoValoresFromJSONTyped(json, false);
}

export function RpsServicoValoresFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpsServicoValores {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'valor_unitario': json['valor_unitario'],
        'valor_servicos': !exists(json, 'valor_servicos') ? undefined : json['valor_servicos'],
        'valor_deducoes': !exists(json, 'valor_deducoes') ? undefined : json['valor_deducoes'],
        'valor_pis': !exists(json, 'valor_pis') ? undefined : json['valor_pis'],
        'valor_cofins': !exists(json, 'valor_cofins') ? undefined : json['valor_cofins'],
        'valor_inss': !exists(json, 'valor_inss') ? undefined : json['valor_inss'],
        'valor_ir': !exists(json, 'valor_ir') ? undefined : json['valor_ir'],
        'valor_csll': !exists(json, 'valor_csll') ? undefined : json['valor_csll'],
        'valor_outras_retencoes': !exists(json, 'valor_outras_retencoes') ? undefined : json['valor_outras_retencoes'],
        'valor_iss': !exists(json, 'valor_iss') ? undefined : json['valor_iss'],
        'valor_iss_retido': !exists(json, 'valor_iss_retido') ? undefined : json['valor_iss_retido'],
        'valor_liquido': !exists(json, 'valor_liquido') ? undefined : json['valor_liquido'],
        'aliquota_iss': !exists(json, 'aliquota_iss') ? undefined : json['aliquota_iss'],
        'aliquota_pis': !exists(json, 'aliquota_pis') ? undefined : json['aliquota_pis'],
        'aliquota_cofins': !exists(json, 'aliquota_cofins') ? undefined : json['aliquota_cofins'],
        'aliquota_inss': !exists(json, 'aliquota_inss') ? undefined : json['aliquota_inss'],
        'aliquota_ir': !exists(json, 'aliquota_ir') ? undefined : json['aliquota_ir'],
        'aliquota_csll': !exists(json, 'aliquota_csll') ? undefined : json['aliquota_csll'],
        'desconto_incondicionado': !exists(json, 'desconto_incondicionado') ? undefined : json['desconto_incondicionado'],
        'desconto_condicionado': !exists(json, 'desconto_condicionado') ? undefined : json['desconto_condicionado'],
    };
}

export function RpsServicoValoresToJSON(value?: RpsServicoValores | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'valor_unitario': value.valor_unitario,
        'valor_servicos': value.valor_servicos,
        'valor_deducoes': value.valor_deducoes,
        'valor_pis': value.valor_pis,
        'valor_cofins': value.valor_cofins,
        'valor_inss': value.valor_inss,
        'valor_ir': value.valor_ir,
        'valor_csll': value.valor_csll,
        'valor_outras_retencoes': value.valor_outras_retencoes,
        'valor_iss': value.valor_iss,
        'valor_iss_retido': value.valor_iss_retido,
        'valor_liquido': value.valor_liquido,
        'aliquota_iss': value.aliquota_iss,
        'aliquota_pis': value.aliquota_pis,
        'aliquota_cofins': value.aliquota_cofins,
        'aliquota_inss': value.aliquota_inss,
        'aliquota_ir': value.aliquota_ir,
        'aliquota_csll': value.aliquota_csll,
        'desconto_incondicionado': value.desconto_incondicionado,
        'desconto_condicionado': value.desconto_condicionado,
    };
}

