/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RTCListaDoc } from './RTCListaDoc';
import {
    RTCListaDocFromJSON,
    RTCListaDocFromJSONTyped,
    RTCListaDocToJSON,
} from './RTCListaDoc';

/**
 * Grupo de informações relativas a valores incluídos neste documento e recebidos por motivo de estarem relacionadas
 * a operações de terceiros, objeto de reembolso, repasse ou ressarcimento pelo recebedor, já tributados e aqui referenciados.
 * @export
 * @interface RTCInfoReeRepRes
 */
export interface RTCInfoReeRepRes {
    /**
     * 
     * @type {Array<RTCListaDoc>}
     * @memberof RTCInfoReeRepRes
     */
    documentos: Array<RTCListaDoc>;
}

/**
 * Check if a given object implements the RTCInfoReeRepRes interface.
 */
export function instanceOfRTCInfoReeRepRes(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "documentos" in value;

    return isInstance;
}

export function RTCInfoReeRepResFromJSON(json: any): RTCInfoReeRepRes {
    return RTCInfoReeRepResFromJSONTyped(json, false);
}

export function RTCInfoReeRepResFromJSONTyped(json: any, ignoreDiscriminator: boolean): RTCInfoReeRepRes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'documentos': ((json['documentos'] as Array<any>).map(RTCListaDocFromJSON)),
    };
}

export function RTCInfoReeRepResToJSON(value?: RTCInfoReeRepRes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'documentos': ((value.documentos as Array<any>).map(RTCListaDocToJSON)),
    };
}

