/* tslint:disable */
/* eslint-disable */
/**
 * ACBr API
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * The version of the OpenAPI document: 3.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RTCListaDocDFe } from './RTCListaDocDFe';
import {
    RTCListaDocDFeFromJSON,
    RTCListaDocDFeFromJSONTyped,
    RTCListaDocDFeToJSON,
} from './RTCListaDocDFe';
import type { RTCListaDocFiscalOutro } from './RTCListaDocFiscalOutro';
import {
    RTCListaDocFiscalOutroFromJSON,
    RTCListaDocFiscalOutroFromJSONTyped,
    RTCListaDocFiscalOutroToJSON,
} from './RTCListaDocFiscalOutro';
import type { RTCListaDocFornec } from './RTCListaDocFornec';
import {
    RTCListaDocFornecFromJSON,
    RTCListaDocFornecFromJSONTyped,
    RTCListaDocFornecToJSON,
} from './RTCListaDocFornec';
import type { RTCListaDocOutro } from './RTCListaDocOutro';
import {
    RTCListaDocOutroFromJSON,
    RTCListaDocOutroFromJSONTyped,
    RTCListaDocOutroToJSON,
} from './RTCListaDocOutro';

/**
 * Grupo relativo aos documentos referenciados nos casos de reembolso, repasse e ressarcimento que serão
 * considerados na base de cálculo do ISSQN, do IBS e da CBS.
 * @export
 * @interface RTCListaDoc
 */
export interface RTCListaDoc {
    /**
     * 
     * @type {RTCListaDocDFe}
     * @memberof RTCListaDoc
     */
    dFeNacional?: RTCListaDocDFe;
    /**
     * 
     * @type {RTCListaDocFiscalOutro}
     * @memberof RTCListaDoc
     */
    docFiscalOutro?: RTCListaDocFiscalOutro;
    /**
     * 
     * @type {RTCListaDocOutro}
     * @memberof RTCListaDoc
     */
    docOutro?: RTCListaDocOutro;
    /**
     * 
     * @type {RTCListaDocFornec}
     * @memberof RTCListaDoc
     */
    fornec?: RTCListaDocFornec;
    /**
     * Data da emissão do documento dedutível
     * Ano, mês e dia (AAAA-MM-DD).
     * @type {Date}
     * @memberof RTCListaDoc
     */
    dtEmiDoc: Date | null;
    /**
     * Data da competência do documento dedutível
     * Ano, mês e dia (AAAA-MM-DD).
     * @type {Date}
     * @memberof RTCListaDoc
     */
    dtCompDoc: Date | null;
    /**
     * Tipo de valor incluído neste documento, recebido por motivo de estarem relacionadas a operações de terceiros,
     * objeto de reembolso, repasse ou ressarcimento pelo recebedor, já tributados e aqui referenciados.
     * @type {string}
     * @memberof RTCListaDoc
     */
    tpReeRepRes: string | null;
    /**
     * Descrição do reembolso ou ressarcimento quando a opção é
     * "99 - Outros reembolsos ou ressarcimentos recebidos por valores pagos relativos a operações por conta e ordem de terceiro".
     * @type {string}
     * @memberof RTCListaDoc
     */
    xTpReeRepRes?: string | null;
    /**
     * Valor monetário (total ou parcial, conforme documento informado) utilizado para não inclusão na base de cálculo
     * do ISS e do IBS e da CBS da NFS-e que está sendo emitida (R$).
     * @type {number}
     * @memberof RTCListaDoc
     */
    vlrReeRepRes: number | null;
}

/**
 * Check if a given object implements the RTCListaDoc interface.
 */
export function instanceOfRTCListaDoc(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "dtEmiDoc" in value;
    isInstance = isInstance && "dtCompDoc" in value;
    isInstance = isInstance && "tpReeRepRes" in value;
    isInstance = isInstance && "vlrReeRepRes" in value;

    return isInstance;
}

export function RTCListaDocFromJSON(json: any): RTCListaDoc {
    return RTCListaDocFromJSONTyped(json, false);
}

export function RTCListaDocFromJSONTyped(json: any, ignoreDiscriminator: boolean): RTCListaDoc {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dFeNacional': !exists(json, 'dFeNacional') ? undefined : RTCListaDocDFeFromJSON(json['dFeNacional']),
        'docFiscalOutro': !exists(json, 'docFiscalOutro') ? undefined : RTCListaDocFiscalOutroFromJSON(json['docFiscalOutro']),
        'docOutro': !exists(json, 'docOutro') ? undefined : RTCListaDocOutroFromJSON(json['docOutro']),
        'fornec': !exists(json, 'fornec') ? undefined : RTCListaDocFornecFromJSON(json['fornec']),
        'dtEmiDoc': (json['dtEmiDoc'] === null ? null : new Date(json['dtEmiDoc'])),
        'dtCompDoc': (json['dtCompDoc'] === null ? null : new Date(json['dtCompDoc'])),
        'tpReeRepRes': json['tpReeRepRes'],
        'xTpReeRepRes': !exists(json, 'xTpReeRepRes') ? undefined : json['xTpReeRepRes'],
        'vlrReeRepRes': json['vlrReeRepRes'],
    };
}

export function RTCListaDocToJSON(value?: RTCListaDoc | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dFeNacional': RTCListaDocDFeToJSON(value.dFeNacional),
        'docFiscalOutro': RTCListaDocFiscalOutroToJSON(value.docFiscalOutro),
        'docOutro': RTCListaDocOutroToJSON(value.docOutro),
        'fornec': RTCListaDocFornecToJSON(value.fornec),
        'dtEmiDoc': (value.dtEmiDoc === null ? null : value.dtEmiDoc.toISOString().substr(0,10)),
        'dtCompDoc': (value.dtCompDoc === null ? null : value.dtCompDoc.toISOString().substr(0,10)),
        'tpReeRepRes': value.tpReeRepRes,
        'xTpReeRepRes': value.xTpReeRepRes,
        'vlrReeRepRes': value.vlrReeRepRes,
    };
}

